/**
 * TypeScript type definitions for session management
 */

import { SaveOasSpecSummaryDto } from './chat';

// ============================================================================
// Content Part Type (for multimodal message content)
// Spec 2026-02-17: Multi-File Upload + URL References for SA and PM Chat
// ============================================================================

/**
 * Content part union type for multimodal OpenAI messages.
 * Duplicated from openaiClient.ts to avoid circular dependencies.
 * Used for storing conversation history in sessions when content is an array.
 *
 * Spec 2026-02-17: Multi-File Upload + URL References for SA and PM Chat
 */
export type ContentPart =
  | { type: 'text'; text: string }
  | { type: 'image_url'; image_url: { url: string; detail?: string } }
  | { type: 'file'; file: { file_data: string; filename: string } };

// ============================================================================
// OpenAI Message Type (for conversation storage)
// ============================================================================

/**
 * Message format for OpenAI conversations.
 * Duplicated from openaiClient.ts to avoid circular dependencies.
 * Used for storing conversation history in sessions.
 *
 * Spec 2026-02-17: Multi-File Upload + URL References for SA and PM Chat
 * - Changed content from `string` to `string | ContentPart[]` to support
 *   multimodal messages with text, image, and file content parts.
 */
export interface OpenAIMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content: string | ContentPart[];
  tool_call_id?: string;
  tool_calls?: {
    id: string;
    type: 'function';
    function: {
      name: string;
      arguments: string;
    };
  }[];
}

// ============================================================================
// Session Types
// ============================================================================

/**
 * Gateway session state stored in memory.
 * Tracks conversation context and OpenAI conversation ID.
 */
export interface GatewaySession {
  /** Frontend session ID (provided by client) */
  sessionId: string;

  /** Internal MCP session ID (generated by Gateway, never exposed to frontend) */
  mcpSessionId: string;

  /** OpenAI conversation ID for maintaining history */
  openaiConversationId?: string;

  /** Last used architecture model filename */
  filename?: string;

  /** Last selected interface ID */
  interfaceId?: string;

  /** Last draft OAS content (for context in subsequent turns) */
  lastDraftOas?: string;

  /** Last saved spec summary (if save_oas_spec was called) */
  lastSavedSpecSummary?: SaveOasSpecSummaryDto;

  /**
   * Conversation history for multi-turn context.
   * Excludes system prompt (rebuilt fresh per-request from buildSystemPrompt).
   * Includes: user messages, assistant messages (with tool_calls), and tool result messages.
   */
  conversation?: OpenAIMessage[];

  /** Session creation timestamp */
  createdAt: Date;

  /** Last activity timestamp (updated on each request) */
  lastActivity: Date;
}

/**
 * Partial update for session fields
 */
export type SessionUpdate = Partial<Omit<GatewaySession, 'sessionId' | 'createdAt'>>;

// ============================================================================
// Session Store Interface
// ============================================================================

/**
 * Interface for session storage operations.
 * Allows for different implementations (in-memory, Redis, etc.)
 */
export interface SessionStore {
  /**
   * Get a session by ID
   * @param sessionId - The session ID to look up
   * @returns The session or null if not found
   */
  get(sessionId: string): GatewaySession | null;

  /**
   * Create or update a session
   * @param sessionId - The session ID
   * @param session - The session data
   */
  set(sessionId: string, session: GatewaySession): void;

  /**
   * Delete a session
   * @param sessionId - The session ID to delete
   * @returns true if session was deleted, false if not found
   */
  delete(sessionId: string): boolean;

  /**
   * Clean up expired sessions
   * @returns Number of sessions cleaned up
   */
  cleanup(): number;
}
