"""
Report generator module for creating Markdown and JSON reports.
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from .categories import FileCategories


class ReportGenerator:
    """Generates reports summarizing the standards extraction process."""
    
    def __init__(self, output_dir: str):
        """
        Initialize report generator.
        
        Args:
            output_dir: Output directory path (used as identifier)
        """
        self.output_dir = output_dir
        self.timestamp = datetime.now().isoformat()
    
    def generate_summary(self, standards_generated: Dict[str, str], output_dir: str) -> Path:
        """
        Generate a simple summary report with just the standards generated.
        This is a simplified version for when full context is not available.
        
        Args:
            standards_generated: Dictionary mapping standard files to output paths
            output_dir: Output directory for reports
            
        Returns:
            Path to the generated REPORT.md file
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Generate simple Markdown report
        report = f"# Standards Extraction Report\n\n"
        report += f"**Output Directory:** {output_dir}\n\n"
        report += f"**Generated:** {self.timestamp}\n\n"
        report += "---\n\n"
        report += "## Standards Generated\n\n"
        report += f"A total of {len(standards_generated)} coding standard documents were generated:\n\n"
        
        for standard_file, file_path in sorted(standards_generated.items()):
            report += f"- **{standard_file}**\n"
            report += f"  - Location: `{file_path}`\n"
        
        report += "\n---\n\n"
        report += f"*Report generated by Standards Extractor on {self.timestamp}*\n"
        
        markdown_path = output_path / 'REPORT.md'
        with open(markdown_path, 'w', encoding='utf-8') as f:
            f.write(report)
        
        return markdown_path
    
    def generate_report(self, 
                       sources: List[str],
                       files_scanned: Dict[str, List[str]],
                       analyses_count: int,
                       standards_generated: Dict[str, str],
                       output_dir: str):
        """
        Generate both Markdown and JSON reports.
        
        Args:
            sources: List of source URLs/paths
            files_scanned: Dictionary of categorized files
            analyses_count: Number of files analyzed
            standards_generated: Dictionary mapping standard files to output paths
            output_dir: Output directory for reports
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Generate Markdown report
        markdown_report = self._generate_markdown_report(
            sources, files_scanned, analyses_count, standards_generated
        )
        markdown_path = output_path / 'REPORT.md'
        with open(markdown_path, 'w', encoding='utf-8') as f:
            f.write(markdown_report)
        
        # Generate JSON report
        json_report = self._generate_json_report(
            sources, files_scanned, analyses_count, standards_generated
        )
        json_path = output_path / 'report.json'
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(json_report, f, indent=2, ensure_ascii=False)
        
        print(f"Reports generated:")
        print(f"  - Markdown: {markdown_path}")
        print(f"  - JSON: {json_path}")
    
    def _generate_markdown_report(self,
                                  sources: List[str],
                                  files_scanned: Dict[str, List[str]],
                                  analyses_count: int,
                                  standards_generated: Dict[str, str]) -> str:
        """Generate Markdown report."""
        report = f"# Standards Extraction Report\n\n"
        report += f"**Output Directory:** {self.output_dir}\n\n"
        report += f"**Generated:** {self.timestamp}\n\n"
        report += "---\n\n"
        
        # Executive Summary
        report += "## Executive Summary\n\n"
        total_files = sum(len(files) for files in files_scanned.values())
        report += f"This report summarizes the automated extraction of coding standards from {len(sources)} source(s). "
        report += f"A total of {total_files} files were scanned, {analyses_count} were analyzed, "
        report += f"and {len(standards_generated)} standard documents were generated.\n\n"
        
        # Sources
        report += "## Sources Analyzed\n\n"
        for i, source in enumerate(sources, 1):
            report += f"{i}. `{source}`\n"
        report += "\n"
        
        # Files Scanned
        report += "## Files Scanned\n\n"
        report += "The following table shows the breakdown of files scanned by category:\n\n"
        report += "| Category | Count | Percentage |\n"
        report += "|----------|-------|------------|\n"
        
        for category in FileCategories.ALL:
            count = len(files_scanned.get(category, []))
            percentage = (count / total_files * 100) if total_files > 0 else 0
            report += f"| {category.title()} | {count} | {percentage:.1f}% |\n"
        
        report += f"| **Total** | **{total_files}** | **100.0%** |\n\n"
        
        # Standards Generated
        report += "## Standards Generated\n\n"
        report += f"A total of {len(standards_generated)} coding standard documents were generated:\n\n"
        
        # Group by category
        by_category = {}
        for standard_file in sorted(standards_generated.keys()):
            category = standard_file.split('/')[0] if '/' in standard_file else 'other'
            if category not in by_category:
                by_category[category] = []
            by_category[category].append(standard_file)
        
        for category in sorted(by_category.keys()):
            report += f"### {category.title()}\n\n"
            for standard_file in by_category[category]:
                output_path = standards_generated[standard_file]
                report += f"- **{standard_file}**\n"
                report += f"  - Location: `{output_path}`\n"
            report += "\n"
        
        # File Mapping
        report += "## Detailed File Mapping\n\n"
        report += "The following sections show which source files contributed to each standard.\n\n"
        
        for category in FileCategories.CODE_CATEGORIES:
            category_files = files_scanned.get(category, [])
            if not category_files:
                continue
            
            report += f"### {category.title()} Files\n\n"
            for file_path in sorted(category_files)[:20]:  # Limit to first 20
                report += f"- `{file_path}`\n"
            
            if len(category_files) > 20:
                report += f"\n*... and {len(category_files) - 20} more files*\n"
            report += "\n"
        
        # Dependency Files
        dependency_files = files_scanned.get('dependency', [])
        if dependency_files:
            report += "### Dependency Files\n\n"
            for file_path in sorted(dependency_files):
                report += f"- `{file_path}`\n"
            report += "\n"
        
        # Next Steps
        report += "## Next Steps\n\n"
        report += "The generated coding standards are ready for review and integration into your development workflow. "
        report += "Consider the following next steps:\n\n"
        report += "1. **Review** each generated standard document for accuracy and completeness\n"
        report += "2. **Customize** the standards to better fit your team's specific needs\n"
        report += "3. **Integrate** the standards into your development documentation\n"
        report += "4. **Share** the standards with your development team\n"
        report += "5. **Update** your CI/CD pipelines to enforce these standards\n\n"
        
        # Footer
        report += "---\n\n"
        report += f"*Report generated by Standards Extractor on {self.timestamp}*\n"
        
        return report
    
    def _generate_json_report(self,
                             sources: List[str],
                             files_scanned: Dict[str, List[str]],
                             analyses_count: int,
                             standards_generated: Dict[str, str]) -> Dict:
        """Generate JSON report."""
        total_files = sum(len(files) for files in files_scanned.values())
        
        return {
            "output_dir": self.output_dir,
            "timestamp": self.timestamp,
            "summary": {
                "sources_count": len(sources),
                "total_files_scanned": total_files,
                "files_analyzed": analyses_count,
                "standards_generated": len(standards_generated)
            },
            "sources": sources,
            "files_scanned": {
                category: {
                    "count": len(files),
                    "files": files
                }
                for category, files in files_scanned.items()
            },
            "standards_generated": [
                {
                    "standard_file": standard_file,
                    "output_path": output_path,
                    "category": standard_file.split('/')[0] if '/' in standard_file else 'other'
                }
                for standard_file, output_path in standards_generated.items()
            ],
            "statistics": {
                "files_by_category": {
                    category: len(files)
                    for category, files in files_scanned.items()
                },
                "standards_by_category": self._count_standards_by_category(standards_generated)
            }
        }
    
    def _count_standards_by_category(self, standards_generated: Dict[str, str]) -> Dict[str, int]:
        """Count standards by category."""
        counts = {}
        for standard_file in standards_generated.keys():
            category = standard_file.split('/')[0] if '/' in standard_file else 'other'
            counts[category] = counts.get(category, 0) + 1
        return counts
