package com.example.architecturemodel.repository.entity;

import com.example.architecturemodel.model.dto.GeneratedMigrationBookOfWorkDto;
import com.example.architecturemodel.model.entity.GeneratedMigrationBookOfWorkEntity;
import com.example.architecturemodel.model.entity.GeneratedMigrationBookOfWorkStatus;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Persistence-layer tests for {@link GeneratedMigrationBookOfWorkEntity} and
 * {@link GeneratedMigrationBookOfWorkRepository}, introduced by Liquibase
 * changeset {@code 139}.
 *
 * <p>Spec: Product Manager Migration Delivery Plan + Draft Book-of-Work
 * Generation (2026-05-17) -- Task Group 1.</p>
 *
 * <p>Tests covered:</p>
 * <ol>
 *   <li>An entity with all four JSONB columns populated round-trips through
 *       persist + reload (each blob's content matches).</li>
 *   <li>An entity with all four JSONB columns NULL persists and reloads cleanly
 *       (Q-14 -- partial drafts representable).</li>
 *   <li>PATCH semantics: an update touching only {@code title} + {@code status}
 *       does NOT wipe the four JSONB columns (boxed-type + null-guard per
 *       {@code project_primitive_double_dto_overwrite.md}).</li>
 *   <li>Status transitions {@code draft -> reviewed -> saved} round-trip cleanly
 *       and {@code updatedAt} advances on each update.</li>
 *   <li>The {@code findByProjectId} / {@code findByProjectIdAndStatusIn}
 *       repository finders return only matching rows.</li>
 *   <li>{@code findActiveDraftForTuple} returns the single active row for a
 *       {@code (projectId, currentArchitectureId, targetArchitectureId)} tuple
 *       and excludes archived rows (Q-6).</li>
 * </ol>
 *
 * <p>The H2 PostgreSQL-mode test DB does not natively understand JSONB, so a
 * {@code CREATE DOMAIN JSONB AS JSON} INIT alias is registered on the JDBC
 * URL -- same pattern used by {@link EndpointProtocolMetadataPersistenceTest}.</p>
 *
 * <p>Note on the {@code chk_gmbw_status} CHECK constraint: that constraint is
 * declared on Liquibase changeset 139 and is the source of truth in production,
 * but {@code @DataJpaTest} rebuilds the schema from Hibernate's JPA mapping
 * (not from the SQL changeset), so CHECK enforcement is exercised by the
 * standard AMS Liquibase smoke path -- not duplicated here. Status validation
 * at the service layer is via
 * {@link GeneratedMigrationBookOfWorkStatus#ALL}.</p>
 */
@DataJpaTest
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@TestPropertySource(properties = {
    "spring.datasource.url=jdbc:h2:mem:gmbwpersistencedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE DOMAIN IF NOT EXISTS JSONB AS JSON"
})
class GeneratedMigrationBookOfWorkPersistenceTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private GeneratedMigrationBookOfWorkRepository repository;

    private GeneratedMigrationBookOfWorkEntity buildEntity(
        UUID id, UUID projectId, UUID currentArchId, UUID targetArchId, String status) {
        return GeneratedMigrationBookOfWorkEntity.builder()
            .id(id)
            .projectId(projectId)
            .currentArchitectureId(currentArchId)
            .targetArchitectureId(targetArchId)
            .status(status)
            .title("Draft for tuple " + currentArchId + " -> " + targetArchId)
            .summary("Auto-generated by the PM migration delivery plan task.")
            .build();
    }

    @Test
    @DisplayName("Entity with all four JSONB columns populated round-trips through persist + reload")
    void allFourJsonbColumnsRoundTrip() {
        UUID id = UUID.randomUUID();
        UUID projectId = UUID.randomUUID();
        UUID currentArch = UUID.randomUUID();
        UUID targetArch = UUID.randomUUID();

        Map<String, Object> generationInputs = new LinkedHashMap<>();
        generationInputs.put("product_definition_ref", "pd-1");
        generationInputs.put("architecture_refs", List.of("arch-current", "arch-target"));
        generationInputs.put("mapping_refs", List.of("map-1", "map-2"));

        Map<String, Object> generationSummary = new LinkedHashMap<>();
        generationSummary.put("initiative_count", 3);
        generationSummary.put("epic_count", 8);
        generationSummary.put("feature_count", 17);
        generationSummary.put("story_count", 42);

        Map<String, Object> qualityAssessment = new LinkedHashMap<>();
        qualityAssessment.put("overall_score", 0.82);
        qualityAssessment.put("rationale", "All workstreams covered; 2 unresolved findings flagged.");

        Map<String, Object> bookOfWork = new LinkedHashMap<>();
        bookOfWork.put("items", List.of(
            Map.of("id", "i-1", "type", "initiative", "title", "Stand up target services"),
            Map.of("id", "e-1", "type", "epic", "parentId", "i-1", "title", "Service A core")
        ));

        GeneratedMigrationBookOfWorkEntity entity = buildEntity(
            id, projectId, currentArch, targetArch, GeneratedMigrationBookOfWorkStatus.DRAFT);
        entity.setGenerationInputsJson(generationInputs);
        entity.setGenerationSummaryJson(generationSummary);
        entity.setQualityAssessmentJson(qualityAssessment);
        entity.setBookOfWorkJson(bookOfWork);

        repository.save(entity);
        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity reloaded = repository.findById(id).orElseThrow();

        assertThat(reloaded.getProjectId()).isEqualTo(projectId);
        assertThat(reloaded.getCurrentArchitectureId()).isEqualTo(currentArch);
        assertThat(reloaded.getTargetArchitectureId()).isEqualTo(targetArch);
        assertThat(reloaded.getStatus()).isEqualTo(GeneratedMigrationBookOfWorkStatus.DRAFT);
        assertThat(reloaded.getCreatedByTask()).isEqualTo("product-manager--migration-delivery-plan");

        assertThat(reloaded.getGenerationInputsJson())
            .containsEntry("product_definition_ref", "pd-1");
        assertThat(reloaded.getGenerationSummaryJson())
            .containsEntry("initiative_count", 3)
            .containsEntry("epic_count", 8)
            .containsEntry("feature_count", 17)
            .containsEntry("story_count", 42);
        assertThat(reloaded.getQualityAssessmentJson())
            .containsEntry("overall_score", 0.82)
            .containsEntry("rationale", "All workstreams covered; 2 unresolved findings flagged.");
        assertThat(reloaded.getBookOfWorkJson()).containsKey("items");
    }

    @Test
    @DisplayName("Entity with all four JSONB columns NULL persists and reloads cleanly (Q-14)")
    void allFourJsonbColumnsNullableRoundTrip() {
        UUID id = UUID.randomUUID();
        UUID projectId = UUID.randomUUID();

        GeneratedMigrationBookOfWorkEntity entity = buildEntity(
            id, projectId, UUID.randomUUID(), UUID.randomUUID(),
            GeneratedMigrationBookOfWorkStatus.DRAFT);
        // Leave the four JSONB fields unset -- mirrors a partial / recovery draft.

        repository.save(entity);
        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity reloaded = repository.findById(id).orElseThrow();
        assertThat(reloaded.getGenerationInputsJson()).isNull();
        assertThat(reloaded.getGenerationSummaryJson()).isNull();
        assertThat(reloaded.getQualityAssessmentJson()).isNull();
        assertThat(reloaded.getBookOfWorkJson()).isNull();
    }

    /**
     * PATCH semantics test: when an update touches only {@code title} +
     * {@code status} and leaves the four JSONB DTO fields {@code null},
     * the existing JSONB column content MUST survive the update untouched.
     *
     * <p>This is the canonical null-guard pattern from
     * {@code project_primitive_double_dto_overwrite.md}: the DTO fields are
     * boxed {@link Map} references (not primitives), so Jackson maps a missing
     * JSON property to {@code null} and the call site null-guards each field
     * before assigning onto the loaded entity.</p>
     */
    @Test
    @DisplayName("PATCH touching only title + status does NOT wipe the four JSONB columns")
    void patchOmittedJsonbFieldsDoNotWipeColumns() {
        UUID id = UUID.randomUUID();
        UUID projectId = UUID.randomUUID();

        Map<String, Object> originalBookOfWork = new LinkedHashMap<>();
        originalBookOfWork.put("items", List.of(Map.of("id", "i-1", "type", "initiative")));

        Map<String, Object> originalQuality = new LinkedHashMap<>();
        originalQuality.put("overall_score", 0.75);

        GeneratedMigrationBookOfWorkEntity persisted = buildEntity(
            id, projectId, UUID.randomUUID(), UUID.randomUUID(),
            GeneratedMigrationBookOfWorkStatus.DRAFT);
        persisted.setBookOfWorkJson(originalBookOfWork);
        persisted.setQualityAssessmentJson(originalQuality);
        repository.save(persisted);
        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity loaded = repository.findById(id).orElseThrow();

        // Simulate a PATCH-style DTO with only title + status set and the four
        // JSONB fields omitted (null on the wire).
        GeneratedMigrationBookOfWorkDto patch = new GeneratedMigrationBookOfWorkDto(
            id,
            projectId,
            loaded.getCurrentArchitectureId(),
            loaded.getTargetArchitectureId(),
            GeneratedMigrationBookOfWorkStatus.REVIEWED,
            "Renamed title",
            null,
            null,  // generation_inputs_json omitted
            null,  // generation_summary_json omitted
            null,  // quality_assessment_json omitted
            null,  // book_of_work_json omitted
            null,
            null,
            null,
            null,
            null
        );

        // Null-guard pattern: only assign each field when present on the DTO.
        if (patch.title() != null) {
            loaded.setTitle(patch.title());
        }
        if (patch.status() != null) {
            loaded.setStatus(patch.status());
        }
        if (patch.generationInputsJson() != null) {
            loaded.setGenerationInputsJson(patch.generationInputsJson());
        }
        if (patch.generationSummaryJson() != null) {
            loaded.setGenerationSummaryJson(patch.generationSummaryJson());
        }
        if (patch.qualityAssessmentJson() != null) {
            loaded.setQualityAssessmentJson(patch.qualityAssessmentJson());
        }
        if (patch.bookOfWorkJson() != null) {
            loaded.setBookOfWorkJson(patch.bookOfWorkJson());
        }

        repository.save(loaded);
        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity reloaded = repository.findById(id).orElseThrow();
        assertThat(reloaded.getTitle()).isEqualTo("Renamed title");
        assertThat(reloaded.getStatus()).isEqualTo(GeneratedMigrationBookOfWorkStatus.REVIEWED);
        // Critical: the four JSONB columns survived even though the DTO fields
        // were null on the wire.
        assertThat(reloaded.getQualityAssessmentJson())
            .as("quality_assessment_json must survive a PATCH that omits the field")
            .isNotNull()
            .containsEntry("overall_score", 0.75);
        assertThat(reloaded.getBookOfWorkJson())
            .as("book_of_work_json must survive a PATCH that omits the field")
            .isNotNull()
            .containsKey("items");
    }

    @Test
    @DisplayName("Status transitions draft -> reviewed -> saved round-trip cleanly")
    void statusTransitionsRoundTrip() {
        UUID id = UUID.randomUUID();
        UUID projectId = UUID.randomUUID();

        GeneratedMigrationBookOfWorkEntity entity = buildEntity(
            id, projectId, UUID.randomUUID(), UUID.randomUUID(),
            GeneratedMigrationBookOfWorkStatus.DRAFT);
        repository.save(entity);
        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity firstReload = repository.findById(id).orElseThrow();
        assertThat(firstReload.getStatus()).isEqualTo(GeneratedMigrationBookOfWorkStatus.DRAFT);

        firstReload.setStatus(GeneratedMigrationBookOfWorkStatus.REVIEWED);
        repository.save(firstReload);
        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity secondReload = repository.findById(id).orElseThrow();
        assertThat(secondReload.getStatus()).isEqualTo(GeneratedMigrationBookOfWorkStatus.REVIEWED);

        secondReload.setStatus(GeneratedMigrationBookOfWorkStatus.SAVED);
        repository.save(secondReload);
        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity finalReload = repository.findById(id).orElseThrow();
        assertThat(finalReload.getStatus()).isEqualTo(GeneratedMigrationBookOfWorkStatus.SAVED);
        // All six declared status values are valid; sanity-check membership.
        assertThat(GeneratedMigrationBookOfWorkStatus.ALL)
            .contains(GeneratedMigrationBookOfWorkStatus.DRAFT,
                     GeneratedMigrationBookOfWorkStatus.REVIEWED,
                     GeneratedMigrationBookOfWorkStatus.SAVED,
                     GeneratedMigrationBookOfWorkStatus.ARCHIVED,
                     GeneratedMigrationBookOfWorkStatus.PARTIALLY_SAVED,
                     GeneratedMigrationBookOfWorkStatus.FAILED);
    }

    @Test
    @DisplayName("findByProjectId and findByProjectIdAndStatusIn return only matching rows")
    void projectIdFilterReturnsOnlyMatchingRows() {
        UUID projectA = UUID.randomUUID();
        UUID projectB = UUID.randomUUID();

        repository.save(buildEntity(UUID.randomUUID(), projectA, UUID.randomUUID(), UUID.randomUUID(),
            GeneratedMigrationBookOfWorkStatus.DRAFT));
        repository.save(buildEntity(UUID.randomUUID(), projectA, UUID.randomUUID(), UUID.randomUUID(),
            GeneratedMigrationBookOfWorkStatus.SAVED));
        repository.save(buildEntity(UUID.randomUUID(), projectA, UUID.randomUUID(), UUID.randomUUID(),
            GeneratedMigrationBookOfWorkStatus.ARCHIVED));
        repository.save(buildEntity(UUID.randomUUID(), projectB, UUID.randomUUID(), UUID.randomUUID(),
            GeneratedMigrationBookOfWorkStatus.DRAFT));
        entityManager.flush();
        entityManager.clear();

        List<GeneratedMigrationBookOfWorkEntity> allForA = repository.findByProjectId(projectA);
        assertThat(allForA).hasSize(3);
        assertThat(allForA).allMatch(r -> r.getProjectId().equals(projectA));

        List<GeneratedMigrationBookOfWorkEntity> activeForA =
            repository.findByProjectIdAndStatusIn(projectA, GeneratedMigrationBookOfWorkStatus.ACTIVE);
        assertThat(activeForA).hasSize(2);
        assertThat(activeForA)
            .extracting(GeneratedMigrationBookOfWorkEntity::getStatus)
            .containsExactlyInAnyOrder(
                GeneratedMigrationBookOfWorkStatus.DRAFT,
                GeneratedMigrationBookOfWorkStatus.SAVED);

        List<GeneratedMigrationBookOfWorkEntity> allForB = repository.findByProjectId(projectB);
        assertThat(allForB).hasSize(1);
        assertThat(allForB.get(0).getProjectId()).isEqualTo(projectB);
    }

    @Test
    @DisplayName("findActiveDraftForTuple returns the single active row and excludes archived (Q-6)")
    void findActiveDraftForTupleExcludesArchived() {
        UUID projectId = UUID.randomUUID();
        UUID currentArch = UUID.randomUUID();
        UUID targetArch = UUID.randomUUID();
        UUID otherTargetArch = UUID.randomUUID();

        // Archived prior draft for the tuple.
        repository.save(buildEntity(UUID.randomUUID(), projectId, currentArch, targetArch,
            GeneratedMigrationBookOfWorkStatus.ARCHIVED));
        // The current active draft for the tuple.
        UUID activeId = UUID.randomUUID();
        repository.save(buildEntity(activeId, projectId, currentArch, targetArch,
            GeneratedMigrationBookOfWorkStatus.DRAFT));
        // A draft for a DIFFERENT tuple -- must not be returned.
        repository.save(buildEntity(UUID.randomUUID(), projectId, currentArch, otherTargetArch,
            GeneratedMigrationBookOfWorkStatus.DRAFT));
        entityManager.flush();
        entityManager.clear();

        var active = repository.findActiveDraftForTuple(projectId, currentArch, targetArch);
        assertThat(active).isPresent();
        assertThat(active.get().getId()).isEqualTo(activeId);
        assertThat(active.get().getStatus()).isEqualTo(GeneratedMigrationBookOfWorkStatus.DRAFT);

        // Sanity: archived rows are excluded from the active-lookup result.
        List<GeneratedMigrationBookOfWorkEntity> all = repository.findByProjectId(projectId);
        assertThat(all).hasSize(3);
    }
}
