package com.example.architecturemodel.service.export.terraform;

import com.example.architecturemodel.model.dto.ArchitectureDto;
import com.example.architecturemodel.model.dto.ArchitectureModelDto;
import com.example.architecturemodel.model.dto.MetaModelDto;
import com.example.architecturemodel.model.dto.MetaModelEntitiesDto;
import com.example.architecturemodel.model.dto.ProjectDto;
import com.example.architecturemodel.model.dto.entity.EnvironmentDto;
import com.example.architecturemodel.model.dto.entity.NetworkDto;
import com.example.architecturemodel.service.ArchitectureService;
import com.example.architecturemodel.service.ModelService;
import com.example.architecturemodel.service.ProjectService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link TerraformAssembler} and {@link TerraformExportService}.
 *
 * <p>Spec: 2026-05-08-infrastructure-terraform-export-gcp -- Task Group 5.
 */
class TerraformExportServiceTest {

    private ModelService modelService;
    private ProjectService projectService;
    private ArchitectureService architectureService;
    private TerraformAssembler assembler;
    private GcpTerraformExporter gcpExporter;

    @TempDir
    Path tempDir;

    private static final UUID PROJECT_ID = UUID.fromString("00000000-0000-0000-0000-000000000001");
    private static final UUID ARCH_ID = UUID.fromString("00000000-0000-0000-0000-000000000002");
    private static final String ENV_ID = "env-1";

    @BeforeEach
    void setUp() {
        modelService = mock(ModelService.class);
        projectService = mock(ProjectService.class);
        architectureService = mock(ArchitectureService.class);
        assembler = new TerraformAssembler();
        gcpExporter = new GcpTerraformExporter();
    }

    // ---------- Assembler tests ----------

    @Test
    void assembler_groupsByTargetFile_andAddsHeadersAndPlaceholders() {
        TerraformContext ctx = ctx();
        EmittedResource main = new EmittedResource(
            "main.tf",
            "resource \"google_compute_network\" \"prod_app_vpc\" {}\n",
            List.of("# Infrastructure concept: Network", "# Architecture entity: App VPC"),
            List.of()
        );
        EmittedResource var1 = new EmittedResource(
            "variables.tf",
            "variable \"project_id\" { type = string }\n",
            List.of(),
            List.of()
        );

        TerraformAssembler.AssembledOutput out = assembler.assemble(List.of(main, var1), ctx);

        Map<String, String> files = out.filesByName();
        assertTrue(files.containsKey("main.tf"));
        assertTrue(files.containsKey("variables.tf"));
        assertTrue(files.containsKey("outputs.tf"));
        assertTrue(files.containsKey("README.md"));
        assertTrue(files.get("main.tf").contains("# Generated by Infrastructure Terraform Export"));
        assertTrue(files.get("main.tf").contains("# Provider: GCP"));
        assertTrue(files.get("main.tf").contains("# Infrastructure concept: Network"));
        assertTrue(files.get("main.tf").contains("google_compute_network"));
        assertTrue(files.get("outputs.tf").contains("(no resources of this kind generated)"));
    }

    @Test
    void assembler_parsesTerraformVariableHints_objectFormat_intoVariableBlocks() {
        String hints = "{\"image_tag\":{\"type\":\"string\",\"description\":\"Container image tag\",\"default\":\"latest\"}}";
        NetworkDto net = TerraformTestFixtures.buildRecord(NetworkDto.class, Map.of(
            "id", "net-1",
            "name", "App VPC",
            "environment_id", ENV_ID,
            "terraform_variable_hints", hints
        ));
        MetaModelEntitiesDto entities = TerraformTestFixtures.entitiesWith(Map.of(
            "networks", List.of(net)
        ));
        TerraformContext ctx = new TerraformContext(
            entities, TerraformTestFixtures.emptyRelationships(), env(), null, null, "GCP");

        TerraformAssembler.AssembledOutput out = assembler.assemble(List.of(), ctx);

        String vars = out.filesByName().get("variables.tf");
        assertTrue(vars.contains("variable \"image_tag\""), "variables.tf missing image_tag block: " + vars);
        assertTrue(vars.contains("description = \"Container image tag\""));
        assertTrue(vars.contains("default     = \"latest\""));
        assertTrue(vars.contains("type        = string"));
    }

    @Test
    void assembler_parsesTerraformVariableHints_arrayFormat_intoVariableBlocks() {
        String hints = "[{\"name\":\"region_override\",\"description\":\"override region\",\"default\":\"europe-west2\"}]";
        NetworkDto net = TerraformTestFixtures.buildRecord(NetworkDto.class, Map.of(
            "id", "net-2",
            "name", "Edge VPC",
            "environment_id", ENV_ID,
            "terraform_variable_hints", hints
        ));
        MetaModelEntitiesDto entities = TerraformTestFixtures.entitiesWith(Map.of(
            "networks", List.of(net)
        ));
        TerraformContext ctx = new TerraformContext(
            entities, TerraformTestFixtures.emptyRelationships(), env(), null, null, "GCP");

        TerraformAssembler.AssembledOutput out = assembler.assemble(List.of(), ctx);

        String vars = out.filesByName().get("variables.tf");
        assertTrue(vars.contains("variable \"region_override\""));
        assertTrue(vars.contains("default     = \"europe-west2\""));
    }

    @Test
    void assembler_aggregatesWarnings_intoWarningsJsonAndReadme() {
        TerraformContext ctx = ctx();
        EmittedResource r1 = new EmittedResource("main.tf", "x\n", List.of(),
            List.of("# TODO: missing CIDR. Source: Subnet 'app'."));
        EmittedResource r2 = new EmittedResource("main.tf", "y\n", List.of(),
            List.of("# TODO: ambiguous DU->CR mapping; expected 1, found 2."));

        TerraformAssembler.AssembledOutput out = assembler.assemble(List.of(r1, r2), ctx);

        assertEquals(2, out.warnings().size());
        assertTrue(out.warningsJson().contains("missing CIDR"));
        assertTrue(out.warningsJson().contains("ambiguous DU->CR mapping"));
        String readme = out.filesByName().get("README.md");
        assertTrue(readme.contains("Warnings / TODOs"));
        assertTrue(readme.contains("missing CIDR"));
    }

    @Test
    void assembler_readmeContainsExpectedSections() {
        TerraformContext ctx = ctx();
        TerraformAssembler.AssembledOutput out = assembler.assemble(List.of(), ctx);

        String readme = out.filesByName().get("README.md");
        assertTrue(readme.contains("# Infrastructure Terraform Export"));
        assertTrue(readme.contains("## Context"));
        assertTrue(readme.contains("## Files"));
        assertTrue(readme.contains("## Warnings / TODOs"));
        assertTrue(readme.contains("## Draft Notice"));
        assertTrue(readme.contains("Provider: `GCP`"));
    }

    // ---------- Service hard-fail tests ----------

    @Test
    void exportTerraform_throwsWhenEnvironmentIdMissing() {
        TerraformExportService svc = new TerraformExportService(
            modelService, projectService, architectureService, assembler, List.of(gcpExporter));

        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
            svc.exportTerraform(PROJECT_ID, ARCH_ID, null, null, null, "GCP")
        );
        assertTrue(ex.getMessage().toLowerCase().contains("environmentid"));
    }

    @Test
    void exportTerraform_throwsWhenProviderNotInOptions() {
        TerraformExportService svc = new TerraformExportService(
            modelService, projectService, architectureService, assembler, List.of(gcpExporter));

        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
            svc.exportTerraform(PROJECT_ID, ARCH_ID, ENV_ID, null, null, "ALIBABA")
        );
        assertTrue(ex.getMessage().contains("iacSourceProviderOptions"));
    }

    @Test
    void exportTerraform_throwsWhenProviderNotRegistered() {
        // 'AWS' is in iacSourceProviderOptions but not registered (V1 only GCP).
        TerraformExportService svc = new TerraformExportService(
            modelService, projectService, architectureService, assembler, List.of(gcpExporter));

        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
            svc.exportTerraform(PROJECT_ID, ARCH_ID, ENV_ID, null, null, "AWS")
        );
        assertTrue(ex.getMessage().toLowerCase().contains("not registered"));
    }

    // ---------- Service happy-path test ----------

    @Test
    void exportTerraform_happyPath_returnsZipWithFiveEntries_andDualWritesFiles() throws Exception {
        ProjectDto project = new ProjectDto(
            PROJECT_ID, "p1", tempDir.toString(), null, null, null, true,
            Instant.now(), Instant.now()
        );
        when(projectService.getProjectById(PROJECT_ID)).thenReturn(project);

        ArchitectureDto arch = new ArchitectureDto(
            ARCH_ID, PROJECT_ID, "Default", null, List.of(), false,
            Instant.now(), Instant.now()
        );
        when(architectureService.listForProject(PROJECT_ID)).thenReturn(List.of(arch));

        EnvironmentDto envDto = TerraformTestFixtures.buildRecord(EnvironmentDto.class, Map.of(
            "id", ENV_ID,
            "name", "Prod"
        ));
        NetworkDto net = TerraformTestFixtures.buildRecord(NetworkDto.class, Map.of(
            "id", "net-1",
            "name", "App VPC",
            "environment_id", ENV_ID,
            "network_type", "VPC"
        ));
        MetaModelEntitiesDto entities = TerraformTestFixtures.entitiesWith(Map.of(
            "environments", List.of(envDto),
            "networks", List.of(net)
        ));
        ArchitectureModelDto model = new ArchitectureModelDto(
            new MetaModelDto(entities, TerraformTestFixtures.emptyRelationships()),
            List.of()
        );
        when(modelService.loadModelByProjectIdAndArchitectureId(PROJECT_ID, ARCH_ID))
            .thenReturn(model);

        TerraformExportService svc = new TerraformExportService(
            modelService, projectService, architectureService, assembler, List.of(gcpExporter));

        TerraformExportService.TerraformExportResult result =
            svc.exportTerraform(PROJECT_ID, ARCH_ID, ENV_ID, null, null, "GCP");

        assertNotNull(result.filename());
        assertTrue(result.filename().endsWith("_terraform.zip"),
            "filename should end with _terraform.zip but was " + result.filename());
        assertTrue(result.filename().contains("default"),
            "filename should contain architecture slug but was " + result.filename());
        assertTrue(result.filename().contains("prod"),
            "filename should contain env slug but was " + result.filename());

        Set<String> entries = readZipEntries(result.zipBytes());
        assertEquals(Set.of("main.tf", "variables.tf", "outputs.tf", "README.md", "warnings.json"),
            entries);

        assertNotNull(result.filesystemDir());
        assertTrue(Files.exists(result.filesystemDir()));
        assertTrue(Files.exists(result.filesystemDir().resolve("main.tf")));
        assertTrue(Files.exists(result.filesystemDir().resolve("variables.tf")));
        assertTrue(Files.exists(result.filesystemDir().resolve("outputs.tf")));
        assertTrue(Files.exists(result.filesystemDir().resolve("README.md")));
        assertFalse(Files.exists(result.filesystemDir().resolve("warnings.json")));

        String mainTf = Files.readString(result.filesystemDir().resolve("main.tf"));
        assertTrue(mainTf.contains("google_compute_network"),
            "main.tf should include the emitted network resource: " + mainTf);
    }

    // ---------- Helpers ----------

    private static EnvironmentDto env() {
        return TerraformTestFixtures.buildRecord(EnvironmentDto.class, Map.of(
            "id", ENV_ID,
            "name", "Prod"
        ));
    }

    private static TerraformContext ctx() {
        return new TerraformContext(
            TerraformTestFixtures.emptyEntities(),
            TerraformTestFixtures.emptyRelationships(),
            env(), null, null, "GCP");
    }

    private static Set<String> readZipEntries(byte[] zipBytes) throws Exception {
        Set<String> out = new java.util.LinkedHashSet<>();
        try (ZipInputStream zis = new ZipInputStream(
                new java.io.ByteArrayInputStream(zipBytes))) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                out.add(entry.getName());
                zis.closeEntry();
            }
        }
        return out;
    }
}
