/**
 * CloseConversationFlow
 *
 * Spec: 2026-05-24 Target State Architect-Persona Conversation -- Commit 5, Surface 6
 *
 * Close CTA + retire-current-session affordance per Q4.
 *
 * Close gate per Q8: enabled only when A.1 (`service.language`) + B.1
 * (`api.protocol`) + C.1 (`db.engine`) are all answered.
 *
 * Per Q16 the `close` turn embeds the full `summaryMarkdown` inline -- the
 * summary is generated by this component from the captured-decision rows so
 * the close write is self-contained (no resolver re-query needed at read time).
 *
 * Per Q4 there is NO optimistic locking on the thread file. The "retire
 * current and start new" affordance is UI-level prevention only -- a second
 * user opening the draft with an active session sees the affordance and can
 * choose to retire the in-flight session before starting their own.
 */

import type { CapturedDecisionRow } from '../../../api/architectConversationApi';
import styles from './ArchitectConversation.module.css';

export const CLOSE_GATE_CODES: readonly string[] = [
  'service.language',
  'api.protocol',
  'db.engine',
];

export interface CloseConversationFlowProps {
  /** Active captured-decision rows -- used to evaluate the close gate per Q8. */
  decisions: CapturedDecisionRow[];
  /** Whether the conversation has an active open session (drives the visible close affordance). */
  isOpen: boolean;
  /** Whether the open session belongs to the current user. False -> show "retire current and start new". */
  isOwnedByCurrentUser: boolean;
  onClose: (summaryMarkdown: string) => Promise<void> | void;
  onRetireAndStartNew: () => Promise<void> | void;
}

/**
 * Compute the close gate per Q8. Returns the unmet code list (empty when the
 * gate is satisfied).
 */
export function evaluateCloseGate(decisions: CapturedDecisionRow[]): string[] {
  const answered = new Set(decisions.map((d) => d.decisionCode));
  return CLOSE_GATE_CODES.filter((code) => !answered.has(code));
}

/**
 * Build the inline `summaryMarkdown` payload per Q16. Groups rows by scope
 * (architecture-wide first, then per-element exceptions) so the final close
 * turn is a self-contained summary any later read can render directly.
 */
export function buildCloseSummaryMarkdown(decisions: CapturedDecisionRow[]): string {
  const architectureRows = decisions.filter((d) => d.scopeKind === 'architecture');
  const elementRows = decisions.filter((d) => d.scopeKind === 'element');

  const lines: string[] = [];
  lines.push('# Architect conversation summary');
  lines.push('');
  lines.push('## Architecture-wide decisions');
  if (architectureRows.length === 0) {
    lines.push('_No architecture-wide decisions captured._');
  } else {
    for (const row of architectureRows) {
      const valueLabel = row.answerValue === 'deferred' ? '_(deferred)_' : row.answerValue;
      lines.push(`- **${row.decisionCode}**: ${valueLabel}`);
    }
  }
  lines.push('');
  if (elementRows.length > 0) {
    lines.push('## Per-element exceptions');
    for (const row of elementRows) {
      lines.push(
        `- **${row.decisionCode}** (${row.scopeRefType}:${row.scopeRefId}): ${row.answerValue}`,
      );
    }
  }
  return lines.join('\n');
}

export function CloseConversationFlow({
  decisions,
  isOpen,
  isOwnedByCurrentUser,
  onClose,
  onRetireAndStartNew,
}: CloseConversationFlowProps) {
  const unmetCodes = evaluateCloseGate(decisions);
  const gateMet = unmetCodes.length === 0;

  // Retire-current path -- second user landing on a conversation already open by another user.
  if (isOpen && !isOwnedByCurrentUser) {
    return (
      <div
        className={styles.banner}
        data-testid="architect-conversation-retire-current-affordance"
      >
        <span>
          This conversation has an open session by another user. You can retire
          it and start a new one.
        </span>
        <button
          type="button"
          className={styles.secondaryButton}
          onClick={() => void onRetireAndStartNew()}
          data-testid="architect-conversation-retire-current-button"
        >
          Retire current and start new
        </button>
      </div>
    );
  }

  return (
    <div
      data-testid="architect-conversation-close-flow"
      style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}
    >
      {!gateMet && (
        <p
          style={{ fontSize: '0.85rem', color: '#57606a', margin: 0 }}
          data-testid="architect-conversation-close-gate-hint"
        >
          Answer all required questions before closing: {unmetCodes.join(', ')}.
        </p>
      )}
      <button
        type="button"
        className={styles.primaryButton}
        disabled={!gateMet || !isOpen}
        onClick={() => void onClose(buildCloseSummaryMarkdown(decisions))}
        title={
          !gateMet
            ? `Close gate not met: missing ${unmetCodes.join(', ')}`
            : 'Close conversation with full summary'
        }
        data-testid="architect-conversation-close-button"
      >
        Close conversation
      </button>
    </div>
  );
}
