package com.example.architecturemodel.service;

import com.example.architecturemodel.exception.ResourceNotFoundException;
import com.example.architecturemodel.model.dto.WorkItemDto;
import com.example.architecturemodel.model.dto.bookofwork.BookOfWorkUploadResultDto;
import com.example.architecturemodel.model.entity.WorkItemEntity;
import com.example.architecturemodel.model.parser.EpicNode;
import com.example.architecturemodel.model.parser.FeatureNode;
import com.example.architecturemodel.model.parser.InitiativeNode;
import com.example.architecturemodel.model.parser.StoryNode;
import com.example.architecturemodel.repository.ProjectRepository;
import com.example.architecturemodel.repository.entity.WorkItemRepository;
import com.example.architecturemodel.util.BookOfWorkParser;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Service for uploading and processing Book of Work markdown files.
 *
 * Spec 2026-01-10: Upload Book of Work from Markdown
 * Task Group 2.4: Create BookOfWorkUploadService
 *
 * Implements destructive sync strategy:
 * - Deletes all existing work items for the project
 * - Inserts new work items parsed from the markdown
 *
 * All imported items are set to status PLANNED.
 * Uses deterministic UUIDs generated by BookOfWorkParser.
 */
@Service
@ConditionalOnProperty(
    name = "app.features.include-database",
    havingValue = "true",
    matchIfMissing = true
)
@Slf4j
public class BookOfWorkUploadService {

    private final WorkItemRepository workItemRepository;
    private final BookOfWorkParser bookOfWorkParser;
    private final ProjectRepository projectRepository;

    private static final String STATUS_PLANNED = "PLANNED";
    private static final String TYPE_INITIATIVE = "INITIATIVE";
    private static final String TYPE_EPIC = "EPIC";
    private static final String TYPE_FEATURE = "FEATURE";
    private static final String TYPE_STORY = "STORY";

    public BookOfWorkUploadService(
            WorkItemRepository workItemRepository,
            BookOfWorkParser bookOfWorkParser,
            ProjectRepository projectRepository) {
        this.workItemRepository = workItemRepository;
        this.bookOfWorkParser = bookOfWorkParser;
        this.projectRepository = projectRepository;
    }

    /**
     * Upload and process a Book of Work markdown file.
     *
     * This method:
     * 1. Validates the project exists
     * 2. Parses the markdown content into a 4-level hierarchy
     * 3. Deletes all existing work items for the project (destructive sync)
     * 4. Creates new work items with PLANNED status
     * 5. Returns the result with all created items and counts
     *
     * @param projectId the project ID (project name) to import into
     * @param markdownContent the raw markdown content of the Book of Work
     * @return result DTO with created work items and import summary
     * @throws ResourceNotFoundException if project is not found
     * @throws IllegalArgumentException if markdown has no valid headings
     */
    @Transactional
    public BookOfWorkUploadResultDto uploadBookOfWork(UUID projectId, String markdownContent) {
        log.info("Starting Book of Work upload for project: {}", projectId);

        // Validate project exists by UUID
        if (!projectRepository.existsById(projectId)) {
            throw new ResourceNotFoundException("Project not found: " + projectId);
        }

        // Parse the markdown - this will throw if no valid headings
        // Note: parser uses projectId.toString() for deterministic ID generation
        List<InitiativeNode> initiatives = bookOfWorkParser.parse(markdownContent, projectId.toString());

        // Destructive sync: delete all existing work items for this project
        log.debug("Deleting existing work items for project: {}", projectId);
        workItemRepository.deleteByProjectId(projectId);

        // Create new work items
        List<WorkItemDto> createdItems = new ArrayList<>();
        int initiativeCount = 0;
        int epicCount = 0;
        int featureCount = 0;
        int storyCount = 0;

        Instant now = Instant.now();

        for (InitiativeNode initNode : initiatives) {
            // Create initiative
            WorkItemEntity initiative = createWorkItem(
                    projectId, initNode.getComputedId(), TYPE_INITIATIVE, null,
                    initNode.getTitle(), null, initNode.getSortOrder(), now);
            WorkItemEntity savedInit = workItemRepository.save(initiative);
            createdItems.add(toDto(savedInit));
            initiativeCount++;

            // Create epics
            for (EpicNode epicNode : initNode.getEpics()) {
                WorkItemEntity epic = createWorkItem(
                        projectId, epicNode.getComputedId(), TYPE_EPIC, savedInit.getId(),
                        epicNode.getTitle(), epicNode.getDescription(), epicNode.getSortOrder(), now);
                WorkItemEntity savedEpic = workItemRepository.save(epic);
                createdItems.add(toDto(savedEpic));
                epicCount++;

                // Create features
                for (FeatureNode featureNode : epicNode.getFeatures()) {
                    WorkItemEntity feature = createWorkItem(
                            projectId, featureNode.getComputedId(), TYPE_FEATURE, savedEpic.getId(),
                            featureNode.getTitle(), featureNode.getDescription(), featureNode.getSortOrder(), now);
                    WorkItemEntity savedFeature = workItemRepository.save(feature);
                    createdItems.add(toDto(savedFeature));
                    featureCount++;

                    // Create stories
                    for (StoryNode storyNode : featureNode.getStories()) {
                        WorkItemEntity story = createWorkItem(
                                projectId, storyNode.getComputedId(), TYPE_STORY, savedFeature.getId(),
                                storyNode.getTitle(), storyNode.getDescription(), storyNode.getSortOrder(), now);
                        WorkItemEntity savedStory = workItemRepository.save(story);
                        createdItems.add(toDto(savedStory));
                        storyCount++;
                    }
                }
            }
        }

        log.info("Book of Work upload completed for project: {}. Created: {} initiatives, {} epics, {} features, {} stories",
                projectId, initiativeCount, epicCount, featureCount, storyCount);

        return BookOfWorkUploadResultDto.of(
                projectId,
                createdItems,
                initiativeCount,
                epicCount,
                featureCount,
                storyCount
        );
    }

    /**
     * Create a WorkItemEntity with the given parameters.
     */
    private WorkItemEntity createWorkItem(
            UUID projectId,
            UUID id,
            String type,
            UUID parentId,
            String title,
            String description,
            int sortOrder,
            Instant timestamp) {
        return WorkItemEntity.builder()
                .id(id)
                .projectId(projectId)
                .type(type)
                .parentId(parentId)
                .title(title)
                .description(description)
                .status(STATUS_PLANNED)
                .sortOrder(sortOrder)
                .createdAt(timestamp)
                .updatedAt(timestamp)
                .build();
    }

    /**
     * Convert a WorkItemEntity to WorkItemDto.
     */
    private WorkItemDto toDto(WorkItemEntity entity) {
        return new WorkItemDto(
                entity.getId(),
                entity.getProjectId(),
                entity.getType(),
                entity.getParentId(),
                entity.getTitle(),
                entity.getDescription(),
                entity.getStatus(),
                entity.getSortOrder(),
                entity.getPriority(),
                entity.getTargetWindow(),
                entity.getTagsJson(),
                entity.getExternalSystem(),
                entity.getExternalKey(),
                entity.getExternalUrl(),
                entity.getCreatedAt(),
                entity.getUpdatedAt()
        );
    }
}
