/**
 * Compensation statement guard (Capture-State Discipline Spec 1).
 *
 * Defence-in-depth: every statement the engine applies is SELF-GENERATED by
 * `inverseDiff.ts`, but the write path still refuses anything outside the
 * exact grammar the generator emits — plain single-statement DML, the Sybase
 * IDENTITY_INSERT toggles, and the two identity-reseed forms. DDL, TRUNCATE,
 * statement chaining, and comments are rejected. The Sybase sidecar re-guards
 * at the JVM layer (`MutationSqlGuard`) with the same rules — no caller is
 * trusted, matching the read path's two-layer posture.
 *
 * Chaining/comment fragments are checked OUTSIDE single-quoted literal spans:
 * restored business data may legitimately contain `;` or `--` inside a
 * quote-doubled string literal, and refusing it would turn a valid undo into
 * a false residue halt.
 */

const ALLOWED_PREFIXES = [
  /^DELETE\s+FROM\s+/i,
  /^UPDATE\s+/i,
  /^INSERT\s+INTO\s+/i,
  /^SET\s+IDENTITY_INSERT\s+\S+\s+(ON|OFF)$/i,
  /^EXEC\s+sp_chgattribute\s+'[^']+',\s*'identity_burn_max',\s*0,\s*'\d+'$/i,
  // SQL Server identity reseed (second-pair programme, Spec 4).
  /^DBCC\s+CHECKIDENT\s*\(\s*'[^']+'\s*,\s*RESEED\s*,\s*\d+\s*\)(\s+WITH\s+NO_INFOMSGS)?$/i,
  /^SELECT\s+setval\(pg_get_serial_sequence\('[^']+',\s*'[^']+'\),\s*\d+,\s*(true|false)\)$/i,
];

const FORBIDDEN_FRAGMENTS = [';', '--', '/*', '*/'];

/**
 * Blank out single-quoted literal spans (quote-doubling aware) so fragment
 * checks only see the SQL skeleton. An UNTERMINATED literal is itself a
 * refusal (the generator never emits one).
 */
export function stripQuotedLiterals(statement: string): { skeleton: string; terminated: boolean } {
  let skeleton = '';
  let i = 0;
  while (i < statement.length) {
    const ch = statement[i];
    if (ch !== "'") {
      skeleton += ch;
      i++;
      continue;
    }
    // Inside a literal: scan to the closing quote, treating '' as an escape.
    let j = i + 1;
    for (;;) {
      const at = statement.indexOf("'", j);
      if (at === -1) return { skeleton, terminated: false };
      if (statement[at + 1] === "'") {
        j = at + 2;
        continue;
      }
      j = at + 1;
      break;
    }
    skeleton += "''";
    i = j;
  }
  return { skeleton, terminated: true };
}

export interface GuardVerdict {
  allowed: boolean;
  reason: string | null;
}

export function checkCompensationStatement(statement: string): GuardVerdict {
  const trimmed = statement.trim();
  if (trimmed.length === 0) return { allowed: false, reason: 'empty statement' };
  const { skeleton, terminated } = stripQuotedLiterals(trimmed);
  if (!terminated) return { allowed: false, reason: 'unterminated string literal' };
  for (const fragment of FORBIDDEN_FRAGMENTS) {
    if (skeleton.includes(fragment)) {
      return { allowed: false, reason: `forbidden fragment '${fragment}'` };
    }
  }
  if (!ALLOWED_PREFIXES.some((re) => re.test(trimmed))) {
    return { allowed: false, reason: 'statement does not match the compensation grammar' };
  }
  return { allowed: true, reason: null };
}

/** Throws on the first disallowed statement (fail-closed batch admission). */
export function assertCompensationBatch(statements: string[]): void {
  for (const statement of statements) {
    const verdict = checkCompensationStatement(statement);
    if (!verdict.allowed) {
      throw new Error(
        `compensation guard refused statement (${verdict.reason}): ${statement.slice(0, 200)}`,
      );
    }
  }
}

// ---------------------------------------------------------------------------
// RESTORE grammar (Capture-State Discipline Spec 2): the S0 restore path is
// the compensation grammar PLUS `TRUNCATE TABLE <t>` — truncate-then-bulk-in
// mirrors the target loader. DROP/ALTER/SELECT stay refused. Restore batches
// are admitted ONLY through `executeRestoreBatch` (never the compensation
// bracket), and the sidecar re-guards with the same mode split.
// ---------------------------------------------------------------------------

const RESTORE_ONLY_PREFIXES = [/^TRUNCATE\s+TABLE\s+\S+$/i];

export function checkRestoreStatement(statement: string): GuardVerdict {
  const trimmed = statement.trim();
  if (RESTORE_ONLY_PREFIXES.some((re) => re.test(trimmed))) {
    return { allowed: true, reason: null };
  }
  return checkCompensationStatement(statement);
}

export function assertRestoreBatch(statements: string[]): void {
  for (const statement of statements) {
    const verdict = checkRestoreStatement(statement);
    if (!verdict.allowed) {
      throw new Error(
        `restore guard refused statement (${verdict.reason}): ${statement.slice(0, 200)}`,
      );
    }
  }
}
