--liquibase formatted sql logicalFilePath:liquibase/changesets/010-tables/Ledger.Postings.sql
--changeset db-migration-pack:table-Ledger.Postings context:structural splitStatements:false
CREATE TABLE "Ledger"."Postings" (
    "PostingID" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 5) NOT NULL,
    "PostedBy" citext NOT NULL,
    "IsVoided" boolean NOT NULL,
    "PayloadDocument" xml,
    "LooseValue" jsonb,
    "OrgNode" ltree,
    "SiteShape" geometry,
    "ScannedDocument" bytea,
    "RowGuid" uuid NOT NULL DEFAULT gen_random_uuid(),
    "PostedOn" timestamp(6) NOT NULL,
    "PostedOffset" timestamptz(6),
    "Amount" numeric(19,4) NOT NULL,
    "ShortCode" citext,
    "DisplayName" text,
    "RowVersion" bytea,
    "Tier" smallint,
    CONSTRAINT "PK_Ledger_Postings" PRIMARY KEY ("PostingID"),
    CONSTRAINT "CK_Postings_Amount" CHECK (Amount >= 0),
    CONSTRAINT "Postings_ShortCode_len_chk" CHECK (length("ShortCode") <= 8)
);
ALTER TABLE "Ledger"."Postings" ADD CONSTRAINT "CK_Postings_PostedBy" CHECK (length(PostedBy) > 0) NOT VALID;
-- CHECK Ledger.Postings.CK_Postings_PostedBy emitted NOT VALID: the constraint was NOT TRUSTED at source (WITH NOCHECK), so the EXISTING rows were never validated against it. New and updated rows ARE checked; run `ALTER TABLE "Ledger"."Postings" VALIDATE CONSTRAINT "CK_Postings_PostedBy";` once the legacy rows have been cleaned to promote it to a fully enforced constraint.
-- FILESTREAM column Ledger.Postings.ScannedDocument: the source stores the bytes on the filesystem. The target column is an ordinary bytea and the extract must read the content itself (decision 'filestream--Ledger.Postings.ScannedDocument').
-- ROWGUIDCOL Ledger.Postings.RowGuid: a SQL Server storage attribute used by merge replication only. It has no target equivalent and no effect on values; the uuid column itself migrates unchanged.
-- SPARSE Ledger.Postings.RowGuid: a SQL Server NULL-storage optimisation, not a semantic. The target column is a plain column — values and nullability are identical.
-- CHECK Ledger.Postings.CK_Postings_PostedBy: expression rewritten deterministically from Sybase ('len(PostedBy) > 0' -> 'length(PostedBy) > 0').
