--liquibase formatted sql logicalFilePath:liquibase/changesets/010-tables/Ledger.AccountHistory.sql
--changeset db-migration-pack:table-Ledger.AccountHistory context:structural splitStatements:false
CREATE TABLE "Ledger"."AccountHistory" (
    "AccountID" integer NOT NULL,
    "Balance" numeric(19,4) NOT NULL,
    "ValidFrom" timestamp(6) NOT NULL,
    "ValidTo" timestamp(6) NOT NULL,
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT "pk_AccountHistory_surrogate" PRIMARY KEY ("id")
);
-- TEMPORAL HISTORY table: this is the history half of a system-versioned pair. Its rows are LOADED like any other table's, and the versioning emulation in liquibase/changesets/015-emulations.sql writes new versions into it — it is never re-derived.
