--liquibase formatted sql logicalFilePath:liquibase/changesets/010-tables/Ledger.Account.sql
--changeset db-migration-pack:table-Ledger.Account context:structural splitStatements:false
CREATE TABLE "Ledger"."Account" (
    "AccountID" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "Balance" numeric(19,4) NOT NULL,
    "ValidFrom" timestamp(6) NOT NULL,
    "ValidTo" timestamp(6) NOT NULL,
    CONSTRAINT "PK_Ledger_Account" PRIMARY KEY ("AccountID")
);
