--liquibase formatted sql logicalFilePath:liquibase/changesets/010-tables/Ops.SensorArchive.sql
--changeset db-migration-pack:table-Ops.SensorArchive context:structural splitStatements:false
CREATE TABLE "Ops"."SensorArchive" (
    "SensorArchiveID" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "ReadingNote" varchar(400),
    "ReadingSummary" varchar(80) GENERATED ALWAYS AS (left(ReadingNote, 80)) VIRTUAL,
    "UpdatedAt" timestamp(3) NOT NULL,
    CONSTRAINT "PK_Ops_SensorArchive" PRIMARY KEY ("SensorArchiveID")
);
-- MEMORY_OPTIMIZED at source: emitted as an ordinary heap table (decision 'memory_optimized_table--Ops.SensorArchive'). Values and constraints are identical; the latency profile and the lock-free concurrency semantics are not.
