/**
 * OAS Export API client.
 *
 * Direct build 2026-06-11 (oracle weaknesses #5): deterministic OpenAPI 3.0
 * contracts generated by the gateway from the architecture model. Read-only —
 * a download is a regeneration, so nothing here mutates the model.
 *
 * Gateway routes (mounted at /api/v1, see gateway/src/routes/oasExport.ts):
 *   GET  /projects/:projectId/architectures/:architectureId/oas-export/interfaces
 *   POST /projects/:projectId/architectures/:architectureId/oas-export/interfaces/:interfaceId/generate
 *   GET  /projects/:projectId/architectures/:architectureId/oas-export/download
 *
 * Conventions mirror `dbMigrationPackApi.ts` (base builder, getJson/sendJson,
 * `extractGatewayErrorMessage` so an error envelope never renders as
 * "[object Object]").
 */

const GATEWAY_BASE = import.meta.env.VITE_GATEWAY_BASE_URL ?? '';

// ============================================================================
// Types (mirror gateway/src/services/oasExport/types.ts)
// ============================================================================

export interface OasExportInterfaceSummary {
  id: string;
  name: string;
}

export interface OasGapItem {
  code: string;
  severity: 'BLOCKING' | 'RECOMMENDED' | 'INFO';
  message: string;
  location?: {
    interfaceId?: string;
    endpointId?: string;
    method?: string;
    path?: string;
  };
  suggestedQuestions?: string[];
  data?: Record<string, unknown>;
}

export interface OasGapReport {
  interfaceId: string;
  generatedAt: string;
  gaps: OasGapItem[];
  defaults: Array<{ code: string; value: unknown; rationale: string }>;
  typeMappings: Array<{ logicalType: string; oasSchema: Record<string, unknown> }>;
  operationIds: Array<{
    endpointId: string;
    style: 'camelCase' | 'snake_case';
    operationId: string;
  }>;
}

export interface OasUnmappedEndpoint {
  endpointId: string;
  name: string;
  reason: string;
}

export interface OasAssemblySummary {
  endpointCount: number;
  mappedEndpointCount: number;
  unmappedEndpoints: OasUnmappedEndpoint[];
  schemaCount: number;
  gapCounts: { blocking: number; recommended: number; info: number };
}

export interface OasExportResult {
  interfaceId: string;
  interfaceName: string;
  suggestedFilename: string;
  document: Record<string, unknown>;
  gapReport: OasGapReport;
  summary: OasAssemblySummary;
}

// ============================================================================
// Error handling (extractGatewayErrorMessage pattern)
// ============================================================================

function extractGatewayErrorMessage(errorBody: unknown): string {
  if (!errorBody || typeof errorBody !== 'object') return '';
  const top = errorBody as { message?: unknown; error?: unknown };
  if (typeof top.message === 'string' && top.message) return top.message;
  if (typeof top.error === 'string' && top.error) return top.error;
  if (top.error && typeof top.error === 'object') {
    const nested = top.error as { message?: unknown; details?: unknown };
    const message = typeof nested.message === 'string' ? nested.message : '';
    const details = typeof nested.details === 'string' ? nested.details : '';
    if (message && details) return `${message}: ${details}`;
    return message || details;
  }
  return '';
}

async function throwGatewayError(res: Response, fallback: string): Promise<never> {
  let serverMessage = '';
  try {
    serverMessage = extractGatewayErrorMessage(await res.json());
  } catch {
    // Ignore JSON parse failure — fall through to the generic message.
  }
  throw new Error(serverMessage || `${fallback}: ${res.status} ${res.statusText}`);
}

function oasExportBase(projectId: string, architectureId: string): string {
  return (
    `${GATEWAY_BASE}/api/v1/projects/${encodeURIComponent(projectId)}` +
    `/architectures/${encodeURIComponent(architectureId)}/oas-export`
  );
}

// ============================================================================
// API functions
// ============================================================================

/** List the architecture's interfaces eligible for contract export. */
export async function listOasExportInterfaces(
  projectId: string,
  architectureId: string,
): Promise<OasExportInterfaceSummary[]> {
  const res = await fetch(`${oasExportBase(projectId, architectureId)}/interfaces`, {
    method: 'GET',
    headers: { Accept: 'application/json' },
  });
  if (!res.ok) await throwGatewayError(res, 'Failed to list interfaces');
  const body = (await res.json()) as { interfaces: OasExportInterfaceSummary[] };
  return body.interfaces ?? [];
}

/** Generate the deterministic OpenAPI contract for one interface. */
export async function generateOasForInterface(
  projectId: string,
  architectureId: string,
  interfaceId: string,
): Promise<OasExportResult> {
  const res = await fetch(
    `${oasExportBase(projectId, architectureId)}/interfaces/${encodeURIComponent(
      interfaceId,
    )}/generate`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    },
  );
  if (!res.ok) await throwGatewayError(res, 'Failed to generate the OpenAPI contract');
  return (await res.json()) as OasExportResult;
}

/**
 * URL for the all-interfaces zip (manifest + one .openapi.json and .gaps.json
 * per interface). Used as a direct anchor/window.open target.
 */
export function getOasExportDownloadUrl(
  projectId: string,
  architectureId: string,
): string {
  return `${oasExportBase(projectId, architectureId)}/download`;
}
