# Generated by Infrastructure Terraform Export
# File: main.tf
# Provider: GCP
# Environment: prod
# Generated: <NORMALISED>
# DRAFT -- review TODO comments and warnings.json before apply.
# Infrastructure concept: Environment
# Architecture entity: prod
# Environment: prod
# Source model id: env-prod
locals {
  common_labels = {
    environment = var.environment
  }
}

# Infrastructure concept: Cloud Account
# Architecture entity: acme-prod-gcp
# Environment: prod
# Source model id: cloud-1
provider "google" {
  project = var.project_id
  region  = var.region
}

# Infrastructure concept: Network
# Architecture entity: prod-vpc
# Environment: prod
# Source model id: net-1
resource "google_compute_network" "prod_prod_vpc" {
  name                    = "prod-vpc"
  auto_create_subnetworks = false
}

# Infrastructure concept: Subnet
# Architecture entity: app-subnet
# Environment: prod
# Source model id: sub-1
resource "google_compute_subnetwork" "prod_app_subnet" {
  name          = "app-subnet"
  ip_cidr_range = "10.0.1.0/24"
  region        = var.region
  network       = google_compute_network.prod_prod_vpc.id
  # TODO: complete required fields above before apply.
}

# Infrastructure concept: Compute Cluster
# Architecture entity: orders-gke
# Environment: prod
# Source model id: cl-1
resource "google_container_cluster" "prod_orders_gke" {
  name     = "orders-gke"
  location = var.region
  remove_default_node_pool = true
  initial_node_count       = 1
}

# TODO: configure google_container_node_pool for cluster 'orders-gke'. Source: Compute Cluster 'orders-gke' (id: cl-1).
resource "google_container_node_pool" "prod_orders_gke_default_pool" {
  name       = "default-pool"
  cluster    = google_container_cluster.prod_orders_gke.name
  location   = var.region
  node_count = 1
  # TODO: complete node_config block before apply.
}

# Infrastructure concept: Compute Resource
# Architecture entity: orders-cr
# Environment: prod
# Source model id: cr-1
resource "google_cloud_run_v2_service" "prod_orders_cr" {
  name     = "orders-cr"
  location = var.region
  template {
    containers {
      image = "REPLACE_ME"
    }
  }
}

# Infrastructure concept: Load Balancer
# Architecture entity: orders-lb
# Environment: prod
# Source model id: lb-1
resource "google_compute_backend_service" "prod_orders_lb_backend" {
  name                  = "orders-lb-backend"
  load_balancing_scheme = "EXTERNAL"
  protocol              = "HTTP"
  # TODO: bind backend to a managed instance group or NEG.
}

resource "google_compute_url_map" "prod_orders_lb_urlmap" {
  name            = "orders-lb-urlmap"
  default_service = google_compute_backend_service.prod_orders_lb_backend.id
}

resource "google_compute_target_http_proxy" "prod_orders_lb_proxy" {
  name    = "orders-lb-proxy"
  url_map = google_compute_url_map.prod_orders_lb_urlmap.id
}

resource "google_compute_global_forwarding_rule" "prod_orders_lb_fwd" {
  name       = "orders-lb-fwd"
  target     = google_compute_target_http_proxy.prod_orders_lb_proxy.id
  port_range = "80"
}

# Infrastructure concept: Listener
# Architecture entity: orders-listener
# Environment: prod
# Source model id: li-1
# Listener contribution to Load Balancer 'orders-lb' (id: lb-1):
#   protocol = HTTPS
#   port = 443

# Infrastructure concept: Data Store Instance
# Architecture entity: orders-db
# Environment: prod
# Source model id: db-1
resource "google_sql_database_instance" "prod_orders_db" {
  name             = "orders-db"
  database_version = "POSTGRES_15"
  region           = var.region
  settings {
    tier = "db-f1-micro"
  }
}

# Infrastructure concept: Infrastructure Resource
# Architecture entity: orders-bucket
# Environment: prod
# Source model id: ir-1
resource "google_storage_bucket" "prod_orders_bucket" {
  name     = "orders-bucket"
  location = var.region
  uniform_bucket_level_access = true
}
