# Generated by Infrastructure Terraform Export
# File: variables.tf
# Provider: GCP
# Environment: prod
# Generated: <NORMALISED>
# DRAFT -- review TODO comments and warnings.json before apply.
# Infrastructure concept: Environment
# Architecture entity: prod
# Environment: prod
# Source model id: env-prod
variable "environment" {
  description = "Environment name (e.g. dev, prod)"
  type        = string
  default     = "prod"
}

# Infrastructure concept: Cloud Account
# Architecture entity: acme-prod-gcp
# Environment: prod
# Source model id: cloud-1
variable "project_id" {
  description = "GCP project id"
  type        = string
  default     = "acme-prod-1234"
}

# Infrastructure concept: Location
# Architecture entity: europe-west1
# Environment: prod
# Source model id: loc-1
variable "region" {
  description = "GCP region"
  type        = string
  default     = "europe-west1"
}
