# Generated by Infrastructure Terraform Export
# File: outputs.tf
# Provider: GCP
# Environment: prod
# Generated: <NORMALISED>
# DRAFT -- review TODO comments and warnings.json before apply.

# (no resources of this kind generated)
