package com.example.architecturemodel.integration;

import com.example.architecturemodel.exception.ArchivedArchitectureSourceException;
import com.example.architecturemodel.exception.SameArchitectureCopyException;
import com.example.architecturemodel.model.dto.SelectiveCopyCommitRequest;
import com.example.architecturemodel.model.dto.SelectiveCopyCommitRequest.ResolutionItem;
import com.example.architecturemodel.model.dto.SelectiveCopyCommitResponse;
import com.example.architecturemodel.model.dto.SelectiveCopyPreflightRequest;
import com.example.architecturemodel.model.dto.SelectiveCopyPreflightResponse;
import com.example.architecturemodel.model.dto.SelectiveCopyPreflightResponse.AutoIncludedItem;
import com.example.architecturemodel.model.dto.SelectiveCopyPreflightResponse.ConflictItem;
import com.example.architecturemodel.model.entity.ArchitectureEntity;
import com.example.architecturemodel.model.entity.DiscoveryRunEntity;
import com.example.architecturemodel.model.entity.ModelFileEntity;
import com.example.architecturemodel.repository.ArchitectureRepository;
import com.example.architecturemodel.repository.ModelFileRepository;
import com.example.architecturemodel.repository.entity.DiscoveryRunRepository;
import com.example.architecturemodel.service.ArchitectureSelectiveCopyService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import javax.sql.DataSource;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * End-to-end integration test for {@link ArchitectureSelectiveCopyService},
 * asserting the nine critical safety properties at the database level.
 *
 * <h2>Test scope (Task Groups 4 + 11 of spec #7)</h2>
 *
 * <p>This is the authoritative test for selective-copy graph correctness;
 * service-level tests in {@code ArchitectureSelectiveCopyServiceTest} cover
 * validation paths with mocked JDBC. Each test seeds two architectures
 * (source + target) in the same project, runs preflight and/or commit, and
 * inspects the resulting database state.</p>
 *
 * <ol>
 *   <li><b>Preflight: same_uuid conflict detected</b> — safety property (b).</li>
 *   <li><b>Preflight: smart cascading auto-include for missing reference</b>
 *       — safety property (d) - missing branch.</li>
 *   <li><b>Preflight: smart cascading reuse when reference exists in target</b>
 *       — safety property (d) - reuse branch.</li>
 *   <li><b>Commit: skip action</b> — safety property (c) - skip.</li>
 *   <li><b>Commit: overwrite action</b> — safety property (c) - overwrite.</li>
 *   <li><b>Commit: duplicate action with FK rewiring</b> — safety property (c)
 *       - duplicate (and intra-copy-set FK rewiring).</li>
 *   <li><b>Refuse archived source</b> — safety property (e). Also asserts
 *       same-architecture refusal — safety property (f).</li>
 *   <li><b>Atomic rollback on mid-commit failure</b> — safety property (a).
 *       Added in Task Group 11 gap fill: wires a {@link ThrowingJdbcTemplate}
 *       that throws on the first {@code update(String, Object[])} write call
 *       once armed; asserts the commit's {@code @Transactional} boundary
 *       rolls back ALL writes (no new rows in target, no UPDATE persisted
 *       from earlier overwrite actions either).</li>
 *   <li><b>Discovery + threads not copied</b> — safety property (g). Added in
 *       Task Group 11 gap fill: seeds the source with a {@code discovery_run}
 *       row, runs a normal selective copy, asserts the target architecture
 *       has zero {@code discovery_run} rows after commit and the source's
 *       run is byte-for-byte untouched (Discovery is locked one-run/architecture
 *       per spec).</li>
 * </ol>
 *
 * <h2>Schema setup caveats</h2>
 *
 * <p>The H2 test schema is generated by JPA's {@code create-drop} from the
 * entity model. Two adjustments are required for these tests to run:</p>
 *
 * <ol>
 *   <li><b>{@code architecture_id} column.</b> Only entities that declare an
 *       {@code architectureId} field (currently {@code model_files},
 *       {@code architecture_tag}, {@code discovery_run}, {@code temporary_diagrams})
 *       get an {@code architecture_id} column on their table. This integration
 *       test therefore manually adds {@code architecture_id} columns to the
 *       additional tables it exercises ({@code applications}, {@code services})
 *       in {@link #setUp()}. In production the same columns are added by
 *       Liquibase changeset 089. This mirrors the pattern in
 *       {@code ArchitectureCloneIntegrationTest}.</li>
 *   <li><b>Composite primary key {@code (id, architecture_id)}.</b> The
 *       JPA-generated H2 schema treats the {@code id} column as a global
 *       PRIMARY KEY, mirroring the production Liquibase schema. The
 *       same-UUID-conflict scenario this test asserts requires that two
 *       different architectures legitimately hold a row with the same
 *       {@code id} value (e.g. a row cloned and then re-imported via selective
 *       copy). To make that scenario representable in the test fixture, the
 *       global single-column PK is dropped and replaced with a composite
 *       {@code (id, architecture_id)} primary key for the two tables this
 *       test exercises. Production behaviour is unchanged — this is purely a
 *       test-fixture relaxation that lets the integration test express the
 *       conflict scenario the service is built to resolve. The production
 *       schema retains the global PK; selective copy's
 *       {@link ArchitectureSelectiveCopyService} relies on the (id,
 *       architecture_id) lookups inside its own logic so behaviour is
 *       unaffected by the relaxation.
 *
 *       <p><b>Documentation note (Group 11):</b> because the production schema
 *       enforces a global single-column PK on {@code id}, the {@code same_uuid}
 *       conflict path is essentially unreachable in normal production flow —
 *       two rows with the same {@code id} would be rejected by the PK
 *       constraint long before selective copy got to run. The {@code same_uuid}
 *       detection is defensive code that future-proofs the service against
 *       schema changes (e.g. if the global PK is ever relaxed for multi-arch
 *       support) and against UUID collisions inserted via raw SQL or via a
 *       data import path that bypasses the JPA layer. This is a deliberate
 *       defence-in-depth choice; the gap is flagged here for transparency
 *       rather than fixed by this spec — schema changes are tracked
 *       separately.</p></li>
 * </ol>
 *
 * <h2>Element IDs are plain UUIDs (no prefix)</h2>
 *
 * <p>Unlike the clone-service test, the selective-copy service exposes a
 * {@code List<UUID> elementIds} parameter that is converted to strings via
 * {@code id.toString()} and matched against the {@code id} column in the
 * source tables. The existing application + service rows therefore must use
 * plain UUID strings for their primary keys (no {@code "app-"} or
 * {@code "svc-"} prefix that the clone test uses). Foreign-key columns like
 * {@code services.application_id} likewise hold plain UUID strings so the
 * cascading walk's {@code looksLikeUuid()} predicate matches.</p>
 *
 * <h2>Transaction boundaries</h2>
 *
 * <p>Tests are NOT annotated {@code @Transactional} so the commit's own
 * {@code @Transactional} boundary is real. Each test cleans up its own seed
 * data in {@link #tearDown()} via direct JDBC deletes.</p>
 *
 * Spec: Multi-Architecture Selective Cross-Architecture Copy (Spec #7)
 * Task Group 4: Backend integration test for selective-copy correctness.
 * Task Group 11: gap-fill tests for safety properties (a) atomic rollback
 *                and (g) excluded-scope (Discovery + threads) verification.
 */
@SpringBootTest
@TestPropertySource(properties = {
    "app.data-entity-points.startup-ensure=false"
})
class ArchitectureSelectiveCopyIntegrationTest {

    /**
     * Test wrapper around the real {@link JdbcTemplate} that lets a single
     * test flip into "throw on update" mode after seeding, simulating a
     * mid-commit JDBC failure to drive the atomic rollback test (safety
     * property (a)). All other JdbcTemplate calls delegate to the real bean
     * so seed + tear-down + the rest of the test class run untouched.
     *
     * <p>Selective copy's commit path uses {@code update(String, Object...)}
     * for both INSERTs (via {@code insertRow}) and UPDATEs (via
     * {@code updateRow}). Overriding that single method gives precise
     * coverage of every commit-write call site without disturbing reads
     * (queryForList) or batch operations.</p>
     */
    public static class ThrowingJdbcTemplate extends JdbcTemplate {
        public final AtomicReference<RuntimeException> throwOn = new AtomicReference<>();
        public final java.util.concurrent.atomic.AtomicInteger updateInvocations =
            new java.util.concurrent.atomic.AtomicInteger(0);

        public ThrowingJdbcTemplate(DataSource dataSource) {
            super(dataSource);
        }

        @Override
        public int update(String sql, Object... args) throws DataAccessException {
            updateInvocations.incrementAndGet();
            RuntimeException pending = throwOn.get();
            if (pending != null) {
                throw pending;
            }
            return super.update(sql, args);
        }
    }

    @TestConfiguration
    static class SelectiveCopyTestConfig {
        @Bean
        @Primary
        public JdbcTemplate testJdbcTemplate(DataSource dataSource) {
            return new ThrowingJdbcTemplate(dataSource);
        }
    }

    @Autowired
    private ArchitectureSelectiveCopyService selectiveCopyService;

    @Autowired
    private ArchitectureRepository architectureRepository;

    @Autowired
    private ModelFileRepository modelFileRepository;

    @Autowired
    private DiscoveryRunRepository discoveryRunRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private UUID projectId;

    @BeforeEach
    void setUp() {
        projectId = UUID.randomUUID();

        // Reset the throwing wrapper each test (avoid cross-test bleed since
        // the Spring context is reused across tests within a class).
        if (jdbcTemplate instanceof ThrowingJdbcTemplate t) {
            t.throwOn.set(null);
            t.updateInvocations.set(0);
        }

        // (1) Add architecture_id columns to JPA-managed tables that need them
        // for the selective-copy walk. JPA's create-drop only adds the column
        // for entities that declare the field. IF NOT EXISTS makes this
        // idempotent across test methods (Spring context is cached).
        ensureArchitectureIdColumn("applications");
        ensureArchitectureIdColumn("services");

        // (2) Replace the global single-column PK on (id) with a composite
        // (id, architecture_id) PK so the same-UUID-conflict scenario is
        // representable. See class-level Javadoc for rationale.
        relaxToCompositePrimaryKey("applications");
        relaxToCompositePrimaryKey("services");
    }

    @AfterEach
    void tearDown() {
        // Clear throwOn first so the cleanup deletes don't trip the wrapper.
        if (jdbcTemplate instanceof ThrowingJdbcTemplate t) {
            t.throwOn.set(null);
        }

        // Clean up everything (and anything copied from it). We can't use
        // @Transactional on the test itself because that would mask the
        // commit's own transaction boundary.
        jdbcTemplate.update("DELETE FROM services WHERE 1=1");
        jdbcTemplate.update("DELETE FROM applications WHERE 1=1");
        jdbcTemplate.update("DELETE FROM model_files WHERE 1=1");
        try {
            jdbcTemplate.update("DELETE FROM discovery_run WHERE 1=1");
        } catch (DataAccessException ignored) {
            // Table may not exist in some test profiles.
        }
        jdbcTemplate.update("DELETE FROM architecture_tag WHERE 1=1");
        jdbcTemplate.update("DELETE FROM architecture WHERE 1=1");
    }

    private void ensureArchitectureIdColumn(String table) {
        try {
            jdbcTemplate.execute(
                "ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS architecture_id UUID");
        } catch (DataAccessException e) {
            throw new IllegalStateException(
                "Failed to ensure architecture_id column on " + table + ": " + e.getMessage(), e);
        }
    }

    /**
     * Replaces the table's single-column PK on {@code id} with a composite
     * {@code (id, architecture_id)} PK so two architectures can hold rows
     * with the same {@code id} value. Idempotent: silently skips if the
     * composite PK is already in place from a previous test method (the
     * Spring context — and therefore the H2 schema — is cached across
     * methods within this class).
     */
    private void relaxToCompositePrimaryKey(String table) {
        // First, ensure architecture_id is NOT NULL (a PK column cannot be
        // nullable). H2 silently no-ops if it's already NOT NULL.
        try {
            // Backfill any pre-existing rows (defensive — should be none in a
            // freshly-cleaned schema) before flipping NOT NULL.
            jdbcTemplate.execute(
                "UPDATE " + table + " SET architecture_id = '00000000-0000-0000-0000-000000000000' "
                    + "WHERE architecture_id IS NULL");
            jdbcTemplate.execute(
                "ALTER TABLE " + table + " ALTER COLUMN architecture_id SET NOT NULL");
        } catch (DataAccessException ignored) {
            // Already NOT NULL or the table is empty — both fine.
        }

        // Drop the existing single-column PK, then add the composite PK. H2's
        // generated PK constraint is named after the table; querying
        // INFORMATION_SCHEMA finds it portably.
        try {
            String pkName = jdbcTemplate.queryForObject(
                "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS "
                    + "WHERE TABLE_NAME = ? AND CONSTRAINT_TYPE = 'PRIMARY KEY'",
                String.class, table.toUpperCase());
            if (pkName != null) {
                jdbcTemplate.execute("ALTER TABLE " + table + " DROP CONSTRAINT " + pkName);
            }
        } catch (DataAccessException ignored) {
            // No PK present (already relaxed) — fall through.
        }
        try {
            jdbcTemplate.execute(
                "ALTER TABLE " + table + " ADD PRIMARY KEY (id, architecture_id)");
        } catch (DataAccessException ignored) {
            // Composite PK already exists — ignore (idempotent across test
            // methods within the cached Spring context).
        }
    }

    // =========================================================================
    // PREFLIGHT TESTS
    // =========================================================================

    /**
     * Test 1 (safety property (b)): preflight detects a {@code same_uuid}
     * conflict when an element id in the user's selection already exists in
     * the target architecture by UUID match.
     *
     * Seeds source with 2 applications (no FK references). Seeds target with
     * the SAME UUID for one of them. Runs preflight selecting both apps.
     * Asserts: 1 conflict reported with conflictReason='same_uuid' for the
     * shared app's id; the other app produces no conflict.
     */
    @Test
    @DisplayName("Test 1 (b): preflight reports same_uuid conflict when target already has the id")
    void testPreflightDetectsSameUuidConflict() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source", null, false);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        // Two model files (one per architecture).
        String srcMfId = newModelFile(sourceArchId);
        String tgtMfId = newModelFile(targetArchId);

        // Two applications in source. The first SHARES its UUID with a row in
        // the target; the second is unique to source.
        UUID sharedAppId = UUID.randomUUID();
        UUID uniqueAppId = UUID.randomUUID();
        insertApplication(sharedAppId.toString(), srcMfId, "Shared App", "SHA", sourceArchId);
        insertApplication(uniqueAppId.toString(), srcMfId, "Unique App", "UNI", sourceArchId);

        // Pre-seed the target with the same UUID for the shared app.
        insertApplication(sharedAppId.toString(), tgtMfId, "Shared App (target name)", "SHA", targetArchId);

        // Run preflight selecting both.
        SelectiveCopyPreflightResponse response = selectiveCopyService.preflight(
            projectId,
            targetArchId,
            new SelectiveCopyPreflightRequest(
                sourceArchId,
                List.of(sharedAppId, uniqueAppId)));

        // Exactly one conflict — the shared app — with reason same_uuid.
        assertThat(response.conflicts())
            .as("preflight should report a same_uuid conflict for the shared app id")
            .hasSize(1);
        ConflictItem conflict = response.conflicts().get(0);
        assertThat(conflict.elementId()).isEqualTo(sharedAppId);
        assertThat(conflict.conflictReason()).isEqualTo("same_uuid");
        assertThat(conflict.elementType()).isEqualTo("applications");
        // Auto-included is empty because there are no FK references.
        assertThat(response.autoIncluded()).isEmpty();
        // Summary counts match.
        assertThat(response.summary().totalSelected()).isEqualTo(2);
        assertThat(response.summary().conflictCount()).isEqualTo(1);
        assertThat(response.summary().autoIncludedCount()).isEqualTo(0);
    }

    /**
     * Test 2 (safety property (d) - missing branch): preflight smart cascading
     * auto-includes a referenced element absent from the target.
     *
     * Seeds source with 1 application + 1 service referencing that
     * application via {@code application_id}. Target is empty. Runs preflight
     * selecting only the service. Asserts: the application appears in
     * {@code autoIncluded} with the service's name as {@code includedBecause}.
     */
    @Test
    @DisplayName("Test 2 (d-missing): preflight auto-includes a missing FK reference")
    void testPreflightAutoIncludesMissingReference() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source", null, false);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        String srcMfId = newModelFile(sourceArchId);

        UUID appId = UUID.randomUUID();
        insertApplication(appId.toString(), srcMfId, "Parent App", "PA", sourceArchId);

        UUID svcId = UUID.randomUUID();
        insertService(svcId.toString(), srcMfId, appId.toString(), "Selected Service", sourceArchId);

        // Run preflight selecting ONLY the service.
        SelectiveCopyPreflightResponse response = selectiveCopyService.preflight(
            projectId,
            targetArchId,
            new SelectiveCopyPreflightRequest(sourceArchId, List.of(svcId)));

        // No conflicts (target is empty).
        assertThat(response.conflicts()).isEmpty();
        // The referenced application must be in autoIncluded with the
        // service's name as includedBecause.
        assertThat(response.autoIncluded())
            .as("preflight must auto-include the application referenced by the service")
            .hasSize(1);
        AutoIncludedItem auto = response.autoIncluded().get(0);
        assertThat(auto.elementId()).isEqualTo(appId);
        assertThat(auto.elementType()).isEqualTo("applications");
        assertThat(auto.includedBecause()).isEqualTo("Selected Service");
        assertThat(response.summary().autoIncludedCount()).isEqualTo(1);
        assertThat(response.summary().conflictCount()).isEqualTo(0);
    }

    /**
     * Test 3 (safety property (d) - reuse branch): preflight silently reuses
     * a referenced element when it ALREADY exists in the target by UUID match.
     * NO entry in {@code conflicts} (the user didn't select it) and NO entry
     * in {@code autoIncluded} (it's already there — no need to copy).
     *
     * Seeds source with 1 application + 1 service. Seeds target with the
     * SAME application UUID. Runs preflight selecting only the service.
     * Asserts: zero auto-included entries.
     */
    @Test
    @DisplayName("Test 3 (d-reuse): preflight reuses a referenced element already in target — no auto-include")
    void testPreflightReusesReferenceAlreadyInTarget() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source", null, false);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        String srcMfId = newModelFile(sourceArchId);
        String tgtMfId = newModelFile(targetArchId);

        // The application appears in BOTH architectures with the SAME UUID.
        UUID sharedAppId = UUID.randomUUID();
        insertApplication(sharedAppId.toString(), srcMfId, "Source App", "SA", sourceArchId);
        insertApplication(sharedAppId.toString(), tgtMfId, "Target App", "SA", targetArchId);

        // Service exists only in source, references the shared application.
        UUID svcId = UUID.randomUUID();
        insertService(svcId.toString(), srcMfId, sharedAppId.toString(), "Selected Service", sourceArchId);

        // Run preflight selecting ONLY the service.
        SelectiveCopyPreflightResponse response = selectiveCopyService.preflight(
            projectId,
            targetArchId,
            new SelectiveCopyPreflightRequest(sourceArchId, List.of(svcId)));

        // No conflicts (the service is unique to source) and crucially NO
        // autoIncluded — the application is silently reused from the target.
        assertThat(response.conflicts())
            .as("the service is unique to source so no conflicts")
            .isEmpty();
        assertThat(response.autoIncluded())
            .as("the application is already in target by UUID match — must be silently reused")
            .isEmpty();
        assertThat(response.summary().autoIncludedCount()).isEqualTo(0);
    }

    // =========================================================================
    // COMMIT TESTS
    // =========================================================================

    /**
     * Test 4 (safety property (c) - skip): commit with {@code skip} action
     * leaves the target row unchanged and inserts nothing for the conflicting
     * element.
     *
     * Seeds source with 1 application; target with the same application UUID
     * but different name. Commits with skip resolution. Asserts: target row's
     * name is unchanged; no new application row was inserted; the source row
     * is untouched.
     */
    @Test
    @DisplayName("Test 4 (c-skip): commit with skip leaves the target row unchanged")
    void testCommitSkipLeavesTargetUnchanged() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source", null, false);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        String srcMfId = newModelFile(sourceArchId);
        String tgtMfId = newModelFile(targetArchId);

        UUID sharedAppId = UUID.randomUUID();
        insertApplication(sharedAppId.toString(), srcMfId, "Source Name", "SRC", sourceArchId);
        insertApplication(sharedAppId.toString(), tgtMfId, "Target Name", "TGT", targetArchId);

        long appCountBefore = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM applications", Long.class);
        assertThat(appCountBefore).isEqualTo(2L);

        SelectiveCopyCommitResponse result = selectiveCopyService.commit(
            projectId,
            targetArchId,
            new SelectiveCopyCommitRequest(
                sourceArchId,
                List.of(sharedAppId),
                List.of(new ResolutionItem(sharedAppId, "skip"))));

        assertThat(result.skipped()).isEqualTo(1);
        assertThat(result.copied()).isEqualTo(0);
        assertThat(result.overwritten()).isEqualTo(0);
        assertThat(result.duplicated()).isEqualTo(0);

        // No new row was inserted.
        long appCountAfter = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM applications", Long.class);
        assertThat(appCountAfter)
            .as("skip must not insert a new application row")
            .isEqualTo(appCountBefore);

        // Target row unchanged.
        Map<String, Object> targetRow = jdbcTemplate.queryForMap(
            "SELECT name, abbreviation FROM applications WHERE id = ? AND architecture_id = ?",
            sharedAppId.toString(), targetArchId);
        assertThat(targetRow.get("name"))
            .as("target row must keep its original name on skip")
            .isEqualTo("Target Name");
        assertThat(targetRow.get("abbreviation")).isEqualTo("TGT");

        // Source row untouched.
        Map<String, Object> sourceRow = jdbcTemplate.queryForMap(
            "SELECT name FROM applications WHERE id = ? AND architecture_id = ?",
            sharedAppId.toString(), sourceArchId);
        assertThat(sourceRow.get("name")).isEqualTo("Source Name");
    }

    /**
     * Test 5 (safety property (c) - overwrite): commit with {@code overwrite}
     * UPDATEs the target row in place using the source row's column values;
     * id is preserved (no INSERT).
     *
     * Seeds source with 1 application; target with the same UUID but
     * different name. Commits with overwrite resolution. Asserts: target
     * row's name now matches source's; row count unchanged (no INSERT).
     */
    @Test
    @DisplayName("Test 5 (c-overwrite): commit with overwrite UPDATEs target row preserving id")
    void testCommitOverwriteUpdatesTargetInPlace() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source", null, false);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        String srcMfId = newModelFile(sourceArchId);
        String tgtMfId = newModelFile(targetArchId);

        UUID sharedAppId = UUID.randomUUID();
        insertApplication(sharedAppId.toString(), srcMfId, "Source Name", "SRC", sourceArchId);
        insertApplication(sharedAppId.toString(), tgtMfId, "Target Name", "TGT", targetArchId);

        long appCountBefore = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM applications", Long.class);

        SelectiveCopyCommitResponse result = selectiveCopyService.commit(
            projectId,
            targetArchId,
            new SelectiveCopyCommitRequest(
                sourceArchId,
                List.of(sharedAppId),
                List.of(new ResolutionItem(sharedAppId, "overwrite"))));

        assertThat(result.overwritten()).isEqualTo(1);
        assertThat(result.copied()).isEqualTo(1);
        assertThat(result.skipped()).isEqualTo(0);
        assertThat(result.duplicated()).isEqualTo(0);

        // Row count unchanged — overwrite is an UPDATE, not an INSERT.
        long appCountAfter = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM applications", Long.class);
        assertThat(appCountAfter)
            .as("overwrite must not change the row count (UPDATE not INSERT)")
            .isEqualTo(appCountBefore);

        // Target row's name now matches the source's; id preserved.
        Map<String, Object> targetRow = jdbcTemplate.queryForMap(
            "SELECT id, name, abbreviation FROM applications WHERE id = ? AND architecture_id = ?",
            sharedAppId.toString(), targetArchId);
        assertThat(targetRow.get("id")).isEqualTo(sharedAppId.toString());
        assertThat(targetRow.get("name"))
            .as("target row's name must now match the source's")
            .isEqualTo("Source Name");
        assertThat(targetRow.get("abbreviation")).isEqualTo("SRC");
    }

    /**
     * Test 6 (safety property (c) - duplicate + intra-copy-set FK rewiring):
     * commit with {@code duplicate} action creates a fresh UUID and rewires
     * FK columns from OTHER copied elements to the new id.
     *
     * Seeds source with 1 application + 1 service referencing that
     * application. Target has the same application UUID (conflict). Commits
     * with {@code duplicate} for the application. Asserts:
     *   - the original target application row is untouched (still has its
     *     original name).
     *   - a new application row exists in the target with a fresh UUID and
     *     the source's name.
     *   - the new service row's {@code application_id} is rewired to the
     *     freshly generated UUID, NOT the original (conflicting) UUID.
     */
    @Test
    @DisplayName("Test 6 (c-duplicate): commit with duplicate creates fresh UUID and rewires intra-copy-set FK")
    void testCommitDuplicateRewiresIntraCopySetFk() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source", null, false);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        String srcMfId = newModelFile(sourceArchId);
        String tgtMfId = newModelFile(targetArchId);

        UUID conflictingAppId = UUID.randomUUID();
        insertApplication(conflictingAppId.toString(), srcMfId, "Source App", "SRC", sourceArchId);
        // Target has the same UUID but different name — this is the conflict.
        insertApplication(conflictingAppId.toString(), tgtMfId, "Target App (untouched)", "TGT", targetArchId);

        // Source service referencing the conflicting app.
        UUID svcId = UUID.randomUUID();
        insertService(svcId.toString(), srcMfId, conflictingAppId.toString(), "Source Service", sourceArchId);

        SelectiveCopyCommitResponse result = selectiveCopyService.commit(
            projectId,
            targetArchId,
            new SelectiveCopyCommitRequest(
                sourceArchId,
                List.of(conflictingAppId, svcId),
                List.of(new ResolutionItem(conflictingAppId, "duplicate"))));

        assertThat(result.duplicated())
            .as("the conflicting application should be reported as duplicated")
            .isEqualTo(1);
        // The service was inserted verbatim (no conflict), and the duplicate
        // app counts as a copied operation too.
        assertThat(result.copied()).isEqualTo(2);

        // Original target application row is untouched.
        Map<String, Object> originalTargetApp = jdbcTemplate.queryForMap(
            "SELECT name, abbreviation FROM applications WHERE id = ? AND architecture_id = ?",
            conflictingAppId.toString(), targetArchId);
        assertThat(originalTargetApp.get("name"))
            .as("original target row must be untouched (duplicate INSERTs a NEW row)")
            .isEqualTo("Target App (untouched)");

        // Find the new (duplicated) application row in target — same name as
        // the source's but a fresh UUID.
        List<Map<String, Object>> targetApps = jdbcTemplate.queryForList(
            "SELECT id, name FROM applications WHERE architecture_id = ?", targetArchId);
        assertThat(targetApps)
            .as("target should now have 2 application rows: the original + the duplicate")
            .hasSize(2);
        Map<String, Object> dupApp = targetApps.stream()
            .filter(r -> "Source App".equals(r.get("name")))
            .findFirst()
            .orElseThrow(() -> new AssertionError("duplicated app row not found in target"));
        String dupAppId = (String) dupApp.get("id");
        assertThat(dupAppId)
            .as("duplicated row must have a fresh UUID, not the original conflicting one")
            .isNotEqualTo(conflictingAppId.toString());

        // The copied service must point at the NEW duplicated app id, NOT
        // the original conflicting id (this is the FK-rewiring assertion).
        Map<String, Object> targetSvc = jdbcTemplate.queryForMap(
            "SELECT id, application_id FROM services WHERE id = ? AND architecture_id = ?",
            svcId.toString(), targetArchId);
        assertThat(targetSvc.get("application_id"))
            .as("service's application_id must be rewired to the duplicated app's new id")
            .isEqualTo(dupAppId);
        assertThat(targetSvc.get("application_id"))
            .as("FK must NOT still point at the original conflicting id")
            .isNotEqualTo(conflictingAppId.toString());
    }

    // =========================================================================
    // VALIDATION TESTS
    // =========================================================================

    /**
     * Test 7 (safety properties (e) + (f)): preflight refuses an archived
     * source with {@link ArchivedArchitectureSourceException} (mapped to 422
     * {@code archived_source}) AND refuses a same-architecture self-copy with
     * {@link SameArchitectureCopyException} (mapped to 422
     * {@code same_architecture}). Defence-in-depth — both refusals are
     * exercised by both preflight and commit.
     */
    @Test
    @DisplayName("Test 7 (e)+(f): preflight + commit refuse archived source and same-architecture self-copy")
    void testPreflightRefusesArchivedSourceAndSameArchitecture() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Archived Source", null, true);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        // (e) Archived-source refusal — preflight.
        assertThatThrownBy(() -> selectiveCopyService.preflight(
            projectId,
            targetArchId,
            new SelectiveCopyPreflightRequest(sourceArchId, List.of())))
            .as("preflight must refuse archived source per safety property (e)")
            .isInstanceOf(ArchivedArchitectureSourceException.class);

        // (e) Archived-source refusal — commit (defence in depth).
        assertThatThrownBy(() -> selectiveCopyService.commit(
            projectId,
            targetArchId,
            new SelectiveCopyCommitRequest(sourceArchId, List.of(), List.of())))
            .as("commit must also refuse archived source")
            .isInstanceOf(ArchivedArchitectureSourceException.class);

        // (f) Same-architecture refusal — preflight (target as source).
        assertThatThrownBy(() -> selectiveCopyService.preflight(
            projectId,
            targetArchId,
            new SelectiveCopyPreflightRequest(targetArchId, List.of())))
            .as("preflight must refuse same-architecture per safety property (f)")
            .isInstanceOf(SameArchitectureCopyException.class);

        // (f) Same-architecture refusal — commit.
        assertThatThrownBy(() -> selectiveCopyService.commit(
            projectId,
            targetArchId,
            new SelectiveCopyCommitRequest(targetArchId, List.of(), List.of())))
            .as("commit must also refuse same-architecture")
            .isInstanceOf(SameArchitectureCopyException.class);
    }

    // =========================================================================
    // GAP-FILL TESTS (Task Group 11)
    // =========================================================================

    /**
     * Test 8 (safety property (a)): atomic rollback on mid-commit failure.
     *
     * <p>Wires a {@link ThrowingJdbcTemplate} (via {@link SelectiveCopyTestConfig})
     * that throws on the first {@code update(String, Object[])} call once
     * armed. Selective copy's commit path performs all writes via that
     * single method (both INSERTs and UPDATEs), so arming it after seeding
     * guarantees we trip the very first commit-write call.</p>
     *
     * <p>Seeds source with 1 application + 1 service that references it,
     * plus a target row with the same UUID as the application (a conflict
     * the test resolves to {@code overwrite} so the commit attempts BOTH
     * an UPDATE and an INSERT). Arms the throwing wrapper, runs commit,
     * and asserts:</p>
     *
     * <ul>
     *   <li>commit surfaces the exception;</li>
     *   <li>the target row's name is UNCHANGED (the {@code overwrite} UPDATE
     *       was rolled back);</li>
     *   <li>no new service row was inserted in the target;</li>
     *   <li>the source rows are byte-for-byte untouched.</li>
     * </ul>
     */
    @Test
    @DisplayName("Test 8 (a): commit rolls back atomically when a mid-commit JDBC update fails")
    void testCommitAtomicRollbackOnMidCommitFailure() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source Atomic", null, false);
        seedArchitecture(targetArchId, projectId, "Target Atomic", null, false);

        String srcMfId = newModelFile(sourceArchId);
        String tgtMfId = newModelFile(targetArchId);

        // Source has app + service referencing it.
        UUID sharedAppId = UUID.randomUUID();
        UUID sourceSvcId = UUID.randomUUID();
        insertApplication(sharedAppId.toString(), srcMfId, "Source App", "SRC", sourceArchId);
        insertService(sourceSvcId.toString(), srcMfId, sharedAppId.toString(),
            "Source Service", sourceArchId);
        // Target has the SAME app uuid but different name — this is the conflict
        // the test will resolve to overwrite (forcing an UPDATE write call).
        insertApplication(sharedAppId.toString(), tgtMfId, "Target App (must remain)", "TGT",
            targetArchId);

        // Snapshot pre-commit state so we can assert nothing changed.
        long applicationsBefore = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM applications", Long.class);
        long servicesBefore = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM services", Long.class);
        Map<String, Object> targetAppBefore = jdbcTemplate.queryForMap(
            "SELECT name, abbreviation FROM applications WHERE id = ? AND architecture_id = ?",
            sharedAppId.toString(), targetArchId);
        Map<String, Object> sourceAppBefore = jdbcTemplate.queryForMap(
            "SELECT name FROM applications WHERE id = ? AND architecture_id = ?",
            sharedAppId.toString(), sourceArchId);
        Map<String, Object> sourceSvcBefore = jdbcTemplate.queryForMap(
            "SELECT name, application_id FROM services WHERE id = ? AND architecture_id = ?",
            sourceSvcId.toString(), sourceArchId);

        // Arm the throwing wrapper to fail on the first commit-time write.
        assertThat(jdbcTemplate)
            .as("the test must be wired with the ThrowingJdbcTemplate via SelectiveCopyTestConfig")
            .isInstanceOf(ThrowingJdbcTemplate.class);
        ThrowingJdbcTemplate throwing = (ThrowingJdbcTemplate) jdbcTemplate;
        throwing.throwOn.set(new RuntimeException("Simulated mid-commit JDBC failure"));

        try {
            assertThatThrownBy(() -> selectiveCopyService.commit(
                projectId,
                targetArchId,
                new SelectiveCopyCommitRequest(
                    sourceArchId,
                    List.of(sharedAppId, sourceSvcId),
                    List.of(new ResolutionItem(sharedAppId, "overwrite")))))
                .as("commit must surface the simulated JDBC failure")
                .isInstanceOf(RuntimeException.class)
                .hasMessageContaining("Simulated mid-commit JDBC failure");
        } finally {
            // Disarm before assertions / teardown so the verification queries
            // and cleanup deletes can run unimpeded.
            throwing.throwOn.set(null);
        }

        // (a) Target row's name MUST be unchanged — the overwrite UPDATE
        // was rolled back.
        Map<String, Object> targetAppAfter = jdbcTemplate.queryForMap(
            "SELECT name, abbreviation FROM applications WHERE id = ? AND architecture_id = ?",
            sharedAppId.toString(), targetArchId);
        assertThat(targetAppAfter.get("name"))
            .as("safety property (a): the overwrite UPDATE must be rolled back")
            .isEqualTo(targetAppBefore.get("name"));
        assertThat(targetAppAfter.get("abbreviation"))
            .isEqualTo(targetAppBefore.get("abbreviation"));

        // (a) No new service row was inserted in target.
        long applicationsAfter = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM applications", Long.class);
        long servicesAfter = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM services", Long.class);
        assertThat(applicationsAfter)
            .as("safety property (a): no new application row should remain after rollback")
            .isEqualTo(applicationsBefore);
        assertThat(servicesAfter)
            .as("safety property (a): no new service row should remain after rollback")
            .isEqualTo(servicesBefore);

        // (a) Source rows are untouched (selective copy never writes to source).
        Map<String, Object> sourceAppAfter = jdbcTemplate.queryForMap(
            "SELECT name FROM applications WHERE id = ? AND architecture_id = ?",
            sharedAppId.toString(), sourceArchId);
        assertThat(sourceAppAfter.get("name")).isEqualTo(sourceAppBefore.get("name"));
        Map<String, Object> sourceSvcAfter = jdbcTemplate.queryForMap(
            "SELECT name, application_id FROM services WHERE id = ? AND architecture_id = ?",
            sourceSvcId.toString(), sourceArchId);
        assertThat(sourceSvcAfter.get("name")).isEqualTo(sourceSvcBefore.get("name"));
        assertThat(sourceSvcAfter.get("application_id"))
            .isEqualTo(sourceSvcBefore.get("application_id"));
    }

    /**
     * Test 9 (safety property (g)): {@code discovery_run} rows are NOT
     * copied by selective copy.
     *
     * <p>The Discovery domain is permanent, time-stamped provenance for the
     * source architecture and must never appear under the target after
     * selective copy (Discovery is locked one-run-per-architecture per the
     * spec). Threads are file-based and project-scoped, so they too are
     * out of scope for the JDBC commit path — by inspection the service
     * NEVER touches thread storage (it has no ThreadStore dependency
     * injected at all), making the Discovery-table assertion the
     * load-bearing demonstration that excluded scopes are honoured.</p>
     *
     * <p>Seeds source with: 1 application + 1 discovery_run pointing at the
     * source architecture. Runs a normal commit selecting the application
     * (no conflict — target is empty). Asserts:</p>
     *
     * <ul>
     *   <li>commit succeeded and copied the application;</li>
     *   <li>target architecture has zero {@code discovery_run} rows;</li>
     *   <li>source's {@code discovery_run} is byte-for-byte untouched
     *       (id, project, status all unchanged);</li>
     *   <li>the total {@code discovery_run} count is unchanged
     *       (no new rows of any kind).</li>
     * </ul>
     */
    @Test
    @DisplayName("Test 9 (g): selective copy does not touch discovery_run rows in either direction")
    void testCommitDoesNotCopyDiscoveryRuns() {
        UUID sourceArchId = UUID.randomUUID();
        UUID targetArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source With Discovery", null, false);
        seedArchitecture(targetArchId, projectId, "Target", null, false);

        String srcMfId = newModelFile(sourceArchId);
        // No model file in target — the application is a no-conflict copy.

        UUID appId = UUID.randomUUID();
        insertApplication(appId.toString(), srcMfId, "Source App", "SRC", sourceArchId);

        // Seed a discovery_run pointing at the source architecture. We use
        // raw JDBC insert rather than the JPA repository because the entity
        // requires a JSONB column with a sensible default and going through
        // raw SQL keeps the test focused on the exclusion property (the
        // service must never read or write this table).
        UUID discoveryRunId = UUID.randomUUID();
        DiscoveryRunEntity run = DiscoveryRunEntity.builder()
            .id(discoveryRunId)
            .projectId(projectId)
            .architectureId(sourceArchId)
            .status("COMPLETED")
            .build();
        discoveryRunRepository.save(run);

        long discoveryRunsBefore = discoveryRunRepository.count();
        long sourceDiscoveryRunsBefore = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM discovery_run WHERE architecture_id = ?",
            Long.class, sourceArchId);
        assertThat(sourceDiscoveryRunsBefore)
            .as("source must have its discovery_run seeded")
            .isEqualTo(1L);

        // Commit the application (a no-conflict, no-auto-include copy).
        SelectiveCopyCommitResponse result = selectiveCopyService.commit(
            projectId,
            targetArchId,
            new SelectiveCopyCommitRequest(
                sourceArchId,
                List.of(appId),
                List.of()));

        assertThat(result.copied())
            .as("the application must have been copied verbatim into target")
            .isEqualTo(1);

        // (g) Target architecture has zero discovery_run rows.
        Long targetDiscoveryRunCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM discovery_run WHERE architecture_id = ?",
            Long.class, targetArchId);
        assertThat(targetDiscoveryRunCount)
            .as("safety property (g): target architecture must have zero discovery_run rows")
            .isEqualTo(0L);

        // (g) Total discovery_run count is unchanged — no new rows of any
        // kind were created by the commit path.
        long discoveryRunsAfter = discoveryRunRepository.count();
        assertThat(discoveryRunsAfter)
            .as("safety property (g): discovery_run total count must be unchanged")
            .isEqualTo(discoveryRunsBefore);

        // (g) Source's discovery_run is byte-for-byte untouched.
        DiscoveryRunEntity sourceRunStill = discoveryRunRepository.findById(discoveryRunId)
            .orElseThrow(() -> new AssertionError("source's discovery_run was deleted"));
        assertThat(sourceRunStill.getArchitectureId()).isEqualTo(sourceArchId);
        assertThat(sourceRunStill.getProjectId()).isEqualTo(projectId);
        assertThat(sourceRunStill.getStatus()).isEqualTo("COMPLETED");

        // The application copy itself worked end-to-end (sanity check).
        Map<String, Object> targetApp = jdbcTemplate.queryForMap(
            "SELECT name, abbreviation FROM applications WHERE id = ? AND architecture_id = ?",
            appId.toString(), targetArchId);
        assertThat(targetApp.get("name")).isEqualTo("Source App");
        assertThat(targetApp.get("abbreviation")).isEqualTo("SRC");
    }

    // =========================================================================
    // SEED HELPERS
    // =========================================================================

    private void seedArchitecture(UUID id, UUID projectId, String name,
                                  String description, boolean archived) {
        ArchitectureEntity arch = ArchitectureEntity.builder()
            .id(id)
            .projectId(projectId)
            .name(name)
            .description(description)
            .archived(archived)
            .build();
        architectureRepository.save(arch);
    }

    private String newModelFile(UUID architectureId) {
        String mfId = "mf-" + UUID.randomUUID();
        modelFileRepository.save(ModelFileEntity.builder()
            .id(mfId)
            .filename("mf-" + UUID.randomUUID())
            .description("Test model file")
            .createdAt(OffsetDateTime.now())
            .updatedAt(OffsetDateTime.now())
            .isDefault(false)
            .projectId(projectId)
            .architectureId(architectureId)
            .build());
        return mfId;
    }

    private void insertApplication(String id, String mfId, String name,
                                   String abbrev, UUID archId) {
        jdbcTemplate.update(
            "INSERT INTO applications (id, model_file_id, name, abbreviation, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?)",
            id, mfId, name, abbrev, archId);
    }

    private void insertService(String id, String mfId, String appId,
                               String name, UUID archId) {
        jdbcTemplate.update(
            "INSERT INTO services (id, model_file_id, application_id, name, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?)",
            id, mfId, appId, name, archId);
    }
}
