package com.example.architecturemodel.integration;

import com.example.architecturemodel.model.dto.ArchitectureDto;
import com.example.architecturemodel.model.entity.ArchitectureEntity;
import com.example.architecturemodel.model.entity.DiscoveryRunEntity;
import com.example.architecturemodel.model.entity.ModelFileEntity;
import com.example.architecturemodel.repository.ArchitectureRepository;
import com.example.architecturemodel.repository.ArchitectureTagRepository;
import com.example.architecturemodel.repository.ModelFileRepository;
import com.example.architecturemodel.repository.entity.DiscoveryRunRepository;
import com.example.architecturemodel.service.ArchitectureCloneService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import javax.sql.DataSource;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * End-to-end integration test for {@link ArchitectureCloneService}, asserting
 * the four critical safety properties at the database level (this is the
 * authoritative test for graph-clone correctness; service-level tests in
 * {@code ArchitectureCloneServiceTest} cover validation paths with mocked
 * JDBC).
 *
 * <h2>Test scope (Task Group 3 of spec #6)</h2>
 * <ol>
 *   <li><b>Happy path graph clone</b> — seeds 1 source architecture with 1
 *       model_file + 2 applications + 1 service + 2 app_business_points + 1
 *       interaction (the interaction's two app_business_point FKs is the
 *       proxy for "application_relationship" the spec text mentions; the
 *       schema in this codebase uses the {@code interactions} table for that
 *       role). Asserts every dependent row gets a fresh UUID and FK columns
 *       are rewired to the cloned base entities — safety properties (b)
 *       (fresh UUIDs) and (c) (FK rewiring).</li>
 *   <li><b>Atomic rollback</b> — wraps {@link JdbcTemplate} with a
 *       {@code @TestConfiguration} that flips into "throw on batchUpdate"
 *       mid-test, then asserts the new architecture row does NOT exist and
 *       no partial rows leak into any in-scope table — safety property (a).</li>
 *   <li><b>discovery_run NOT cloned</b> — seeds a discovery_run on the source
 *       architecture, runs the clone, asserts the new architecture has zero
 *       discovery_run rows AND the source's discovery_run is untouched —
 *       safety property (f).</li>
 *   <li><b>Empty source clones cleanly</b> — seeds source with just the
 *       architecture row (no entities), runs the clone, asserts the new
 *       architecture exists with no orphan rows in any in-scope table.</li>
 * </ol>
 *
 * <h2>Schema setup caveats</h2>
 *
 * <p><b>architecture_id columns:</b> The H2 test schema is generated by JPA's
 * {@code create-drop} from the entity model. Only entities that declare an
 * {@code architectureId} field (currently {@code model_files},
 * {@code architecture_tag}, {@code discovery_run}, {@code temporary_diagrams})
 * get an {@code architecture_id} column on their table. This integration test
 * therefore manually adds {@code architecture_id} columns to the additional
 * tables it exercises ({@code applications}, {@code services},
 * {@code app_business_points}, {@code interactions}) in {@link #setUp()}. In
 * production the same columns are added by Liquibase changeset 089 (verified
 * by spec #1's plumbing tests).</p>
 *
 * <p><b>model_files.filename uniqueness (UPDATED -- Task Group 8):</b>
 * The original {@code @Column(unique = true)} on {@code ModelFileEntity#filename}
 * surfaced a production bug: clones preserve the source filename verbatim, so
 * a global UNIQUE constraint blocked the model_files clone path. Task Group 8
 * fixed this by:
 * <ol>
 *   <li>Removing {@code unique = true} from
 *       {@code ModelFileEntity#filename}'s column annotation.</li>
 *   <li>Adding Liquibase changeset 096 which drops the global
 *       {@code model_files_filename_key} UNIQUE constraint and replaces it
 *       with a composite {@code (architecture_id, filename)} UNIQUE INDEX
 *       ({@code model_files_architecture_id_filename_uidx}).</li>
 * </ol>
 * This integration test no longer needs the legacy
 * {@code dropUniqueConstraintsOnFilenameIfPresent()} workaround that earlier
 * iterations relied on; the JPA-generated H2 schema now matches the production
 * shape (no global unique on filename), so the happy-path test below can clone
 * model_files cleanly.</p>
 *
 * <h2>Transaction boundaries</h2>
 * <p>Tests are NOT annotated {@code @Transactional} so the clone's own
 * {@code @Transactional} boundary is real and rollback semantics can be
 * asserted. Each test cleans up its own seed data in {@link #tearDown()}
 * via direct JDBC deletes.</p>
 *
 * Spec: Multi-Architecture Full Clone (Spec #6)
 * Task Group 3: Backend integration test for graph-clone correctness.
 * Task Group 8: filename-uniqueness production-bug fix verified inline by
 *               removing the workaround and relying on the new schema.
 */
@SpringBootTest
@TestPropertySource(properties = {
    // Discovery + data-entity-point startup ensures are noisy and unrelated.
    "app.data-entity-points.startup-ensure=false"
})
class ArchitectureCloneIntegrationTest {

    /**
     * Test wrapper around the real {@link JdbcTemplate} that lets a single
     * test flip into "throw on batchUpdate" mode after the first N
     * invocations, simulating a mid-clone JDBC failure to drive the atomic
     * rollback test (safety property (a)). All other JdbcTemplate calls
     * delegate to the real bean so the rest of the suite runs untouched.
     */
    public static class ThrowingJdbcTemplate extends JdbcTemplate {
        public final AtomicReference<RuntimeException> throwOn = new AtomicReference<>();
        public final java.util.concurrent.atomic.AtomicInteger batchInvocations =
            new java.util.concurrent.atomic.AtomicInteger(0);

        public ThrowingJdbcTemplate(DataSource dataSource) {
            super(dataSource);
        }

        @Override
        public int[] batchUpdate(String sql, List<Object[]> batchArgs) throws DataAccessException {
            batchInvocations.incrementAndGet();
            RuntimeException pending = throwOn.get();
            if (pending != null) {
                throw pending;
            }
            return super.batchUpdate(sql, batchArgs);
        }
    }

    @TestConfiguration
    static class CloneTestConfig {
        @Bean
        @Primary
        public JdbcTemplate testJdbcTemplate(DataSource dataSource) {
            return new ThrowingJdbcTemplate(dataSource);
        }
    }

    @Autowired
    private ArchitectureCloneService cloneService;

    @Autowired
    private ArchitectureRepository architectureRepository;

    @Autowired
    private ArchitectureTagRepository architectureTagRepository;

    @Autowired
    private ModelFileRepository modelFileRepository;

    @Autowired
    private DiscoveryRunRepository discoveryRunRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private UUID projectId;

    @BeforeEach
    void setUp() {
        projectId = UUID.randomUUID();

        // Reset the throwing wrapper each test (avoid cross-test bleed since
        // the Spring context is reused across tests within a class).
        if (jdbcTemplate instanceof ThrowingJdbcTemplate t) {
            t.throwOn.set(null);
            t.batchInvocations.set(0);
        }

        // Add architecture_id columns to the JPA-managed tables the clone
        // needs to touch in this test. JPA's create-drop only generates
        // architecture_id columns for entities that declare the field;
        // production runs Liquibase changeset 089 to add the same columns.
        // IF NOT EXISTS keeps this idempotent across test methods (Spring
        // context is cached so the schema persists between tests).
        ensureArchitectureIdColumn("applications");
        ensureArchitectureIdColumn("services");
        ensureArchitectureIdColumn("app_business_points");
        ensureArchitectureIdColumn("interactions");

        // Task Group 8 fix: the legacy `dropUniqueConstraintsOnFilenameIfPresent()`
        // workaround is no longer needed. ModelFileEntity#filename no longer
        // declares `unique = true`, and Liquibase changeset 096 replaces the
        // production global UNIQUE constraint with a per-architecture
        // composite (architecture_id, filename) UNIQUE INDEX. The JPA-generated
        // H2 schema therefore matches production: clones can now preserve the
        // source filename verbatim under a fresh architecture_id without
        // colliding.
    }

    @AfterEach
    void tearDown() {
        // Clean up everything we created (and anything cloned from it). We
        // don't use @Transactional on the test itself because that would
        // mask the clone's own transaction boundary that the rollback test
        // relies on.
        jdbcTemplate.update("DELETE FROM interactions WHERE 1=1");
        jdbcTemplate.update("DELETE FROM app_business_points WHERE 1=1");
        jdbcTemplate.update("DELETE FROM services WHERE 1=1");
        jdbcTemplate.update("DELETE FROM applications WHERE 1=1");
        jdbcTemplate.update("DELETE FROM environments WHERE 1=1");
        jdbcTemplate.update("DELETE FROM model_files WHERE 1=1");
        // discovery_run -> architecture FK requires we clear it before the
        // architecture rows go.
        try {
            jdbcTemplate.update("DELETE FROM discovery_run WHERE 1=1");
        } catch (DataAccessException ignored) {
            // Table may not exist in some test profiles.
        }
        jdbcTemplate.update("DELETE FROM architecture_tag WHERE 1=1");
        jdbcTemplate.update("DELETE FROM architecture WHERE 1=1");

        if (jdbcTemplate instanceof ThrowingJdbcTemplate t) {
            t.throwOn.set(null);
        }
    }

    private void ensureArchitectureIdColumn(String table) {
        // H2 supports ALTER TABLE ... ADD COLUMN IF NOT EXISTS.
        try {
            jdbcTemplate.execute(
                "ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS architecture_id UUID");
        } catch (DataAccessException e) {
            throw new IllegalStateException(
                "Failed to ensure architecture_id column on " + table + ": " + e.getMessage(), e);
        }
    }

    /**
     * Test 1 (safety properties (b) + (c)): happy-path graph clone.
     *
     * Seeds the source architecture with a representative subgraph:
     *   - 1 model_file
     *   - 2 applications + 1 service (under app1)
     *   - 2 app_business_points (one per application — base entity
     *     references applications via source_entity_id)
     *   - 1 interaction (dependent row referencing both app_business_points
     *     via primary_app_business_point_id + secondary_app_business_point_id
     *     -- this is the standard "relationship between the two apps"
     *     pattern in this codebase's schema)
     *
     * Asserts:
     *   - new architecture row created with the requested name/description/tags
     *   - 1 new model_file with fresh UUID, pointing at new architecture
     *   - 2 new applications with fresh UUIDs, pointing at new architecture
     *   - 1 new service with fresh UUID, pointing at new architecture
     *   - 2 new app_business_points with fresh UUIDs, source_entity_id rewired
     *     to the cloned applications' new ids
     *   - 1 new interaction with fresh UUID, BOTH FK columns rewired to the
     *     cloned app_business_points' new ids (NOT the source's)
     *   - source rows untouched (originals still exist with original ids and
     *     point at the source architecture)
     */
    @Test
    @DisplayName("Test 1 (b)+(c): happy-path graph clone duplicates rows with fresh UUIDs and rewired FKs")
    void testHappyPathGraphClone() {
        // ----- Seed source architecture -----
        UUID sourceArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Current State", "Captured via Discovery");

        String mfId = "mf-" + UUID.randomUUID();
        ModelFileEntity modelFile = ModelFileEntity.builder()
            .id(mfId)
            .filename("model-file-" + UUID.randomUUID())
            .description("Source model file")
            .createdAt(OffsetDateTime.now())
            .updatedAt(OffsetDateTime.now())
            .isDefault(false)
            .projectId(projectId)
            .architectureId(sourceArchId)
            .build();
        modelFileRepository.save(modelFile);

        String app1Id = "app-" + UUID.randomUUID();
        String app2Id = "app-" + UUID.randomUUID();
        insertApplication(app1Id, mfId, "App One", "APP1", sourceArchId);
        insertApplication(app2Id, mfId, "App Two", "APP2", sourceArchId);

        String svcId = "svc-" + UUID.randomUUID();
        insertService(svcId, mfId, app1Id, "Service One", sourceArchId);

        String abp1Id = "abp-" + UUID.randomUUID();
        String abp2Id = "abp-" + UUID.randomUUID();
        insertAppBusinessPoint(abp1Id, mfId, "ABP1", "outbound", app1Id, sourceArchId);
        insertAppBusinessPoint(abp2Id, mfId, "ABP2", "inbound", app2Id, sourceArchId);

        String interactionId = "int-" + UUID.randomUUID();
        insertInteraction(interactionId, mfId, "App1->App2", abp1Id, abp2Id, sourceArchId);

        // ----- Clone -----
        ArchitectureDto cloned = cloneService.cloneArchitecture(
            projectId,
            sourceArchId,
            "Target State",
            "Designed from current",
            List.of("target", "future"));

        // ----- Assert new architecture metadata -----
        assertThat(cloned.id()).isNotEqualTo(sourceArchId);
        assertThat(cloned.name()).isEqualTo("Target State");
        assertThat(cloned.description()).isEqualTo("Designed from current");
        assertThat(cloned.archived()).isFalse();
        assertThat(cloned.tags()).containsExactlyInAnyOrder("target", "future");
        UUID newArchId = cloned.id();

        ArchitectureEntity newArch = architectureRepository.findById(newArchId).orElseThrow();
        assertThat(newArch.getProjectId()).isEqualTo(projectId);
        assertThat(newArch.getArchived()).isFalse();

        // ----- Assert model_file cloned with fresh UUID -----
        List<Map<String, Object>> newMfs = jdbcTemplate.queryForList(
            "SELECT id, filename, project_id, architecture_id FROM model_files WHERE architecture_id = ?",
            newArchId);
        assertThat(newMfs).hasSize(1);
        Map<String, Object> newMf = newMfs.get(0);
        assertThat(newMf.get("id")).isNotEqualTo(mfId);
        assertThat(newMf.get("filename")).isEqualTo(modelFile.getFilename());
        assertThat(asUuid(newMf.get("project_id"))).isEqualTo(projectId);
        String newMfId = (String) newMf.get("id");

        // ----- Assert 2 applications cloned with fresh UUIDs -----
        List<Map<String, Object>> newApps = jdbcTemplate.queryForList(
            "SELECT id, name, abbreviation, model_file_id, architecture_id FROM applications WHERE architecture_id = ?",
            newArchId);
        assertThat(newApps).hasSize(2);
        Set<String> newAppIds = new HashSet<>();
        for (Map<String, Object> row : newApps) {
            String id = (String) row.get("id");
            newAppIds.add(id);
            assertThat(id).isNotEqualTo(app1Id);
            assertThat(id).isNotEqualTo(app2Id);
            assertThat(asUuid(row.get("architecture_id"))).isEqualTo(newArchId);
            // model_file_id should be rewired to the new model_file
            assertThat(row.get("model_file_id")).isEqualTo(newMfId);
        }

        // ----- Assert 1 service cloned with fresh UUID -----
        List<Map<String, Object>> newServices = jdbcTemplate.queryForList(
            "SELECT id, name, application_id, architecture_id FROM services WHERE architecture_id = ?",
            newArchId);
        assertThat(newServices).hasSize(1);
        Map<String, Object> newSvc = newServices.get(0);
        assertThat(newSvc.get("id")).isNotEqualTo(svcId);
        assertThat(newSvc.get("name")).isEqualTo("Service One");
        // service.application_id should be rewired to one of the new app ids
        assertThat(newAppIds).contains((String) newSvc.get("application_id"));

        // ----- Assert 2 app_business_points cloned, source_entity_id rewired -----
        List<Map<String, Object>> newAbps = jdbcTemplate.queryForList(
            "SELECT id, name, source_entity_id, architecture_id FROM app_business_points WHERE architecture_id = ?",
            newArchId);
        assertThat(newAbps).hasSize(2);
        Set<String> newAbpIds = new HashSet<>();
        for (Map<String, Object> row : newAbps) {
            String id = (String) row.get("id");
            newAbpIds.add(id);
            assertThat(id).isNotEqualTo(abp1Id);
            assertThat(id).isNotEqualTo(abp2Id);
            // source_entity_id (FK to applications) should point at one of
            // the NEW application ids — NOT the source's app ids.
            String sourceEntityId = (String) row.get("source_entity_id");
            assertThat(newAppIds).contains(sourceEntityId);
            assertThat(sourceEntityId).isNotEqualTo(app1Id);
            assertThat(sourceEntityId).isNotEqualTo(app2Id);
        }

        // ----- Assert 1 interaction cloned, BOTH FKs rewired (safety property (c)) -----
        List<Map<String, Object>> newInteractions = jdbcTemplate.queryForList(
            "SELECT id, name, primary_app_business_point_id, secondary_app_business_point_id, architecture_id "
                + "FROM interactions WHERE architecture_id = ?",
            newArchId);
        assertThat(newInteractions).hasSize(1);
        Map<String, Object> newInt = newInteractions.get(0);
        assertThat(newInt.get("id")).isNotEqualTo(interactionId);
        assertThat(newInt.get("name")).isEqualTo("App1->App2");

        String newPrimary = (String) newInt.get("primary_app_business_point_id");
        String newSecondary = (String) newInt.get("secondary_app_business_point_id");
        // Both FK columns must be rewired to the CLONED app_business_points,
        // not the source's. This is the load-bearing FK-rewiring assertion.
        assertThat(newAbpIds).contains(newPrimary);
        assertThat(newAbpIds).contains(newSecondary);
        assertThat(newPrimary).isNotEqualTo(abp1Id);
        assertThat(newSecondary).isNotEqualTo(abp2Id);
        // And the two FKs should be different from each other (the clone
        // shouldn't collapse the two app_business_points into the same id).
        assertThat(newPrimary).isNotEqualTo(newSecondary);

        // ----- Assert source rows untouched -----
        ArchitectureEntity sourceStill = architectureRepository.findById(sourceArchId).orElseThrow();
        assertThat(sourceStill.getName()).isEqualTo("Current State");

        Integer sourceAppCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM applications WHERE architecture_id = ?", Integer.class, sourceArchId);
        assertThat(sourceAppCount).isEqualTo(2);

        Integer sourceInteractionCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM interactions WHERE architecture_id = ? AND id = ?",
            Integer.class, sourceArchId, interactionId);
        assertThat(sourceInteractionCount).isEqualTo(1);
    }

    /**
     * Test 2 (safety property (a)): atomic rollback on mid-clone failure.
     *
     * Wires a {@link ThrowingJdbcTemplate} (via {@link CloneTestConfig}) that
     * throws on the very first batchUpdate. Asserts:
     *   - the clone call surfaces the exception,
     *   - no new architecture row was committed (rollback worked),
     *   - the source architecture is still present and untouched.
     */
    @Test
    @DisplayName("Test 2 (a): atomic rollback when batchUpdate throws mid-clone")
    void testAtomicRollbackOnBatchUpdateFailure() {
        UUID sourceArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source Atomic", null);

        // Seed at least one model_file under the source so the clone reaches
        // the first batchUpdate (clone iterates IN_SCOPE_TABLES_IN_ORDER and
        // model_files is the first table it visits).
        String mfId = "mf-rollback-" + UUID.randomUUID();
        modelFileRepository.save(ModelFileEntity.builder()
            .id(mfId)
            .filename("rollback-mf-" + UUID.randomUUID())
            .createdAt(OffsetDateTime.now())
            .updatedAt(OffsetDateTime.now())
            .isDefault(false)
            .projectId(projectId)
            .architectureId(sourceArchId)
            .build());

        long architecturesBefore = architectureRepository.count();
        long modelFilesBefore = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM model_files", Long.class);

        // Capture the throwing-wrapper and arm it.
        assertThat(jdbcTemplate).isInstanceOf(ThrowingJdbcTemplate.class);
        ThrowingJdbcTemplate throwing = (ThrowingJdbcTemplate) jdbcTemplate;
        throwing.throwOn.set(new RuntimeException("Simulated mid-clone JDBC failure"));

        try {
            assertThatThrownBy(() -> cloneService.cloneArchitecture(
                projectId,
                sourceArchId,
                "Will Rollback",
                null,
                null))
                .isInstanceOf(RuntimeException.class)
                .hasMessageContaining("Simulated mid-clone JDBC failure");
        } finally {
            throwing.throwOn.set(null);
        }

        // The new architecture row + tag rows must be rolled back.
        long architecturesAfter = architectureRepository.count();
        assertThat(architecturesAfter)
            .as("clone should have rolled back the new architecture row")
            .isEqualTo(architecturesBefore);

        // No "Will Rollback" architecture should exist anywhere.
        assertThat(architectureRepository.existsByProjectIdAndNameIgnoreCase(
            projectId, "Will Rollback")).isFalse();

        // No new model_files row created (only the source's pre-existing one).
        long modelFilesAfter = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM model_files", Long.class);
        assertThat(modelFilesAfter)
            .as("no new model_files row should remain after rollback")
            .isEqualTo(modelFilesBefore);

        // Source architecture and its model_file are still present.
        assertThat(architectureRepository.findById(sourceArchId)).isPresent();
        assertThat(modelFileRepository.findById(mfId)).isPresent();
    }

    /**
     * Test 3 (safety property (f)): {@code discovery_run} rows are NOT
     * cloned. The Discovery domain is permanent, time-stamped provenance for
     * the source architecture and must never appear under the cloned
     * architecture (cloning would create misleading provenance).
     *
     * Seeds the source architecture + 1 discovery_run pointing at the source.
     * Runs the clone. Asserts:
     *   - new architecture has zero discovery_run rows
     *   - source's discovery_run is untouched (id, status, project unchanged)
     */
    @Test
    @DisplayName("Test 3 (f): discovery_run is not cloned and source's run is untouched")
    void testDiscoveryRunNotCloned() {
        UUID sourceArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source With Discovery", null);

        UUID discoveryRunId = UUID.randomUUID();
        DiscoveryRunEntity run = DiscoveryRunEntity.builder()
            .id(discoveryRunId)
            .projectId(projectId)
            .architectureId(sourceArchId)
            .status("COMPLETED")
            .build();
        discoveryRunRepository.save(run);

        long discoveryRunsBefore = discoveryRunRepository.count();

        ArchitectureDto cloned = cloneService.cloneArchitecture(
            projectId,
            sourceArchId,
            "Clone Without Discovery",
            null,
            null);

        UUID newArchId = cloned.id();

        // The new architecture must have zero discovery_run rows.
        Long newArchDiscoveryRunCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM discovery_run WHERE architecture_id = ?",
            Long.class, newArchId);
        assertThat(newArchDiscoveryRunCount)
            .as("safety property (f): cloned architecture must have zero discovery_run rows")
            .isEqualTo(0L);

        // The total discovery_run count must be unchanged (source still has
        // its run; no new rows created).
        long discoveryRunsAfter = discoveryRunRepository.count();
        assertThat(discoveryRunsAfter).isEqualTo(discoveryRunsBefore);

        // The source's discovery_run is byte-for-byte untouched.
        DiscoveryRunEntity sourceRunStill = discoveryRunRepository.findById(discoveryRunId).orElseThrow();
        assertThat(sourceRunStill.getArchitectureId()).isEqualTo(sourceArchId);
        assertThat(sourceRunStill.getProjectId()).isEqualTo(projectId);
        assertThat(sourceRunStill.getStatus()).isEqualTo("COMPLETED");
    }

    /**
     * Test 4: empty source architecture clones cleanly. Smoke test that the
     * generic clone mechanism handles zero-row tables without error and
     * produces no orphan rows.
     *
     * Seeds source with just the architecture row (no model_files, no
     * applications, no anything). Runs the clone. Asserts:
     *   - clone returns a fresh architecture DTO
     *   - new architecture has zero rows in every in-scope table we check
     */
    @Test
    @DisplayName("Test 4: empty source architecture clones with zero orphan rows")
    void testEmptySourceClonesCleanly() {
        UUID sourceArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Empty Source", null);

        ArchitectureDto cloned = cloneService.cloneArchitecture(
            projectId,
            sourceArchId,
            "Empty Clone",
            "Clone of an architecture with no entities",
            List.of());

        UUID newArchId = cloned.id();
        assertThat(newArchId).isNotEqualTo(sourceArchId);
        assertThat(cloned.name()).isEqualTo("Empty Clone");
        assertThat(cloned.tags()).isEmpty();

        // Every in-scope table we touched in setUp should have zero rows for
        // the new architecture.
        for (String table : List.of(
                "model_files", "applications", "services",
                "app_business_points", "interactions")) {
            Long count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + table + " WHERE architecture_id = ?",
                Long.class, newArchId);
            assertThat(count)
                .as("empty source should produce zero orphan rows in " + table)
                .isEqualTo(0L);
        }

        // Architecture row exists with correct name + project.
        ArchitectureEntity persisted = architectureRepository.findById(newArchId).orElseThrow();
        assertThat(persisted.getName()).isEqualTo("Empty Clone");
        assertThat(persisted.getProjectId()).isEqualTo(projectId);
        assertThat(persisted.getArchived()).isFalse();
    }

    /**
     * Test 5 (Task Group 8 gap-fill — production-bug regression):
     * <b>model_files clone now succeeds end-to-end with the source filename
     * preserved verbatim, post Liquibase changeset 096.</b>
     *
     * <p>Earlier iterations of this integration test required a manual
     * {@code dropUniqueConstraintsOnFilenameIfPresent()} workaround to clone
     * model_files at all (the JPA-generated H2 schema honoured the old
     * {@code @Column(unique = true)} on {@code ModelFileEntity#filename},
     * which would have broken every production clone with a 500-class
     * unique-constraint violation).</p>
     *
     * <p>This test asserts the fix end-to-end:</p>
     * <ol>
     *   <li>The schema no longer carries a global UNIQUE on
     *       {@code model_files.filename} — verified by performing the clone
     *       without invoking any constraint-drop helper.</li>
     *   <li>The cloned model_file's {@code filename} is byte-for-byte equal
     *       to the source's (proves the clone path no longer mangles the
     *       filename to dodge the constraint — Option A's footgun).</li>
     *   <li>Two model_files rows now legitimately coexist with the SAME
     *       filename across different {@code architecture_id}s, which is the
     *       conceptually-correct namespace.</li>
     *   <li>The new {@code (architecture_id, filename)} composite uniqueness
     *       still rejects duplicates within a single architecture: a second
     *       INSERT against the cloned architecture with the same filename
     *       throws a {@link DataAccessException}. (This is asserted only when
     *       the H2 fixture honours the composite — JPA's create-drop does
     *       not generate the index from changeset 096, so we install it
     *       inline before the duplicate-INSERT to mirror production.)</li>
     * </ol>
     *
     * <p>Why this is a strategic gap-fill rather than a redundant assertion:
     * the existing happy-path test verifies clone CORRECTNESS (FK rewiring,
     * fresh ids); this test verifies the FILENAME-UNIQUENESS FIX itself —
     * a different production guarantee that no earlier test pinned down.</p>
     */
    @Test
    @DisplayName("Test 5 (Task Group 8 gap-fill): model_files clone succeeds end-to-end with source filename preserved (no workaround required)")
    void testModelFilesCloneSucceedsWithFilenamePreserved() {
        UUID sourceArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Source With Model File", null);

        // Use a deterministic (but unique-per-test-run) filename so the
        // assertion below is unambiguous.
        String sharedFilename = "shared-clone-target-" + UUID.randomUUID() + ".json";
        String mfId = "mf-fix-" + UUID.randomUUID();
        modelFileRepository.save(ModelFileEntity.builder()
            .id(mfId)
            .filename(sharedFilename)
            .description("Source model file for the filename-uniqueness fix test")
            .createdAt(OffsetDateTime.now())
            .updatedAt(OffsetDateTime.now())
            .isDefault(false)
            .projectId(projectId)
            .architectureId(sourceArchId)
            .build());

        // ----- Clone (no workaround invoked) -----
        ArchitectureDto cloned = cloneService.cloneArchitecture(
            projectId,
            sourceArchId,
            "Filename-Fix Verified Clone",
            null,
            null);

        UUID newArchId = cloned.id();

        // 1+2: cloned filename is byte-for-byte equal to the source.
        List<Map<String, Object>> rowsByFilename = jdbcTemplate.queryForList(
            "SELECT id, filename, architecture_id FROM model_files WHERE filename = ?",
            sharedFilename);
        assertThat(rowsByFilename)
            .as("two model_files rows now legitimately share a filename across architectures")
            .hasSize(2);

        Set<UUID> archIds = new HashSet<>();
        Set<String> ids = new HashSet<>();
        for (Map<String, Object> row : rowsByFilename) {
            archIds.add(asUuid(row.get("architecture_id")));
            ids.add((String) row.get("id"));
            assertThat(row.get("filename")).isEqualTo(sharedFilename);
        }
        assertThat(archIds).containsExactlyInAnyOrder(sourceArchId, newArchId);
        assertThat(ids).hasSize(2); // distinct primary keys

        // 4: composite uniqueness still rejects two rows with the same
        //    (architecture_id, filename). JPA's create-drop does not generate
        //    the index from changeset 096 in this H2 fixture, so we install
        //    it inline (idempotent) before attempting the duplicate INSERT
        //    to mirror production semantics.
        try {
            jdbcTemplate.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS model_files_architecture_id_filename_uidx "
                    + "ON model_files (architecture_id, filename)");
        } catch (DataAccessException ignored) {
            // Index may already exist from a previous test in the cached
            // Spring context — IF NOT EXISTS handles that, this catch is
            // belt-and-braces for driver semantics.
        }

        String dupId = "mf-dup-" + UUID.randomUUID();
        assertThatThrownBy(() -> jdbcTemplate.update(
            "INSERT INTO model_files (id, filename, project_id, architecture_id, "
                + "created_at, updated_at, is_default) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?)",
            dupId,
            sharedFilename, // same filename
            projectId,
            newArchId,      // SAME architecture_id as the cloned row
            OffsetDateTime.now(),
            OffsetDateTime.now(),
            false))
            .as("composite (architecture_id, filename) UNIQUE must reject duplicates within an architecture")
            .isInstanceOf(DataAccessException.class);
    }

    // ---------------------------------------------------------------------
    // Seed helpers — direct JDBC inserts (the entities for these tables
    // don't have an architectureId field on the JPA entity, so we can't use
    // the JPA repositories to populate that column).
    // ---------------------------------------------------------------------

    /**
     * Regression for the silent-skip gap: tables that lack an {@code architecture_id}
     * column (libraries + the whole infrastructure domain, all created after
     * changeset 089) are anchored to the architecture via
     * {@code model_file_id -> model_files.architecture_id}. The clone MUST copy
     * them via that chain rather than skip them. {@code environments} is a real
     * such table (its entity has {@code model_file_id} but no {@code architectureId},
     * and this test does NOT add the column), so it faithfully reproduces the
     * production schema. Before the fix the clone dropped these tables entirely,
     * so Suggest-from-current produced a target missing all infrastructure.
     */
    @Test
    @DisplayName("Clone copies model_file_id-scoped tables that lack architecture_id (infra/libraries), rewiring model_file_id")
    void testClonesModelFileScopedTableWithoutArchitectureIdColumn() {
        UUID sourceArchId = UUID.randomUUID();
        seedArchitecture(sourceArchId, projectId, "Current State", "Captured via Discovery");

        String mfId = "mf-" + UUID.randomUUID();
        ModelFileEntity modelFile = ModelFileEntity.builder()
            .id(mfId)
            .filename("model-file-" + UUID.randomUUID())
            .description("Source model file")
            .createdAt(OffsetDateTime.now())
            .updatedAt(OffsetDateTime.now())
            .isDefault(false)
            .projectId(projectId)
            .architectureId(sourceArchId)
            .build();
        modelFileRepository.save(modelFile);

        String envId = "env-" + UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO environments (id, model_file_id, name) VALUES (?, ?, ?)",
            envId, mfId, "Production Tier");

        ArchitectureDto cloned = cloneService.cloneArchitecture(
            projectId, sourceArchId, "Target State", "Designed from current", List.of());
        UUID newArchId = cloned.id();

        // The new model_file the cloned environment must be rewired to.
        List<Map<String, Object>> newMfs = jdbcTemplate.queryForList(
            "SELECT id FROM model_files WHERE architecture_id = ?", newArchId);
        assertThat(newMfs).hasSize(1);
        String newMfId = (String) newMfs.get(0).get("id");

        // The environment must be CLONED (not skipped), scoped via model_file_id.
        List<Map<String, Object>> clonedEnvs = jdbcTemplate.queryForList(
            "SELECT id, name, model_file_id FROM environments "
                + "WHERE model_file_id IN (SELECT id FROM model_files WHERE architecture_id = ?)",
            newArchId);
        assertThat(clonedEnvs)
            .as("environments is model_file_id-scoped (no architecture_id) and MUST be cloned, not skipped")
            .hasSize(1);
        Map<String, Object> env = clonedEnvs.get(0);
        assertThat(env.get("id")).isNotEqualTo(envId);            // fresh id
        assertThat(env.get("name")).isEqualTo("Production Tier"); // value preserved
        assertThat(env.get("model_file_id")).isEqualTo(newMfId);  // rewired to the new model_file

        // Source environment is untouched.
        List<Map<String, Object>> sourceEnvs = jdbcTemplate.queryForList(
            "SELECT id FROM environments WHERE model_file_id = ?", mfId);
        assertThat(sourceEnvs).hasSize(1);
        assertThat(sourceEnvs.get(0).get("id")).isEqualTo(envId);
    }

    private void seedArchitecture(UUID id, UUID projectId, String name, String description) {
        ArchitectureEntity arch = ArchitectureEntity.builder()
            .id(id)
            .projectId(projectId)
            .name(name)
            .description(description)
            .archived(false)
            .build();
        architectureRepository.save(arch);
    }

    private void insertApplication(String id, String mfId, String name, String abbrev, UUID archId) {
        jdbcTemplate.update(
            "INSERT INTO applications (id, model_file_id, name, abbreviation, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?)",
            id, mfId, name, abbrev, archId);
    }

    private void insertService(String id, String mfId, String appId, String name, UUID archId) {
        jdbcTemplate.update(
            "INSERT INTO services (id, model_file_id, application_id, name, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?)",
            id, mfId, appId, name, archId);
    }

    private void insertAppBusinessPoint(String id, String mfId, String name, String kind,
                                        String sourceEntityId, UUID archId) {
        jdbcTemplate.update(
            "INSERT INTO app_business_points (id, model_file_id, name, kind, source_entity_id, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?, ?)",
            id, mfId, name, kind, sourceEntityId, archId);
    }

    private void insertInteraction(String id, String mfId, String name,
                                   String primaryAbpId, String secondaryAbpId, UUID archId) {
        jdbcTemplate.update(
            "INSERT INTO interactions (id, model_file_id, name, primary_app_business_point_id, "
                + "secondary_app_business_point_id, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?, ?)",
            id, mfId, name, primaryAbpId, secondaryAbpId, archId);
    }

    private static UUID asUuid(Object value) {
        if (value == null) return null;
        if (value instanceof UUID u) return u;
        return UUID.fromString(value.toString());
    }
}
