/**
 * SCL corpus export — the cross-service fixture bridge (SCL pipeline spec 10,
 * 2026-08-18: "end-to-end fixture proof").
 *
 * Runs the REAL pipeline (sliceProject → assembleCorpus) over the fixture
 * legacy app and WRITES the canned corpus to
 * `gateway/src/__tests__/fixtures/scl-fixture-corpus.json` — contracts in the
 * exact SclContractDto wire shape AMS would return (snake_case keys incl.
 * `body_json`; the mapping mirrors sclScanRunner's bulk-upsert payload
 * byte-for-byte). The gateway's `sclPipelineEndToEnd.test.ts` consumes this
 * file: scan-shaped data → plan → spec → red suite, all deterministic.
 *
 * DETERMINISM: content is stableStringify'd (sorted keys) then pretty-printed
 * — no timestamps, no machine-dependent paths. The test REGENERATES the file
 * on every run and asserts the on-disk content matches the fresh assembly, so
 * a slicer/assembler change shows up as a DIFF in the committed fixture (the
 * commit-friendly posture), never a silent drift.
 *
 * Parse-heavy (wasm tree-sitter); run via
 * `npm test -- --testPathPattern="src/scl"`.
 */

import * as fs from 'fs';
import * as path from 'path';
import { sliceProject } from '../slicer';
import { assembleCorpus, type SclCorpusContract } from '../corpusAssembler';
import { stableStringify } from '../sclTypes';

const FIXTURE_ROOT = path.join(__dirname, 'fixtures', 'legacy-app');

/** discovery-service/src/scl/__tests__ → repo root → gateway fixtures. */
const GATEWAY_FIXTURE_PATH = path.join(
  __dirname,
  '..', '..', '..', '..',
  'gateway', 'src', '__tests__', 'fixtures', 'scl-fixture-corpus.json'
);

/** EXACTLY the sclScanRunner bulk-upsert wire mapping (AMS SclContractDto). */
function toWireContract(c: SclCorpusContract): Record<string, unknown> {
  return {
    contract_key: c.contractKey,
    kind: c.kind,
    source_path: c.sourcePath,
    source_symbol: c.sourceSymbol,
    content_hash: c.contentHash,
    fan_in: c.rootFanIn,
    roots_json: { roots: c.roots, total: c.rootFanIn, reachable: c.reachable },
    body_json: c.contract,
  };
}

describe('corpus export → gateway fixture (end-to-end bridge)', () => {
  jest.setTimeout(120_000);

  let rendered: string;

  beforeAll(async () => {
    const slice = await sliceProject(FIXTURE_ROOT);
    const corpus = assembleCorpus(slice);
    const doc = {
      note:
        'GENERATED by discovery-service src/scl/__tests__/corpusExport.e2e.test.ts — ' +
        'do not edit by hand; re-run `npm test -- --testPathPattern=src/scl` to refresh.',
      contracts: corpus.contracts.map(toWireContract),
    };
    // stableStringify (sorted keys, no timestamps) → pretty-print for a
    // commit-friendly diffable file. Parsing the stable string first keeps
    // the sorted key order in the pretty output.
    rendered = `${JSON.stringify(JSON.parse(stableStringify(doc)), null, 2)}\n`;
  });

  it('writes the canned corpus and the on-disk file matches a fresh assembly', () => {
    fs.mkdirSync(path.dirname(GATEWAY_FIXTURE_PATH), { recursive: true });
    const before = fs.existsSync(GATEWAY_FIXTURE_PATH)
      ? fs.readFileSync(GATEWAY_FIXTURE_PATH, 'utf8')
      : null;
    if (before !== rendered) {
      // Regenerate on drift — the committed fixture then shows the diff.
      fs.writeFileSync(GATEWAY_FIXTURE_PATH, rendered, 'utf8');
    }
    const onDisk = fs.readFileSync(GATEWAY_FIXTURE_PATH, 'utf8');
    expect(onDisk).toBe(rendered);
  });

  it('is byte-deterministic across two assemblies of the same slice', async () => {
    const slice = await sliceProject(FIXTURE_ROOT);
    const again = assembleCorpus(slice);
    const renderedAgain = `${JSON.stringify(
      JSON.parse(
        stableStringify({
          note:
            'GENERATED by discovery-service src/scl/__tests__/corpusExport.e2e.test.ts — ' +
            'do not edit by hand; re-run `npm test -- --testPathPattern=src/scl` to refresh.',
          contracts: again.contracts.map(toWireContract),
        })
      ),
      null,
      2
    )}\n`;
    expect(renderedAgain).toBe(rendered);
  });

  it('carries the anchors the gateway end-to-end proof consumes', () => {
    const doc = JSON.parse(rendered) as {
      contracts: Array<{ contract_key: string; kind: string; source_symbol: string; body_json: unknown }>;
    };
    const symbols = doc.contracts.map((c) => c.source_symbol);
    // ViewResource external endpoints (the endpoint group the gateway picks).
    expect(symbols).toContain(
      'com.legacy.hier.api.ViewResource#getView(String,String,Integer,javax.ws.rs.core.HttpHeaders)'
    );
    // The provider chain behind them (behaviour tests must generate).
    expect(symbols).toContain(
      'com.legacy.hier.provider.HierarchyViewProvider#getView(Integer,AuditInfo)'
    );
    // The DTO shape the fixtures build.
    expect(
      doc.contracts.some(
        (c) => c.kind === 'shape' && c.source_symbol === 'com.legacy.hier.model.HierarchyViewDetail'
      )
    ).toBe(true);
    // Every contract rides the full wire shape incl. body_json.
    for (const c of doc.contracts) {
      expect(typeof c.contract_key).toBe('string');
      expect(c.body_json).toBeDefined();
    }
  });
});
