/**
 * StartProcCaptureSessionWizard — start a stored-proc / function behaviour
 * capture (Stored Proc & Function Behaviour Program, Spec 3, 2026-09-09).
 *
 * Three steps, DB-native throughout. There is deliberately NO base URL, NO
 * OAS source, NO API auth and NO scenario file import on this wizard:
 *   1. Scope    — the routine catalog from the DB scan (`/db-routines`).
 *                 Triggers are listed but never selectable: by decision they
 *                 are exercised through the DML inside routine scenarios.
 *   2. Database — the credential block lifted from the API wizard's step 3
 *                 (dbType / host / port / database / schema / username /
 *                 password + the optional both-or-nothing read-only pair).
 *   3. Tuning   — attempts per scenario, rows per result set, invocation
 *                 timeout, quiet window; then Start.
 *
 * Start is a three-call sequence, in order:
 *   POST capture-sessions  →  POST .../secrets  →  POST .../start
 * so the password never rides the redacted session row. Every 409 guard code
 * from `/start` is rendered as a sentence with a next step (S0_NOT_PINNED →
 * "Run the DB scan first — it pins S0 automatically.").
 *
 * Scenarios are generated by the LLM against the live database; nothing is
 * imported here.
 */

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  ProcCaptureSession,
  ProcRoutineKind,
  RoutineCatalogRow,
  createProcCaptureSession,
  describeProcError,
  listDbRoutines,
  routineLabel,
  startProcCapture,
  submitProcSecrets,
} from '../../api/procBehaviourApi';
import styles from '../ApiBehaviour/StartCaptureSessionWizard.module.css';
import proc from './ProcBehaviour.module.css';
import type { DbEngineKey } from '../../api/dbEngines';

export const DEFAULT_ATTEMPTS_PER_SCENARIO = 15;
export const DEFAULT_MAX_ROWS_PER_RESULT_SET = 1000;
export const DEFAULT_INVOCATION_TIMEOUT_SECONDS = 300;
export const DEFAULT_QUIET_WINDOW_SECONDS = 120;

type Step = 1 | 2 | 3;
type ProcDbType = DbEngineKey;

export interface StartProcCaptureSessionWizardProps {
  open: boolean;
  projectId: string;
  architectureId: string;
  onClose: () => void;
  onStarted?: (session: ProcCaptureSession) => void;
}

interface DbState {
  dbType: ProcDbType;
  host: string;
  port: string;
  database: string;
  schema: string;
  username: string;
  password: string;
  readonlyUsername: string;
  readonlyPassword: string;
}

const INITIAL_DB: DbState = {
  dbType: 'sybase',
  host: '',
  port: '5000',
  database: '',
  schema: '',
  username: '',
  password: '',
  readonlyUsername: '',
  readonlyPassword: '',
};

function defaultSessionName(): string {
  const now = new Date();
  const stamp = now.toISOString().slice(0, 16).replace('T', ' ');
  return `Proc behaviour capture ${stamp}`;
}

/** Triggers are never selectable (design: no standalone trigger DML scenarios). */
function isSelectableRoutine(r: RoutineCatalogRow): boolean {
  return r.routineKind !== 'trigger';
}

export const StartProcCaptureSessionWizard: React.FC<
  StartProcCaptureSessionWizardProps
> = ({ open, projectId, architectureId, onClose, onStarted }) => {
  const [step, setStep] = useState<Step>(1);
  const [name, setName] = useState<string>(defaultSessionName);
  const [routines, setRoutines] = useState<RoutineCatalogRow[]>([]);
  const [loadingRoutines, setLoadingRoutines] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [kindFilter, setKindFilter] = useState<'all' | ProcRoutineKind>('all');
  const [search, setSearch] = useState('');
  const [db, setDb] = useState<DbState>(INITIAL_DB);
  const [attempts, setAttempts] = useState(String(DEFAULT_ATTEMPTS_PER_SCENARIO));
  const [maxRows, setMaxRows] = useState(String(DEFAULT_MAX_ROWS_PER_RESULT_SET));
  const [timeoutSeconds, setTimeoutSeconds] = useState(
    String(DEFAULT_INVOCATION_TIMEOUT_SECONDS),
  );
  const [quietWindow, setQuietWindow] = useState(String(DEFAULT_QUIET_WINDOW_SECONDS));
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Load the routine catalog whenever the wizard opens.
  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    setLoadingRoutines(true);
    setError(null);
    void (async () => {
      try {
        const rows = await listDbRoutines(projectId, architectureId);
        if (cancelled) return;
        setRoutines(rows);
        // Pre-select every selectable routine: the honest default is "verify
        // everything", and the operator narrows from there.
        setSelected(new Set(rows.filter(isSelectableRoutine).map((r) => r.id)));
      } catch (err) {
        if (!cancelled) setError(describeProcError(err));
      } finally {
        if (!cancelled) setLoadingRoutines(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [open, projectId, architectureId]);

  const visibleRoutines = useMemo(() => {
    const q = search.trim().toLowerCase();
    return routines.filter((r) => {
      if (kindFilter !== 'all' && r.routineKind !== kindFilter) return false;
      if (!q) return true;
      return routineLabel(r).toLowerCase().includes(q);
    });
  }, [routines, kindFilter, search]);

  const selectableVisible = useMemo(
    () => visibleRoutines.filter(isSelectableRoutine),
    [visibleRoutines],
  );

  const toggle = useCallback((id: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const selectAllVisible = useCallback(
    (on: boolean) => {
      setSelected((prev) => {
        const next = new Set(prev);
        for (const r of selectableVisible) {
          if (on) next.add(r.id);
          else next.delete(r.id);
        }
        return next;
      });
    },
    [selectableVisible],
  );

  // Both-or-nothing read-only pair (mirrors the backend rule: a lone value
  // would silently fall back to the write-capable login).
  const readonlyIncomplete =
    (db.readonlyUsername.trim() !== '') !== (db.readonlyPassword !== '');

  const dbComplete =
    db.host.trim() !== '' &&
    db.database.trim() !== '' &&
    db.username.trim() !== '' &&
    db.password !== '' &&
    !readonlyIncomplete;

  const canAdvanceStep1 = selected.size > 0 && name.trim() !== '';

  const handleStart = useCallback(async () => {
    if (submitting) return;
    setError(null);
    setSubmitting(true);
    try {
      // 1. Create the session (redacted config only — no password on the row).
      const session = await createProcCaptureSession(projectId, architectureId, {
        name: name.trim(),
        kind: 'current',
        scopeRoutineIds: Array.from(selected),
        dbConfigRedacted: {
          dbType: db.dbType,
          host: db.host.trim(),
          port: Number(db.port) || null,
          database: db.database.trim(),
          schema: db.schema.trim() || null,
          username: db.username.trim(),
          maxRowsPerQuery: Number(maxRows) || DEFAULT_MAX_ROWS_PER_RESULT_SET,
          queryTimeoutSeconds:
            Number(timeoutSeconds) || DEFAULT_INVOCATION_TIMEOUT_SECONDS,
        },
        captureTuning: {
          attemptsPerScenario: Number(attempts) || DEFAULT_ATTEMPTS_PER_SCENARIO,
          maxRowsPerResultSet: Number(maxRows) || DEFAULT_MAX_ROWS_PER_RESULT_SET,
          invocationTimeoutSeconds:
            Number(timeoutSeconds) || DEFAULT_INVOCATION_TIMEOUT_SECONDS,
          quietWindowSeconds: Number(quietWindow) || DEFAULT_QUIET_WINDOW_SECONDS,
        },
      });

      // 2. Secrets (draft -> configured).
      await submitProcSecrets(projectId, architectureId, session.id, {
        password: db.password,
        readonlyUsername: db.readonlyUsername.trim() || null,
        readonlyPassword: db.readonlyPassword || null,
      });

      // 3. Start (202 + poll). Guard codes surface as sentences.
      await startProcCapture(projectId, architectureId, session.id);
      onStarted?.(session);
    } catch (err) {
      setError(describeProcError(err));
    } finally {
      setSubmitting(false);
    }
  }, [
    submitting,
    projectId,
    architectureId,
    name,
    selected,
    db,
    attempts,
    maxRows,
    timeoutSeconds,
    quietWindow,
    onStarted,
  ]);

  if (!open) return null;

  return (
    <div className={styles.overlay} data-testid="proc-start-capture-wizard">
      <div
        className={`${styles.modal} ${proc.modalWide}`}
        role="dialog"
        aria-modal="true"
        aria-labelledby="proc-start-capture-wizard-title"
      >
        <div className={styles.header}>
          <h2 className={styles.title} id="proc-start-capture-wizard-title">
            Capture stored procedure &amp; function behaviour
          </h2>
          <button
            type="button"
            className={styles.closeButton}
            onClick={onClose}
            disabled={submitting}
            data-testid="proc-start-capture-wizard-close"
            title="Close"
          >
            &times;
          </button>
        </div>

        <div className={styles.stepper} data-testid="proc-start-capture-wizard-stepper">
          {([1, 2, 3] as Step[]).map((n, idx) => (
            <React.Fragment key={n}>
              {idx > 0 && (
                <span className={styles.stepSeparator} aria-hidden="true">
                  &rsaquo;
                </span>
              )}
              <span
                className={`${styles.step} ${
                  n === step ? styles.stepActive : n < step ? styles.stepDone : ''
                }`}
                data-testid={`proc-start-capture-wizard-step-${n}`}
              >
                {n}. {n === 1 ? 'Scope' : n === 2 ? 'Database' : 'Tuning + Start'}
              </span>
            </React.Fragment>
          ))}
        </div>

        <div className={styles.content}>
          {error && (
            <div
              className={styles.errorBanner}
              data-testid="proc-start-capture-wizard-error"
              role="alert"
            >
              {error}
            </div>
          )}

          {step === 1 && (
            <>
              <p className={styles.helperText}>
                Choose the routines to capture. Scenarios are generated by the
                LLM against the live database — there is nothing to import.
                Triggers are listed for context but are never selected: they
                are exercised through the DML inside routine scenarios.
              </p>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-session-name">
                  Session name
                </label>
                <input
                  id="proc-session-name"
                  className={styles.input}
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  data-testid="proc-session-name"
                />
              </div>
              <div className={proc.filterRow}>
                <select
                  value={kindFilter}
                  onChange={(e) =>
                    setKindFilter(e.target.value as 'all' | ProcRoutineKind)
                  }
                  data-testid="proc-scope-kind-filter"
                  aria-label="Filter by routine kind"
                >
                  <option value="all">All kinds</option>
                  <option value="procedure">Procedures</option>
                  <option value="function">Functions</option>
                  <option value="trigger">Triggers</option>
                </select>
                <input
                  type="text"
                  placeholder="Search by name…"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  data-testid="proc-scope-search"
                  aria-label="Search routines"
                />
                <button
                  type="button"
                  className={proc.linkButton}
                  onClick={() => selectAllVisible(true)}
                  data-testid="proc-scope-select-all"
                >
                  Select all
                </button>
                <button
                  type="button"
                  className={proc.linkButton}
                  onClick={() => selectAllVisible(false)}
                  data-testid="proc-scope-select-none"
                >
                  Select none
                </button>
                <span data-testid="proc-scope-selected-count">
                  {selected.size} selected
                </span>
              </div>
              {loadingRoutines && (
                <div data-testid="proc-scope-loading">Loading routine catalog…</div>
              )}
              {!loadingRoutines && routines.length === 0 && (
                <div data-testid="proc-scope-empty">
                  No routines in the catalog yet — run the DB scan first, which
                  builds the routine catalog and pins S0.
                </div>
              )}
              {routines.length > 0 && (
                <div className={proc.tableWrap}>
                  <table className={proc.table} data-testid="proc-scope-table">
                    <thead>
                      <tr>
                        <th />
                        <th>Routine</th>
                        <th>Kind</th>
                        <th className={proc.numeric}>Params</th>
                        <th className={proc.numeric}>Writes</th>
                        <th>Flags</th>
                      </tr>
                    </thead>
                    <tbody>
                      {visibleRoutines.map((r) => {
                        const selectable = isSelectableRoutine(r);
                        const nonCompensatable =
                          r.profile.nonCompensatableReasons.length > 0;
                        return (
                          <tr
                            key={r.id}
                            data-testid="proc-scope-row"
                            data-routine-id={r.id}
                            data-kind={r.routineKind}
                            data-selectable={selectable ? 'true' : 'false'}
                          >
                            <td>
                              <input
                                type="checkbox"
                                checked={selected.has(r.id)}
                                disabled={!selectable}
                                onChange={() => toggle(r.id)}
                                data-testid={`proc-scope-check-${r.id}`}
                                aria-label={`Select ${routineLabel(r)}`}
                              />
                            </td>
                            <td className={proc.mono}>{routineLabel(r)}</td>
                            <td>{r.routineKind}</td>
                            <td className={proc.numeric}>{r.params.length}</td>
                            <td className={proc.numeric}>{r.writesClosure.length}</td>
                            <td>
                              {nonCompensatable && (
                                <span
                                  className={`${proc.flag} ${proc.flagWarn}`}
                                  data-testid={`proc-scope-flag-non-compensatable-${r.id}`}
                                  title={r.profile.nonCompensatableReasons.join('; ')}
                                >
                                  non-compensatable
                                </span>
                              )}
                              {!r.signatureParsed && (
                                <span
                                  className={`${proc.flag} ${proc.flagWarn}`}
                                  data-testid={`proc-scope-flag-signature-unparsed-${r.id}`}
                                  title="The routine signature could not be parsed from the source"
                                >
                                  signature unparsed
                                </span>
                              )}
                              {!selectable && (
                                <span className={`${proc.flag} ${proc.flagMuted}`}>
                                  exercised via routine DML
                                </span>
                              )}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </>
          )}

          {step === 2 && (
            <>
              <p className={styles.helperText}>
                Capture fires real procedure calls, so these credentials must be
                write-capable. Use a <strong>non-production database</strong>{' '}
                pinned at S0: every scenario runs inside the derived
                compensation bracket and the database is returned to S0, but
                the routines genuinely execute.
              </p>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-db-type">
                  DB type
                </label>
                <select
                  id="proc-db-type"
                  className={styles.select}
                  value={db.dbType}
                  onChange={(e) =>
                    setDb((s) => ({ ...s, dbType: e.target.value as ProcDbType }))
                  }
                  data-testid="proc-db-type"
                >
                  <option value="sybase">Sybase ASE</option>
                  <option value="postgres">PostgreSQL</option>
                </select>
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-db-host">
                  Host
                </label>
                <input
                  id="proc-db-host"
                  className={styles.input}
                  value={db.host}
                  onChange={(e) => setDb((s) => ({ ...s, host: e.target.value }))}
                  data-testid="proc-db-host"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-db-port">
                  Port
                </label>
                <input
                  id="proc-db-port"
                  className={styles.input}
                  value={db.port}
                  onChange={(e) => setDb((s) => ({ ...s, port: e.target.value }))}
                  data-testid="proc-db-port"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-db-database">
                  Database
                </label>
                <input
                  id="proc-db-database"
                  className={styles.input}
                  value={db.database}
                  onChange={(e) => setDb((s) => ({ ...s, database: e.target.value }))}
                  data-testid="proc-db-database"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-db-schema">
                  Schema (optional)
                </label>
                <input
                  id="proc-db-schema"
                  className={styles.input}
                  value={db.schema}
                  onChange={(e) => setDb((s) => ({ ...s, schema: e.target.value }))}
                  data-testid="proc-db-schema"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-db-username">
                  Username
                </label>
                <input
                  id="proc-db-username"
                  className={styles.input}
                  value={db.username}
                  onChange={(e) => setDb((s) => ({ ...s, username: e.target.value }))}
                  data-testid="proc-db-username"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-db-password">
                  Password
                </label>
                <input
                  id="proc-db-password"
                  type="password"
                  className={styles.input}
                  value={db.password}
                  onChange={(e) => setDb((s) => ({ ...s, password: e.target.value }))}
                  data-testid="proc-db-password"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label}>
                  Read-only login (optional, recommended)
                </label>
                <input
                  className={styles.input}
                  placeholder="Read-only username"
                  value={db.readonlyUsername}
                  onChange={(e) =>
                    setDb((s) => ({ ...s, readonlyUsername: e.target.value }))
                  }
                  data-testid="proc-db-readonly-username"
                />
                <input
                  type="password"
                  className={styles.input}
                  placeholder="Read-only password"
                  value={db.readonlyPassword}
                  onChange={(e) =>
                    setDb((s) => ({ ...s, readonlyPassword: e.target.value }))
                  }
                  data-testid="proc-db-readonly-password"
                  style={{ marginTop: 6 }}
                />
                <div className={proc.hint}>
                  When supplied, snapshots, state fingerprints and observation
                  reads connect with this read-only login and the write-capable
                  login above is used ONLY inside compensation brackets. Both
                  fields are required for the split to engage.
                </div>
                {readonlyIncomplete && (
                  <div
                    className={styles.errorBanner}
                    data-testid="proc-db-readonly-incomplete"
                  >
                    Enter BOTH read-only fields — a lone value is ignored and
                    the single-login posture remains.
                  </div>
                )}
              </div>
            </>
          )}

          {step === 3 && (
            <>
              <p className={styles.helperText}>
                Budgets for the capture run. Research (reading the source,
                sampling the database) is free; the attempt budget counts
                invocations fired at a routine.
              </p>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-tuning-attempts">
                  Attempts per scenario
                </label>
                <input
                  id="proc-tuning-attempts"
                  type="number"
                  min={1}
                  className={styles.input}
                  value={attempts}
                  onChange={(e) => setAttempts(e.target.value)}
                  data-testid="proc-tuning-attempts"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-tuning-max-rows">
                  Rows per result set
                </label>
                <input
                  id="proc-tuning-max-rows"
                  type="number"
                  min={1}
                  className={styles.input}
                  value={maxRows}
                  onChange={(e) => setMaxRows(e.target.value)}
                  data-testid="proc-tuning-max-rows"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-tuning-timeout">
                  Invocation timeout (seconds)
                </label>
                <input
                  id="proc-tuning-timeout"
                  type="number"
                  min={1}
                  className={styles.input}
                  value={timeoutSeconds}
                  onChange={(e) => setTimeoutSeconds(e.target.value)}
                  data-testid="proc-tuning-timeout"
                />
              </div>
              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="proc-tuning-quiet-window">
                  Quiet window (seconds)
                </label>
                <input
                  id="proc-tuning-quiet-window"
                  type="number"
                  min={0}
                  className={styles.input}
                  value={quietWindow}
                  onChange={(e) => setQuietWindow(e.target.value)}
                  data-testid="proc-tuning-quiet-window"
                />
              </div>
              <div className={styles.summarySection} data-testid="proc-start-summary">
                <div>
                  <span className={styles.summaryKey}>Routines in scope:</span>{' '}
                  {selected.size}
                </div>
                <div>
                  <span className={styles.summaryKey}>Database:</span>{' '}
                  {db.dbType} · {db.host || '(host missing)'}:{db.port} /{' '}
                  {db.database || '(database missing)'}
                </div>
                <div>
                  <span className={styles.summaryKey}>Read-only split:</span>{' '}
                  {db.readonlyUsername.trim() && db.readonlyPassword
                    ? 'engaged'
                    : 'not supplied'}
                </div>
              </div>
            </>
          )}
        </div>

        <div className={styles.footer}>
          <button
            type="button"
            className={styles.secondaryButton}
            onClick={() => (step === 1 ? onClose() : setStep((s) => (s - 1) as Step))}
            disabled={submitting}
            data-testid="proc-start-capture-wizard-back"
          >
            {step === 1 ? 'Cancel' : 'Back'}
          </button>
          {step === 1 && (
            <button
              type="button"
              className={styles.primaryButton}
              onClick={() => setStep(2)}
              disabled={!canAdvanceStep1}
              data-testid="proc-start-capture-wizard-next"
              title={
                canAdvanceStep1
                  ? undefined
                  : 'Select at least one procedure or function and name the session'
              }
            >
              Next
            </button>
          )}
          {step === 2 && (
            <button
              type="button"
              className={styles.primaryButton}
              onClick={() => setStep(3)}
              disabled={!dbComplete}
              data-testid="proc-start-capture-wizard-next"
              title={
                dbComplete
                  ? undefined
                  : 'Host, database, username and password are required (and the read-only pair must be both-or-nothing)'
              }
            >
              Next
            </button>
          )}
          {step === 3 && (
            <button
              type="button"
              className={styles.primaryButton}
              onClick={() => void handleStart()}
              disabled={submitting}
              data-testid="proc-start-capture-wizard-start"
            >
              {submitting ? 'Starting…' : 'Start'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default StartProcCaptureSessionWizard;
