package com.example.architecturemodel.service;

import com.example.architecturemodel.model.dto.ElementInventoryResponse;
import com.example.architecturemodel.model.dto.ElementInventoryResponse.Domain;
import com.example.architecturemodel.model.dto.ElementInventoryResponse.Type;
import com.example.architecturemodel.model.entity.ArchitectureEntity;
import com.example.architecturemodel.model.entity.ModelFileEntity;
import com.example.architecturemodel.repository.ArchitectureRepository;
import com.example.architecturemodel.repository.ModelFileRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.time.OffsetDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration test for {@link ArchitectureElementInventoryService} verifying
 * the parent-chain read path. Seeds two architectures (A and B) in one
 * project, inserts rows whose {@code model_file_id} points at A's model file
 * but whose leaf {@code architecture_id} column has been deliberately
 * overwritten to B's id via raw SQL — simulating the production drift that
 * triggered spec 2026-05-22-architecture-scope-via-parent-not-leaf.
 *
 * <p>Each test asserts:</p>
 * <ol>
 *   <li>Inventory for architecture A surfaces the drifted row (because the
 *       parent chain {@code logical_data_entities.model_file_id ->
 *       model_files.architecture_id} resolves to A).</li>
 *   <li>Inventory for architecture B does NOT surface the row (its parent
 *       chain points elsewhere even though the leaf column is misleading).</li>
 * </ol>
 *
 * <p>These tests are RED on master (the legacy {@code WHERE architecture_id
 * = ?} query trusts the drifted leaf and surfaces the row under B instead
 * of A) and GREEN on this branch.</p>
 *
 * <p>Spec: 2026-05-22-architecture-scope-via-parent-not-leaf — Task Group 2.</p>
 */
@SpringBootTest
@TestPropertySource(properties = {
    "app.data-entity-points.startup-ensure=false"
})
class ArchitectureElementInventoryServiceLeafDriftTest {

    @Autowired
    private ArchitectureElementInventoryService inventoryService;

    @Autowired
    private ArchitectureRepository architectureRepository;

    @Autowired
    private ModelFileRepository modelFileRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private UUID projectId;
    private UUID archA;
    private UUID archB;
    private String mfA;
    private String mfB;

    @BeforeEach
    void setUp() {
        projectId = UUID.randomUUID();
        archA = UUID.randomUUID();
        archB = UUID.randomUUID();

        // Two architectures in the same project.
        seedArchitecture(archA, "Architecture A (true owner)");
        seedArchitecture(archB, "Architecture B (drifted-leaf target)");

        // One model file per architecture.
        mfA = newModelFile(archA);
        mfB = newModelFile(archB);

        // Some element tables (applications, logical_data_entities, etc.) only
        // gain an architecture_id column at the DB layer via Liquibase 089 in
        // production. The H2 test schema is generated by JPA's create-drop
        // from the entity model and DOES NOT include the column for tables
        // whose JPA entity doesn't declare architectureId. Ensure the column
        // is present on the tables this test seeds.
        ensureArchitectureIdColumn("applications");
        ensureArchitectureIdColumn("logical_data_entities");
        ensureArchitectureIdColumn("logical_data_attributes");
        ensureArchitectureIdColumn("physical_data_entities");
        ensureArchitectureIdColumn("physical_data_attributes");
    }

    @AfterEach
    void tearDown() {
        // Idempotent best-effort cleanup; the cached Spring context reuses
        // the H2 schema across tests within this class.
        safeDelete("physical_data_attributes");
        safeDelete("physical_data_entities");
        safeDelete("logical_data_attributes");
        safeDelete("logical_data_entities");
        safeDelete("applications");
        safeDelete("model_files");
        safeDelete("architecture_tag");
        safeDelete("architecture");
    }

    /**
     * Test 1: logical_data_entity drift — the production-reported bug.
     *
     * <p>Insert one row with model_file_id pointing at A, then UPDATE its
     * leaf architecture_id to B's id. Assert inventory for A surfaces it
     * (parent chain resolves correctly) and inventory for B does not.</p>
     */
    @Test
    @DisplayName("logical_data_entity with drifted leaf appears under parent-chain architecture, not leaf")
    void logicalDataEntityDriftFollowsParentChain() {
        UUID rowId = UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO logical_data_entities (id, model_file_id, name, architecture_id) "
                + "VALUES (?, ?, ?, ?)",
            rowId.toString(), mfA, "Customer LDE", archA);
        // Deliberately drift the leaf column to architecture B.
        jdbcTemplate.update(
            "UPDATE logical_data_entities SET architecture_id = ? WHERE id = ?",
            archB, rowId.toString());

        // Inventory for A surfaces the row (parent chain wins).
        assertTableContainsId(archA, "logical_data_entities", rowId.toString());
        // Inventory for B does NOT surface the row.
        assertTableDoesNotContainId(archB, "logical_data_entities", rowId.toString());
    }

    /**
     * Test 2: physical_data_entity drift — same domain, different table.
     */
    @Test
    @DisplayName("physical_data_entity with drifted leaf appears under parent-chain architecture")
    void physicalDataEntityDriftFollowsParentChain() {
        UUID rowId = UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO physical_data_entities (id, model_file_id, name, architecture_id) "
                + "VALUES (?, ?, ?, ?)",
            rowId.toString(), mfA, "customers_table", archA);
        jdbcTemplate.update(
            "UPDATE physical_data_entities SET architecture_id = ? WHERE id = ?",
            archB, rowId.toString());

        assertTableContainsId(archA, "physical_data_entities", rowId.toString());
        assertTableDoesNotContainId(archB, "physical_data_entities", rowId.toString());
    }

    /**
     * Test 3: logical_data_attribute drift — child table.
     */
    @Test
    @DisplayName("logical_data_attribute with drifted leaf appears under parent-chain architecture")
    void logicalDataAttributeDriftFollowsParentChain() {
        UUID parentLde = UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO logical_data_entities (id, model_file_id, name, architecture_id) "
                + "VALUES (?, ?, ?, ?)",
            parentLde.toString(), mfA, "Customer LDE", archA);

        UUID rowId = UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO logical_data_attributes (id, model_file_id, logical_entity_id, name, is_primary_key, is_nullable, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?)",
            rowId.toString(), mfA, parentLde.toString(), "customer_id", false, true, archA);
        jdbcTemplate.update(
            "UPDATE logical_data_attributes SET architecture_id = ? WHERE id = ?",
            archB, rowId.toString());

        assertTableContainsId(archA, "logical_data_attributes", rowId.toString());
        assertTableDoesNotContainId(archB, "logical_data_attributes", rowId.toString());
    }

    /**
     * Test 4: physical_data_attribute drift — child table.
     */
    @Test
    @DisplayName("physical_data_attribute with drifted leaf appears under parent-chain architecture")
    void physicalDataAttributeDriftFollowsParentChain() {
        UUID parentPde = UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO physical_data_entities (id, model_file_id, name, architecture_id) "
                + "VALUES (?, ?, ?, ?)",
            parentPde.toString(), mfA, "customers_table", archA);

        UUID rowId = UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO physical_data_attributes (id, model_file_id, physical_entity_id, name, is_primary_key, is_nullable, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?)",
            rowId.toString(), mfA, parentPde.toString(), "customer_id", false, true, archA);
        jdbcTemplate.update(
            "UPDATE physical_data_attributes SET architecture_id = ? WHERE id = ?",
            archB, rowId.toString());

        assertTableContainsId(archA, "physical_data_attributes", rowId.toString());
        assertTableDoesNotContainId(archB, "physical_data_attributes", rowId.toString());
    }

    /**
     * Test 5: applications drift — proves cross-domain uniformity.
     *
     * <p>Applications are seeded recently in real workflows (the user's
     * report shows applications appear under the correct architecture
     * because the leaf was still in sync at the time of write). This test
     * proves the parent-chain read path also handles applications, so
     * future drift on any domain follows the same resolution rule.</p>
     */
    @Test
    @DisplayName("application with drifted leaf appears under parent-chain architecture (cross-domain check)")
    void applicationsDriftFollowsParentChain() {
        UUID rowId = UUID.randomUUID();
        jdbcTemplate.update(
            "INSERT INTO applications (id, model_file_id, name, abbreviation, architecture_id) "
                + "VALUES (?, ?, ?, ?, ?)",
            rowId.toString(), mfA, "Order Service", "OS", archA);
        jdbcTemplate.update(
            "UPDATE applications SET architecture_id = ? WHERE id = ?",
            archB, rowId.toString());

        assertTableContainsId(archA, "applications", rowId.toString());
        assertTableDoesNotContainId(archB, "applications", rowId.toString());
    }

    // ------------------------------------------------------------------
    // Assertion helpers
    // ------------------------------------------------------------------

    private void assertTableContainsId(UUID architectureId, String table, String id) {
        ElementInventoryResponse response =
            inventoryService.getInventory(projectId, architectureId);
        boolean found = response.domains().stream()
            .map(Domain::types)
            .flatMap(java.util.List::stream)
            .filter(t -> table.equals(t.entityType()))
            .flatMap(t -> t.instances().stream())
            .anyMatch(inst -> id.equals(inst.id()));
        assertThat(found)
            .as("inventory for arch %s expected to contain %s.%s via the parent chain",
                architectureId, table, id)
            .isTrue();
    }

    private void assertTableDoesNotContainId(UUID architectureId, String table, String id) {
        ElementInventoryResponse response =
            inventoryService.getInventory(projectId, architectureId);
        boolean found = response.domains().stream()
            .map(Domain::types)
            .flatMap(java.util.List::stream)
            .filter(t -> table.equals(t.entityType()))
            .flatMap(t -> t.instances().stream())
            .anyMatch(inst -> id.equals(inst.id()));
        assertThat(found)
            .as("inventory for arch %s must NOT contain %s.%s — leaf-column drift must not leak through",
                architectureId, table, id)
            .isFalse();
    }

    // ------------------------------------------------------------------
    // Schema + seed helpers
    // ------------------------------------------------------------------

    private void seedArchitecture(UUID id, String name) {
        ArchitectureEntity arch = ArchitectureEntity.builder()
            .id(id)
            .projectId(projectId)
            .name(name)
            .archived(false)
            .build();
        architectureRepository.save(arch);
    }

    private String newModelFile(UUID architectureId) {
        String mfId = "mf-" + UUID.randomUUID();
        modelFileRepository.save(ModelFileEntity.builder()
            .id(mfId)
            .filename("mf-" + UUID.randomUUID())
            .description("Test model file")
            .createdAt(OffsetDateTime.now())
            .updatedAt(OffsetDateTime.now())
            .isDefault(false)
            .projectId(projectId)
            .architectureId(architectureId)
            .build());
        return mfId;
    }

    private void ensureArchitectureIdColumn(String table) {
        try {
            jdbcTemplate.execute(
                "ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS architecture_id UUID");
        } catch (DataAccessException e) {
            throw new IllegalStateException(
                "Failed to ensure architecture_id column on " + table + ": " + e.getMessage(), e);
        }
    }

    private void safeDelete(String table) {
        try {
            jdbcTemplate.update("DELETE FROM " + table + " WHERE 1=1");
        } catch (DataAccessException ignored) {
            // Table absent in this H2 fixture variant — fine.
        }
    }
}
