package com.example.architecturemodel.service;

import com.example.architecturemodel.exception.ResourceNotFoundException;
import com.example.architecturemodel.model.dto.GeneratedMigrationBookOfWorkDto;
import com.example.architecturemodel.model.entity.GeneratedMigrationBookOfWorkEntity;
import com.example.architecturemodel.model.entity.GeneratedMigrationBookOfWorkStatus;
import com.example.architecturemodel.repository.entity.GeneratedMigrationBookOfWorkRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Service-layer tests for the CRUD half of
 * {@link GeneratedMigrationBookOfWorkService} -- Task Group 7.
 *
 * <p>Uses {@code @DataJpaTest} + an in-memory H2 JSONB-domain-aliased DB, the
 * same pattern as {@code GeneratedMigrationBookOfWorkPersistenceTest}, plus an
 * {@code @Import} of the service-under-test and its collaborators so the
 * Spring container can wire them.</p>
 *
 * <p>WorkItemRepository is unused on this surface (CRUD only) but the service
 * declares it as a constructor dependency for the save-to-backlog path; we
 * therefore re-use the auto-discovered repository bean from the {@code DataJpaTest}
 * scope. No mocking required.</p>
 *
 * <p>Tests covered (Group 7 acceptance criteria):</p>
 * <ol>
 *   <li>Create draft persists all four JSONB columns and returns the DTO.</li>
 *   <li>List drafts defaults to active; {@code includeArchived=true} returns all.</li>
 *   <li>Get draft 404s on a wrong-project / missing id.</li>
 *   <li>Update draft applies PATCH semantics: omitted JSONB fields survive.</li>
 *   <li>Status transitions {@code draft -> reviewed -> saved} round-trip.</li>
 *   <li>Regenerate-on-same-tuple auto-archives the prior draft (Q-6).</li>
 *   <li>Update with invalid status rejects.</li>
 * </ol>
 *
 * <p>Spec: Product Manager Migration Delivery Plan + Draft Book-of-Work
 * Generation (2026-05-17) -- Task Group 7.</p>
 */
@DataJpaTest
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@TestPropertySource(properties = {
    "spring.datasource.url=jdbc:h2:mem:gmbwservicedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE DOMAIN IF NOT EXISTS JSONB AS JSON"
})
@Import({
    GeneratedMigrationBookOfWorkService.class,
    GeneratedMigrationBookOfWorkService.GeneratedMigrationBookOfWorkItemSaver.class
})
class GeneratedMigrationBookOfWorkServiceTest {

    @Autowired
    private GeneratedMigrationBookOfWorkService service;

    @Autowired
    private GeneratedMigrationBookOfWorkRepository repository;

    @Autowired
    private TestEntityManager entityManager;

    private static GeneratedMigrationBookOfWorkDto buildCreateRequest(
        UUID currentArch, UUID targetArch) {
        Map<String, Object> generationInputs = new LinkedHashMap<>();
        generationInputs.put("product_definition_ref", "pd-1");
        generationInputs.put("architecture_refs", List.of("arch-current", "arch-target"));

        Map<String, Object> generationSummary = new LinkedHashMap<>();
        generationSummary.put("initiative_count", 2);
        generationSummary.put("story_count", 12);

        Map<String, Object> qualityAssessment = new LinkedHashMap<>();
        qualityAssessment.put("overall_score", 0.74);

        Map<String, Object> bookOfWork = new LinkedHashMap<>();
        bookOfWork.put("items", List.of(
            Map.of("id", "i-1", "type", "initiative", "title", "Stand up target services"),
            Map.of("id", "e-1", "type", "epic", "parentId", "i-1", "title", "Service A core")
        ));

        return new GeneratedMigrationBookOfWorkDto(
            null,                       // id -- generated server-side
            null,                       // projectId -- from URL path
            currentArch,
            targetArch,
            null,                       // status -- defaults to draft
            "Test draft",
            "Auto-generated by tests.",
            generationInputs,
            generationSummary,
            qualityAssessment,
            bookOfWork,
            null,                       // createdByTask -- default
            null, null, null, null
        );
    }

    @Test
    @DisplayName("createDraft persists all four JSONB columns and returns the DTO")
    void createDraftPersistsAllJsonbColumns() {
        UUID projectId = UUID.randomUUID();
        UUID currentArch = UUID.randomUUID();
        UUID targetArch = UUID.randomUUID();

        GeneratedMigrationBookOfWorkDto created =
            service.createDraft(projectId, buildCreateRequest(currentArch, targetArch));

        assertThat(created.id()).isNotNull();
        assertThat(created.projectId()).isEqualTo(projectId);
        assertThat(created.status()).isEqualTo(GeneratedMigrationBookOfWorkStatus.DRAFT);
        assertThat(created.title()).isEqualTo("Test draft");
        assertThat(created.generationInputsJson()).containsEntry("product_definition_ref", "pd-1");
        assertThat(created.generationSummaryJson()).containsEntry("initiative_count", 2);
        assertThat(created.qualityAssessmentJson()).containsEntry("overall_score", 0.74);
        assertThat(created.bookOfWorkJson()).containsKey("items");

        // Reload from DB and confirm the row materialised.
        entityManager.flush();
        entityManager.clear();
        GeneratedMigrationBookOfWorkEntity reloaded =
            repository.findById(created.id()).orElseThrow();
        assertThat(reloaded.getCurrentArchitectureId()).isEqualTo(currentArch);
        assertThat(reloaded.getTargetArchitectureId()).isEqualTo(targetArch);
        assertThat(reloaded.getGenerationInputsJson()).isNotNull();
        assertThat(reloaded.getGenerationSummaryJson()).isNotNull();
        assertThat(reloaded.getQualityAssessmentJson()).isNotNull();
        assertThat(reloaded.getBookOfWorkJson()).isNotNull();
    }

    @Test
    @DisplayName("listDrafts defaults to active; includeArchived=true returns all")
    void listDraftsFilterByArchivedStatus() {
        UUID projectId = UUID.randomUUID();

        GeneratedMigrationBookOfWorkDto draft1 = service.createDraft(
            projectId, buildCreateRequest(UUID.randomUUID(), UUID.randomUUID()));
        GeneratedMigrationBookOfWorkDto draft2 = service.createDraft(
            projectId, buildCreateRequest(UUID.randomUUID(), UUID.randomUUID()));

        // Manually archive draft2 to simulate post-regenerate state.
        GeneratedMigrationBookOfWorkEntity arch = repository.findById(draft2.id()).orElseThrow();
        arch.setStatus(GeneratedMigrationBookOfWorkStatus.ARCHIVED);
        repository.save(arch);
        entityManager.flush();
        entityManager.clear();

        List<GeneratedMigrationBookOfWorkDto> activeOnly = service.listDrafts(projectId, false);
        assertThat(activeOnly).hasSize(1);
        assertThat(activeOnly.get(0).id()).isEqualTo(draft1.id());

        List<GeneratedMigrationBookOfWorkDto> all = service.listDrafts(projectId, true);
        assertThat(all).hasSize(2);
        assertThat(all).extracting(GeneratedMigrationBookOfWorkDto::id)
            .containsExactlyInAnyOrder(draft1.id(), draft2.id());
    }

    @Test
    @DisplayName("getDraft throws ResourceNotFoundException for wrong project / missing id")
    void getDraftThrowsResourceNotFoundOnWrongProject() {
        UUID projectId = UUID.randomUUID();
        UUID otherProjectId = UUID.randomUUID();
        GeneratedMigrationBookOfWorkDto created = service.createDraft(
            projectId, buildCreateRequest(UUID.randomUUID(), UUID.randomUUID()));

        // Wrong project for an existing book id.
        assertThatThrownBy(() -> service.getDraft(otherProjectId, created.id()))
            .isInstanceOf(ResourceNotFoundException.class);

        // Missing book id altogether.
        assertThatThrownBy(() -> service.getDraft(projectId, UUID.randomUUID()))
            .isInstanceOf(ResourceNotFoundException.class);

        // Same-project happy path still works.
        GeneratedMigrationBookOfWorkDto roundtrip = service.getDraft(projectId, created.id());
        assertThat(roundtrip.id()).isEqualTo(created.id());
    }

    @Test
    @DisplayName("updateDraft PATCH semantics preserve omitted JSONB columns")
    void updateDraftPatchSemanticsPreserveOmittedFields() {
        UUID projectId = UUID.randomUUID();
        GeneratedMigrationBookOfWorkDto created = service.createDraft(
            projectId, buildCreateRequest(UUID.randomUUID(), UUID.randomUUID()));

        // PATCH touches only title + status; the four JSONB DTO fields are null
        // (omitted). The existing column content MUST survive untouched per
        // project_primitive_double_dto_overwrite.md.
        GeneratedMigrationBookOfWorkDto patch = new GeneratedMigrationBookOfWorkDto(
            null, null,
            null, null,
            GeneratedMigrationBookOfWorkStatus.REVIEWED,
            "Renamed title", null,
            null, null, null, null,
            null, null, null, null, null);

        GeneratedMigrationBookOfWorkDto updated = service.updateDraft(projectId, created.id(), patch);
        assertThat(updated.title()).isEqualTo("Renamed title");
        assertThat(updated.status()).isEqualTo(GeneratedMigrationBookOfWorkStatus.REVIEWED);
        // Critical: the four JSONB columns survived the omitted-fields PATCH.
        assertThat(updated.generationInputsJson()).containsEntry("product_definition_ref", "pd-1");
        assertThat(updated.generationSummaryJson()).containsEntry("initiative_count", 2);
        assertThat(updated.qualityAssessmentJson()).containsEntry("overall_score", 0.74);
        assertThat(updated.bookOfWorkJson()).containsKey("items");
    }

    @Test
    @DisplayName("updateDraft status transitions draft -> reviewed -> saved are accepted")
    void updateDraftStatusTransitionsAccepted() {
        UUID projectId = UUID.randomUUID();
        GeneratedMigrationBookOfWorkDto created = service.createDraft(
            projectId, buildCreateRequest(UUID.randomUUID(), UUID.randomUUID()));

        GeneratedMigrationBookOfWorkDto first = service.updateDraft(projectId, created.id(),
            new GeneratedMigrationBookOfWorkDto(
                null, null, null, null,
                GeneratedMigrationBookOfWorkStatus.REVIEWED,
                null, null, null, null, null, null,
                null, null, null, null, null));
        assertThat(first.status()).isEqualTo(GeneratedMigrationBookOfWorkStatus.REVIEWED);

        GeneratedMigrationBookOfWorkDto second = service.updateDraft(projectId, created.id(),
            new GeneratedMigrationBookOfWorkDto(
                null, null, null, null,
                GeneratedMigrationBookOfWorkStatus.SAVED,
                null, null, null, null, null, null,
                null, null, null, null, null));
        assertThat(second.status()).isEqualTo(GeneratedMigrationBookOfWorkStatus.SAVED);
    }

    @Test
    @DisplayName("updateDraft rejects an invalid status value")
    void updateDraftRejectsInvalidStatus() {
        UUID projectId = UUID.randomUUID();
        GeneratedMigrationBookOfWorkDto created = service.createDraft(
            projectId, buildCreateRequest(UUID.randomUUID(), UUID.randomUUID()));

        assertThatThrownBy(() -> service.updateDraft(projectId, created.id(),
            new GeneratedMigrationBookOfWorkDto(
                null, null, null, null,
                "not-a-status",
                null, null, null, null, null, null,
                null, null, null, null, null)))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("Invalid status");
    }

    @Test
    @DisplayName("Regenerate-on-same-tuple auto-archives the prior active draft (Q-6)")
    void regenerateOnSameTupleArchivesPriorDraft() {
        UUID projectId = UUID.randomUUID();
        UUID currentArch = UUID.randomUUID();
        UUID targetArch = UUID.randomUUID();

        GeneratedMigrationBookOfWorkDto first = service.createDraft(
            projectId, buildCreateRequest(currentArch, targetArch));
        GeneratedMigrationBookOfWorkDto second = service.createDraft(
            projectId, buildCreateRequest(currentArch, targetArch));

        entityManager.flush();
        entityManager.clear();

        GeneratedMigrationBookOfWorkEntity firstReloaded = repository.findById(first.id()).orElseThrow();
        GeneratedMigrationBookOfWorkEntity secondReloaded = repository.findById(second.id()).orElseThrow();
        assertThat(firstReloaded.getStatus())
            .as("Prior draft should be auto-archived on regenerate (Q-6)")
            .isEqualTo(GeneratedMigrationBookOfWorkStatus.ARCHIVED);
        assertThat(secondReloaded.getStatus()).isEqualTo(GeneratedMigrationBookOfWorkStatus.DRAFT);

        // A draft for a DIFFERENT tuple is NOT archived.
        UUID otherTarget = UUID.randomUUID();
        GeneratedMigrationBookOfWorkDto unrelated = service.createDraft(
            projectId, buildCreateRequest(currentArch, otherTarget));
        entityManager.flush();
        entityManager.clear();
        GeneratedMigrationBookOfWorkEntity secondAfter = repository.findById(second.id()).orElseThrow();
        assertThat(secondAfter.getStatus())
            .as("Unrelated tuple draft must NOT archive the same-tuple active draft for a different target")
            .isEqualTo(GeneratedMigrationBookOfWorkStatus.DRAFT);
        assertThat(repository.findById(unrelated.id()).orElseThrow().getStatus())
            .isEqualTo(GeneratedMigrationBookOfWorkStatus.DRAFT);
    }
}
