-- ============================================================================
-- Migration 047: Fix work_item.project_id — TEXT (name) → UUID (FK to project)
--
-- The work_item.project_id column was TEXT storing the project NAME instead of
-- a proper UUID foreign key to project(id). This migration:
--   1. Resolves existing project names to UUIDs
--   2. Deletes orphaned rows whose name doesn't match any project
--   3. Converts the column from TEXT to UUID
--   4. Adds a proper FK constraint with ON DELETE CASCADE
--
-- NOTE: After this migration, deterministic IDs generated by StableIdGenerator
-- (used by BookOfWork and Roadmap parsers) will differ because they incorporate
-- projectId. The first re-import after migration will effectively be a fresh
-- import with new deterministic IDs.
-- ============================================================================

-- Step 1: Resolve project names to UUIDs in existing work_item rows
UPDATE work_item wi
SET project_id = p.id::text
FROM project p
WHERE wi.project_id = p.name;

-- Step 2: Delete orphaned work items whose project_id doesn't match any project UUID
-- (rows that had an invalid or no-longer-existing project name)
DELETE FROM work_item
WHERE project_id NOT IN (SELECT id::text FROM project);

-- Step 3: Alter column type from TEXT to UUID
ALTER TABLE work_item
ALTER COLUMN project_id TYPE UUID USING project_id::uuid;

-- Step 4: Add FK constraint to project table with cascade delete
ALTER TABLE work_item
ADD CONSTRAINT fk_work_item_project
FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE;
