/**
 * OasExportView
 *
 * Direct build 2026-06-11 (oracle weaknesses #5): the "Interface contracts"
 * surface mounted off `MigrationDeliveryPlanRoute` next to the book of work
 * and the schema-migration pack.
 *
 * Deterministic OpenAPI 3.0 contracts generated by the gateway from the
 * architecture model — no LLM, no persistence; a download is a regeneration,
 * so contracts can never go stale. Where the model does not specify something
 * (server URL, response schemas, parameter types) the document carries
 * explicit gap notes and the per-interface gap summary here says exactly what
 * to add to the model to improve the contract.
 *
 * The architecture picker defaults to the route's architecture but lets the
 * user switch — implementation contracts normally come from the TARGET
 * architecture, while the delivery-plan route is usually entered from the
 * current-state architecture.
 */

import React, { useCallback, useEffect, useState } from 'react';
import {
  generateOasForInterface,
  getOasExportDownloadUrl,
  listOasExportInterfaces,
  type OasExportInterfaceSummary,
  type OasExportResult,
} from '../../../api/oasExportApi';
import styles from './DbMigrationPack.module.css';

export interface OasExportViewProps {
  projectId: string;
  /** Initially-selected architecture (the route's active architecture). */
  architectureId: string;
  /** All architectures of the project, for the source picker. */
  architectures: Array<{ id: string; name: string }>;
}

interface RowState {
  busy: boolean;
  result?: OasExportResult;
  error?: string;
}

/** Client-side file download of an in-memory JSON document. */
function downloadJson(document: Record<string, unknown>, filename: string): void {
  const blob = new Blob([JSON.stringify(document, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const anchor = window.document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  window.document.body.appendChild(anchor);
  anchor.click();
  window.document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export const OasExportView: React.FC<OasExportViewProps> = ({
  projectId,
  architectureId,
  architectures,
}) => {
  const [selectedArchitectureId, setSelectedArchitectureId] =
    useState(architectureId);
  const [interfaces, setInterfaces] = useState<OasExportInterfaceSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [rowStates, setRowStates] = useState<Record<string, RowState>>({});

  // (Re)load the interface list whenever the selected architecture changes.
  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    setRowStates({});
    void listOasExportInterfaces(projectId, selectedArchitectureId)
      .then((rows) => {
        if (!cancelled) setInterfaces(rows);
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setInterfaces([]);
          setError(
            err instanceof Error ? err.message : 'Failed to list interfaces.',
          );
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [projectId, selectedArchitectureId]);

  const handleGenerate = useCallback(
    async (interfaceId: string) => {
      setRowStates((prev) => ({ ...prev, [interfaceId]: { busy: true } }));
      try {
        const result = await generateOasForInterface(
          projectId,
          selectedArchitectureId,
          interfaceId,
        );
        setRowStates((prev) => ({
          ...prev,
          [interfaceId]: { busy: false, result },
        }));
      } catch (err) {
        setRowStates((prev) => ({
          ...prev,
          [interfaceId]: {
            busy: false,
            error:
              err instanceof Error
                ? err.message
                : 'Failed to generate the OpenAPI contract.',
          },
        }));
      }
    },
    [projectId, selectedArchitectureId],
  );

  return (
    <div className={styles.surface} data-testid="oas-export-view">
      <div className={styles.surfaceHeader}>
        <div>
          <h2 className={styles.surfaceTitle}>Interface contracts (OpenAPI)</h2>
          <p className={styles.surfaceSubtitle}>
            Deterministic OpenAPI 3.0 contracts generated from the architecture
            model — the same model always produces the same document. Anything
            the model does not specify is marked with an explicit gap note
            instead of being invented; resolve the gaps by enriching the model
            (endpoints, logical entities, server URLs) and regenerate.
          </p>
        </div>
      </div>

      <div className={styles.actionsBar}>
        <span className={styles.filterGroup}>
          <label className={styles.filterLabel} htmlFor="oas-export-arch-select">
            Architecture
          </label>
          <select
            id="oas-export-arch-select"
            data-testid="oas-export-arch-select"
            className={styles.filterSelect}
            value={selectedArchitectureId}
            onChange={(e) => setSelectedArchitectureId(e.target.value)}
          >
            {architectures.map((arch) => (
              <option key={arch.id} value={arch.id}>
                {arch.name}
              </option>
            ))}
            {!architectures.some((a) => a.id === selectedArchitectureId) && (
              <option value={selectedArchitectureId}>
                (current architecture)
              </option>
            )}
          </select>
        </span>
        <a
          className={styles.actionLink}
          data-testid="oas-export-download-all"
          href={getOasExportDownloadUrl(projectId, selectedArchitectureId)}
          download
        >
          Download all contracts (zip)
        </a>
      </div>

      {error && (
        <div className={styles.errorBanner} role="alert" data-testid="oas-export-error">
          {error}
        </div>
      )}

      {loading && <p data-testid="oas-export-loading">Loading interfaces…</p>}

      {!loading && !error && interfaces.length === 0 && (
        <p className={styles.manifestNote} data-testid="oas-export-empty">
          This architecture has no interfaces. Add interfaces and endpoints to
          the model (via discovery save-back or the target-state conversation)
          and they will appear here for contract export.
        </p>
      )}

      {!loading && interfaces.length > 0 && (
        <div className={styles.tableScroll}>
          <table className={styles.dataTable} data-testid="oas-export-table">
            <thead>
              <tr>
                <th>Interface</th>
                <th>Contract</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {interfaces.map((iface) => {
                const state = rowStates[iface.id];
                return (
                  <React.Fragment key={iface.id}>
                    <tr data-testid={`oas-export-row-${iface.id}`}>
                      <td>{iface.name}</td>
                      <td>
                        {state?.result && (
                          <span
                            className={styles.coverageChips}
                            data-testid={`oas-export-result-${iface.id}`}
                          >
                            <span className={styles.coverageChipTranslated}>
                              {state.result.summary.mappedEndpointCount}/
                              {state.result.summary.endpointCount} endpoints
                            </span>
                            <span className={styles.coverageChipFlagged}>
                              {state.result.summary.gapCounts.blocking} blocking gaps
                            </span>
                            <span className={styles.coverageChipSkipped}>
                              {state.result.summary.gapCounts.recommended} recommended
                            </span>
                          </span>
                        )}
                        {state?.error && (
                          <span
                            className={styles.errorBanner}
                            role="alert"
                            data-testid={`oas-export-row-error-${iface.id}`}
                          >
                            {state.error}
                          </span>
                        )}
                        {!state?.result && !state?.error && (
                          <span className={styles.manifestNote}>Not generated yet</span>
                        )}
                      </td>
                      <td>
                        <button
                          type="button"
                          className={styles.actionButton}
                          data-testid={`oas-export-generate-${iface.id}`}
                          disabled={state?.busy === true}
                          onClick={() => void handleGenerate(iface.id)}
                        >
                          {state?.busy
                            ? 'Generating…'
                            : state?.result
                              ? 'Regenerate'
                              : 'Generate'}
                        </button>
                        {state?.result && (
                          <button
                            type="button"
                            className={styles.actionButtonPrimary}
                            data-testid={`oas-export-download-${iface.id}`}
                            onClick={() =>
                              downloadJson(
                                state.result!.document,
                                state.result!.suggestedFilename,
                              )
                            }
                          >
                            Download
                          </button>
                        )}
                      </td>
                    </tr>
                    {state?.result &&
                      (state.result.summary.unmappedEndpoints.length > 0 ||
                        state.result.gapReport.gaps.length > 0) && (
                        <tr data-testid={`oas-export-detail-${iface.id}`}>
                          <td colSpan={3}>
                            <details>
                              <summary>
                                Gap details (
                                {state.result.gapReport.gaps.length} gaps,{' '}
                                {state.result.summary.unmappedEndpoints.length}{' '}
                                unmapped endpoints)
                              </summary>
                              {state.result.summary.unmappedEndpoints.length > 0 && (
                                <>
                                  <p className={styles.manifestSectionTitle}>
                                    Endpoints not expressible in this contract
                                  </p>
                                  <ul className={styles.orderedList}>
                                    {state.result.summary.unmappedEndpoints.map(
                                      (u) => (
                                        <li key={u.endpointId}>
                                          <strong>{u.name}</strong> — {u.reason}
                                        </li>
                                      ),
                                    )}
                                  </ul>
                                </>
                              )}
                              <p className={styles.manifestSectionTitle}>
                                Model gaps affecting contract quality
                              </p>
                              <ul className={styles.orderedList}>
                                {state.result.gapReport.gaps.map((gap, idx) => (
                                  <li key={`${gap.code}-${idx}`}>
                                    <span className={styles.badge}>{gap.severity}</span>{' '}
                                    {gap.message}
                                    {gap.location?.path && (
                                      <>
                                        {' '}
                                        <code>
                                          {gap.location.method} {gap.location.path}
                                        </code>
                                      </>
                                    )}
                                  </li>
                                ))}
                              </ul>
                            </details>
                          </td>
                        </tr>
                      )}
                  </React.Fragment>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default OasExportView;
