/**
 * Hard-coded constants shared across pack-finding scanners.
 *
 * Spec: 2026-05-16 Wire Java + Spring Classic + Maven Findings (D7).
 *
 * Caps live as code constants -- NOT in `config_snapshot` for v1. Promote to
 * config when operators need tunability in a future iteration.
 */

/**
 * Cap on the number of findings any single scanner emits for a given
 * `finding_type` in a single discovery run. Prevents pathological inputs
 * (autogenerated source trees, etc.) from producing thousands of identical
 * findings that drown out the signal in the Findings tab.
 */
export const MAX_FINDINGS_PER_TYPE_PER_RUN = 50;

/**
 * Whether the Maven scanner emits info-severity findings for the detected
 * Java / Spring version when the detected value falls in the "info" cutoff
 * band (`>= 17` for Java, `6.x` for Spring). `true` keeps those visible in
 * the Findings tab as positive-signal observations; `false` would suppress
 * them.
 */
export const EMIT_INFO_FINDINGS_FOR_MAVEN_VERSION = true;
