/**
 * Hypothesis Types (Increment 15)
 *
 * Defines the hypothesis and hypothesis answer interfaces used by the
 * hypothesis-first discovery Q&A validation loop. Hypotheses represent
 * uncertain or ambiguous discovery results that require human confirmation.
 *
 * Data flow position: Phase 1d candidates -> **hypothesis generation** -> Q&A -> refinement
 */

/**
 * Categories of uncertainty that a hypothesis can describe.
 *
 * - `low_confidence`: Candidate confidence is below the auto-accept threshold
 * - `ambiguous_type`: Cluster has an unknown or ambiguous type classification
 * - `conflicting_evidence`: Candidate has conflicting evidence from different sources
 * - `missing_attribute`: Candidate is missing critical attributes in its data payload
 * - `weak_cluster`: Cluster has low confidence or insufficient evidence strength
 */
export type HypothesisCategory =
  | 'low_confidence'
  | 'ambiguous_type'
  | 'conflicting_evidence'
  | 'missing_attribute'
  | 'weak_cluster';

/**
 * Possible statuses for a hypothesis throughout its lifecycle.
 *
 * - `pending`: Hypothesis has been generated but not yet answered
 * - `confirmed`: User confirmed the hypothesis
 * - `denied`: User denied the hypothesis
 * - `partially_confirmed`: User partially confirmed the hypothesis
 * - `needs_more_info`: More information is needed to resolve the hypothesis
 */
export type HypothesisStatus =
  | 'pending'
  | 'confirmed'
  | 'denied'
  | 'partially_confirmed'
  | 'needs_more_info';

/**
 * Verdict values for a hypothesis answer.
 * Matches `HypothesisStatus` excluding `pending` -- only active resolution values.
 */
export type HypothesisVerdict =
  | 'confirmed'
  | 'denied'
  | 'partially_confirmed'
  | 'needs_more_info';

/**
 * A hypothesis describing an uncertain or ambiguous discovery result.
 *
 * Generated by the rule-based hypothesis engine after Phase 1d completion.
 * Each hypothesis references specific candidates, clusters, or evidence atoms
 * that contributed to the uncertainty.
 */
export interface Hypothesis {
  /** Unique identifier (UUID) for this hypothesis. */
  id: string;

  /** The discovery run that produced this hypothesis. */
  runId: string;

  /** The category of uncertainty this hypothesis describes. */
  category: HypothesisCategory;

  /** Whether this hypothesis is about a candidate or a cluster. */
  subjectType: 'candidate' | 'cluster';

  /** The ID of the candidate or cluster this hypothesis is about. */
  subjectId: string;

  /** Human-readable description of the uncertainty. */
  description: string;

  /** Array of atom, relationship, or cluster IDs supporting this hypothesis. */
  evidenceRefs: string[];

  /** Current resolution status of this hypothesis. */
  status: HypothesisStatus;

  /** ISO 8601 timestamp when this hypothesis was created. */
  createdAt: string;
}

/**
 * A structured answer to a hypothesis, capturing the user's verdict.
 *
 * Created when a user responds to a hypothesis question during the Q&A loop.
 * The verdict drives automatic refinement of candidate confidence and cluster
 * membership.
 */
export interface HypothesisAnswer {
  /** The ID of the hypothesis being answered. */
  hypothesisId: string;

  /** The user's verdict on the hypothesis. */
  verdict: HypothesisVerdict;

  /** Optional free-text notes providing additional context for the answer. */
  freeTextNotes?: string;

  /** ISO 8601 timestamp when the answer was provided. */
  answeredAt: string;
}
